/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ActiveSession
 */
export interface ActiveSession {
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  AccessToken?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  Browser?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  Device?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  Os?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  DeviceType?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  City?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  Country?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  Ip?: string;
  /**
   *
   * @type {string}
   * @memberof ActiveSession
   */
  LoginDate?: string;
}
