/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AppleSecretConfiguration } from './apple-secret-configuration';

/**
 *
 * @export
 * @interface AppProvider
 */
export interface AppProvider {
  /**
   * Indicates whether the provider is active.
   * @type {boolean}
   * @memberof AppProvider
   */
  IsActive?: boolean;
  /**
   * The key for the provider application.
   * @type {string}
   * @memberof AppProvider
   */
  Key?: string;
  /**
   * The secret for the provider application.
   * @type {string}
   * @memberof AppProvider
   */
  Secret?: string;
  /**
   * An extra field for additional configuration.
   * @type {string}
   * @memberof AppProvider
   */
  ExtraField1?: string;
  /**
   * Another extra field for additional configuration.
   * @type {string}
   * @memberof AppProvider
   */
  ExtraField2?: string;
  /**
   *
   * @type {AppleSecretConfiguration}
   * @memberof AppProvider
   */
  AppleSecretConfiguration?: AppleSecretConfiguration;
}
