/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AppleSecretConfiguration
 */
export interface AppleSecretConfiguration {
  /**
   * Certificate for Apple configuration
   * @type {string}
   * @memberof AppleSecretConfiguration
   */
  Certificate?: string;
  /**
   * Key identifier for Apple configuration
   * @type {string}
   * @memberof AppleSecretConfiguration
   */
  KeyIdentifier?: string;
  /**
   * Service ID for Apple configuration
   * @type {string}
   * @memberof AppleSecretConfiguration
   */
  ServiceId?: string;
  /**
   * Bundle ID for Apple configuration
   * @type {string}
   * @memberof AppleSecretConfiguration
   */
  BundleId?: string;
  /**
   * Team ID for Apple configuration
   * @type {string}
   * @memberof AppleSecretConfiguration
   */
  TeamId?: string;
}
