/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AuthResponseEmailVerificationData } from './auth-response-email-verification-data';

/**
 *
 * @export
 * @interface AuthResponseEmailVerification
 */
export interface AuthResponseEmailVerification {
  /**
   *
   * @type {boolean}
   * @memberof AuthResponseEmailVerification
   */
  IsPosted?: boolean;
  /**
   *
   * @type {AuthResponseEmailVerificationData}
   * @memberof AuthResponseEmailVerification
   */
  Data?: AuthResponseEmailVerificationData;
}
