/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BatchUploadErrorResponseErrorsInner } from './batch-upload-error-response-errors-inner';

/**
 *
 * @export
 * @interface BatchUploadErrorResponse
 */
export interface BatchUploadErrorResponse {
  /**
   * Error code for identifying the error type.
   * @type {number}
   * @memberof BatchUploadErrorResponse
   */
  ErrorCode: number;
  /**
   * Brief message describing the error.
   * @type {string}
   * @memberof BatchUploadErrorResponse
   */
  Message: string;
  /**
   * Detailed description of the error.
   * @type {string}
   * @memberof BatchUploadErrorResponse
   */
  Description: string;
  /**
   * List of individual field errors.
   * @type {Array<BatchUploadErrorResponseErrorsInner>}
   * @memberof BatchUploadErrorResponse
   */
  Errors?: Array<BatchUploadErrorResponseErrorsInner>;
}
