/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PublicKeyCredentialCreationOptions } from './public-key-credential-creation-options';

/**
 * Container for the WebAuthn registration initiation data
 * @export
 * @interface BeginMFAPasskeyRegistration200ResponseRegisterBeginCredential
 */
export interface BeginMFAPasskeyRegistration200ResponseRegisterBeginCredential {
  /**
   *
   * @type {PublicKeyCredentialCreationOptions}
   * @memberof BeginMFAPasskeyRegistration200ResponseRegisterBeginCredential
   */
  publicKey?: PublicKeyCredentialCreationOptions;
}
