/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CaptchaModel
 */
export interface CaptchaModel {
  /**
   * The Google reCAPTCHA response which is sent to the server for verification.
   * @type {string}
   * @memberof CaptchaModel
   */
  'g-recaptcha-response'?: string | null;
  /**
   * The QQ Captcha ticket which is sent to the server for verification.
   * @type {string}
   * @memberof CaptchaModel
   */
  qq_captcha_ticket?: string | null;
  /**
   * The QQ Captcha random string which is sent to the server for verification.
   * @type {string}
   * @memberof CaptchaModel
   */
  qq_captcha_randstr?: string | null;
  /**
   * The hCaptcha response which is sent to the server for verification.
   * @type {string}
   * @memberof CaptchaModel
   */
  'h-captcha-response'?: string | null;
}
