/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionGroupRoleResponse } from './connection-group-role-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionResponseCore } from './connection-response-core';
// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionResponseVariant } from './connection-response-variant';
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsConnectionBase } from './organizations-connection-base';
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsConnectionBaseAttributes } from './organizations-connection-base-attributes';
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsConnectionSamlBaseIDPCertificate } from './organizations-connection-saml-base-idpcertificate';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlConnectionResponseCoreSPCertificate } from './saml-connection-response-core-spcertificate';

/**
 * @type ConnectionResponse
 * @export
 */
export type ConnectionResponse = ConnectionResponseCore &
  ConnectionResponseVariant &
  OrganizationsConnectionBase;
