/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConsentFormEvent
 */
export interface ConsentFormEvent {
  /**
   * Indicates if the event is custom.
   * @type {boolean}
   * @memberof ConsentFormEvent
   */
  IsCustom?: boolean;
  /**
   * Name of the event.
   * @type {string}
   * @memberof ConsentFormEvent
   */
  Name?: string;
}
