/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ConsentProfileLog } from './consent-profile-log';
// May contain unused imports in some cases
// @ts-ignore
import type { ConsentVersion } from './consent-version';

/**
 *
 * @export
 * @interface ConsentLog
 */
export interface ConsentLog {
  /**
   * Type of update performed
   * @type {string}
   * @memberof ConsentLog
   */
  UpdateType?: string | null;
  /**
   * User agent string
   * @type {string}
   * @memberof ConsentLog
   */
  UserAgent?: string | null;
  /**
   * IP address of the User
   * @type {string}
   * @memberof ConsentLog
   */
  IP?: string | null;
  /**
   * Host information
   * @type {string}
   * @memberof ConsentLog
   */
  Host?: string | null;
  /**
   * Date and time when the log was created
   * @type {string}
   * @memberof ConsentLog
   */
  LoggedOnDate?: string | null;
  /**
   * List of current consent form versions
   * @type {Array<ConsentVersion>}
   * @memberof ConsentLog
   */
  CurrentConsentFormsVersions?: Array<ConsentVersion>;
  /**
   * List of consent profile logs
   * @type {Array<ConsentProfileLog>}
   * @memberof ConsentLog
   */
  ConsentLogs?: Array<ConsentProfileLog> | null;
  /**
   * ObjectId (MongoDB) of the log entry
   * @type {string}
   * @memberof ConsentLog
   */
  Id?: string;
}
