/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConsentOptions
 */
export interface ConsentOptions {
  /**
   * Unique identifier for the consent option.
   * @type {string}
   * @memberof ConsentOptions
   */
  ConsentId?: string;
  /**
   * Title of the consent option.
   * @type {string}
   * @memberof ConsentOptions
   */
  Title?: string;
  /**
   * Description of the consent option.
   * @type {string}
   * @memberof ConsentOptions
   */
  Description?: string;
  /**
   * Creation date of the consent option.
   * @type {string}
   * @memberof ConsentOptions
   */
  CreatedOn?: string | null;
  /**
   * Indicates if the consent option is currently active.
   * @type {boolean}
   * @memberof ConsentOptions
   */
  IsActive?: boolean;
}
