/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Certificates } from './certificates';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlIntegrationCreateCore } from './saml-integration-create-core';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlIntegrationRequest } from './saml-integration-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlIntegrationResponseAssertionConsumerService } from './saml-integration-response-assertion-consumer-service';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlIntegrationResponseAttributesValue } from './saml-integration-response-attributes-value';

/**
 * @type CreateSamlIntegrationRequest
 * @export
 */
export type CreateSamlIntegrationRequest = SamlIntegrationCreateCore & SamlIntegrationRequest;
