/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   * Brief message describing the error.
   * @type {string}
   * @memberof ErrorResponse
   */
  Message?: string;
  /**
   * Detailed description of the error.
   * @type {string}
   * @memberof ErrorResponse
   */
  Description?: string;
  /**
   * Error code for identifying the error type.
   * @type {number}
   * @memberof ErrorResponse
   */
  ErrorCode?: number;
  /**
   * HTTP status code associated with the error.
   * @type {number}
   * @memberof ErrorResponse
   */
  Code?: number | null;
}
