/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { IdentityResponseWithSocialWithoutLogins } from './identity-response-with-social-without-logins';

/**
 *
 * @export
 * @interface IdentitiesResponse
 */
export interface IdentitiesResponse {
  /**
   * List of User Identities with social information but without login details.
   * @type {Array<IdentityResponseWithSocialWithoutLogins>}
   * @memberof IdentitiesResponse
   */
  Data?: Array<IdentityResponseWithSocialWithoutLogins> | null;
}
