/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface JwtClaimAudienceProperty
 */
export interface JwtClaimAudienceProperty {
  /**
   *
   * @type {Array<string>}
   * @memberof JwtClaimAudienceProperty
   */
  ExpectedValues?: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof JwtClaimAudienceProperty
   */
  MatchValue?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof JwtClaimAudienceProperty
   */
  IsMandatory?: boolean | null;
}
