/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginByPhoneCore
 */
export interface LoginByPhoneCore {
  /**
   * The Phone number of the User
   * @type {string}
   * @memberof LoginByPhoneCore
   */
  phone: string;
  /**
   * The Password of the User
   * @type {string}
   * @memberof LoginByPhoneCore
   */
  password: string;
  /**
   * The security answer which is set for the User, this will be used when the User is blocked for the security question.
   * @type {string}
   * @memberof LoginByPhoneCore
   */
  securityAnswer?: string;
}
