/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The age range of the User.
 * @export
 * @interface ManageRegisterModelAgeRange
 */
export interface ManageRegisterModelAgeRange {
  /**
   * The minimum age in the range.
   * @type {number}
   * @memberof ManageRegisterModelAgeRange
   */
  Min?: number | null;
  /**
   * The maximum age in the range.
   * @type {number}
   * @memberof ManageRegisterModelAgeRange
   */
  Max?: number | null;
}
