/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PIN information of the User.
 * @export
 * @interface ManageRegisterModelPINInfo
 */
export interface ManageRegisterModelPINInfo {
  /**
   * The PIN of the User.
   * @type {string}
   * @memberof ManageRegisterModelPINInfo
   */
  PIN?: string | null;
  /**
   * Indicates if the PIN setup was skipped.
   * @type {boolean}
   * @memberof ManageRegisterModelPINInfo
   */
  Skipped?: boolean | null;
  /**
   * Indicates if the PIN is valid.
   * @type {boolean}
   * @memberof ManageRegisterModelPINInfo
   */
  IsValid?: boolean | null;
  /**
   * Indicates if IO validation is required.
   * @type {boolean}
   * @memberof ManageRegisterModelPINInfo
   */
  IOValidationRequired?: boolean;
}
