/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ManageRegisterModelMemberUrlResourcesInner
 */
export interface ManageRegisterModelMemberUrlResourcesInner {
  /**
   * The URL of the resource.
   * @type {string}
   * @memberof ManageRegisterModelMemberUrlResourcesInner
   */
  Url?: string;
  /**
   * The name of the resource URL.
   * @type {string}
   * @memberof ManageRegisterModelMemberUrlResourcesInner
   */
  UrlName?: string;
}
