/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelAddressesInner } from './manage-register-model-addresses-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelAgeRange } from './manage-register-model-age-range';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelBadgesInner } from './manage-register-model-badges-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelBooksInner } from './manage-register-model-books-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelCertificationsInner } from './manage-register-model-certifications-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelConsents } from './manage-register-model-consents';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelCountry } from './manage-register-model-country';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelCoursesInner } from './manage-register-model-courses-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelEducationsInner } from './manage-register-model-educations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelEmailInner } from './manage-register-model-email-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelFamilyInner } from './manage-register-model-family-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelFavoriteThingsInner } from './manage-register-model-favorite-things-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelGamesInner } from './manage-register-model-games-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelJobBookmarksInner } from './manage-register-model-job-bookmarks-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelLanguagesInner } from './manage-register-model-languages-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelMemberUrlResourcesInner } from './manage-register-model-member-url-resources-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelMoviesInner } from './manage-register-model-movies-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelMutualFriendsInner } from './manage-register-model-mutual-friends-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelPINInfo } from './manage-register-model-pininfo';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelPatentsInner } from './manage-register-model-patents-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelPlacesLivedInner } from './manage-register-model-places-lived-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelPositionsInner } from './manage-register-model-positions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelPrivacyPolicy } from './manage-register-model-privacy-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelProjectsInner } from './manage-register-model-projects-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelProviderAccessCredential } from './manage-register-model-provider-access-credential';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelPublicationsInner } from './manage-register-model-publications-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelRecommendationsReceivedInner } from './manage-register-model-recommendations-received-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelRelatedProfileViewsInner } from './manage-register-model-related-profile-views-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelSubscription } from './manage-register-model-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelSuggestions } from './manage-register-model-suggestions';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelTelevisionShowInner } from './manage-register-model-television-show-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ManageRegisterModelVolunteerInner } from './manage-register-model-volunteer-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileAwardsInner } from './profile-awards-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileCurrentStatusInner } from './profile-current-status-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileExternalIdsInner } from './profile-external-ids-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileIMAccountsInner } from './profile-imaccounts-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileInspirationalPeopleInner } from './profile-inspirational-people-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileInterestsInner } from './profile-interests-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePhoneNumbersInner } from './profile-phone-numbers-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSkillsInner } from './profile-skills-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSportsInner } from './profile-sports-inner';

/**
 *
 * @export
 * @interface ManageRegisterModel
 */
export interface ManageRegisterModel {
  /**
   * The unique identifier (UID) of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Uid?: string | null;
  /**
   * The Username of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  UserName?: string | null;
  /**
   * The Phone ID of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  PhoneId?: string | null;
  /**
   * The gender of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Gender?: string | null;
  /**
   * The birth date of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  BirthDate?: string | null;
  /**
   * The prefix for the User\'s name.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Prefix?: string | null;
  /**
   * The first name of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  FirstName?: string | null;
  /**
   * The middle name of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  MiddleName?: string | null;
  /**
   * The last name of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  LastName?: string | null;
  /**
   * The suffix for the User\'s name.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Suffix?: string | null;
  /**
   * The nickname of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  NickName?: string | null;
  /**
   * The profile name of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ProfileName?: string | null;
  /**
   * A brief description about the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  About?: string | null;
  /**
   * The company the User is associated with.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Company?: string | null;
  /**
   * The URL of the User\'s profile image.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ImageUrl?: string | null;
  /**
   * The time zone of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  TimeZone?: string | null;
  /**
   * The website of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Website?: string | null;
  /**
   * The URL of the User\'s thumbnail image.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ThumbnailImageUrl?: string | null;
  /**
   * The URL of the User\'s favicon.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Favicon?: string | null;
  /**
   * The URL of the User\'s profile.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ProfileUrl?: string | null;
  /**
   * The hometown of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  HomeTown?: string | null;
  /**
   * The state of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  State?: string | null;
  /**
   * The city of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  City?: string | null;
  /**
   * The industry of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Industry?: string | null;
  /**
   * The local language of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  LocalLanguage?: string | null;
  /**
   * The language of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Language?: string | null;
  /**
   * The URL of the User\'s cover photo.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  CoverPhoto?: string | null;
  /**
   * The tagline of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  TagLine?: string | null;
  /**
   * The main address of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  MainAddress?: string | null;
  /**
   * The local city of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  LocalCity?: string | null;
  /**
   * The profile city of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ProfileCity?: string | null;
  /**
   * The local country of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  LocalCountry?: string | null;
  /**
   * The profile country of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ProfileCountry?: string | null;
  /**
   * The quota assigned to the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Quota?: string | null;
  /**
   * The religion of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Religion?: string | null;
  /**
   * The political views of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Political?: string | null;
  /**
   * The relationship status of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  RelationshipStatus?: string | null;
  /**
   * The HTTPS URL of the User\'s profile image.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  HttpsImageUrl?: string | null;
  /**
   * Indicates if geolocation is enabled for the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  IsGeoEnabled?: string | null;
  /**
   * The associations of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Associations?: string | null;
  /**
   * The honors received by the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Honors?: string | null;
  /**
   * The number of public repositories owned by the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  PublicRepository?: string | null;
  /**
   * The URL of the User\'s repository.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  RepositoryUrl?: string | null;
  /**
   * The professional headline of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ProfessionalHeadline?: string | null;
  /**
   * The preferred currency of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Currency?: string | null;
  /**
   * The URL of the User\'s starred items.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  StarredUrl?: string | null;
  /**
   * The URL of the User\'s gists.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  GistsUrl?: string | null;
  /**
   * The URL of the User\'s Gravatar image.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  GravatarImageUrl?: string | null;
  /**
   * The external User login ID.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ExternalUserLoginId?: string | null;
  /**
   * Interests of the User.
   * @type {Array<string>}
   * @memberof ManageRegisterModel
   */
  InterestedIn?: Array<string> | null;
  /**
   * The number of followers the User has.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  FollowersCount?: number | null;
  /**
   * The number of friends the User has.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  FriendsCount?: number | null;
  /**
   * The total number of statuses posted by the User.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  TotalStatusesCount?: number | null;
  /**
   * The number of recommenders for the User.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  NumRecommenders?: number | null;
  /**
   * The total number of private repositories owned by the User.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  TotalPrivateRepository?: number | null;
  /**
   * The total number of public gists owned by the User.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  PublicGists?: number | null;
  /**
   * The total number of private gists owned by the User.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  PrivateGists?: number | null;
  /**
   * The session limit for the User.
   * @type {number}
   * @memberof ManageRegisterModel
   */
  SessionLimit?: number | null;
  /**
   * Custom fields associated with the User.
   * @type {{ [key: string]: string; }}
   * @memberof ManageRegisterModel
   */
  CustomFields?: { [key: string]: string } | null;
  /**
   * URLs of the User\'s profile images.
   * @type {{ [key: string]: string; }}
   * @memberof ManageRegisterModel
   */
  ProfileImageUrls?: { [key: string]: string } | null;
  /**
   * The User\'s web profiles.
   * @type {{ [key: string]: string; }}
   * @memberof ManageRegisterModel
   */
  WebProfiles?: { [key: string]: string } | null;
  /**
   * Security question answers for the User.
   * @type {{ [key: string]: string; }}
   * @memberof ManageRegisterModel
   */
  SecurityQuestionAnswer?: { [key: string]: string } | null;
  /**
   *
   * @type {ManageRegisterModelCountry}
   * @memberof ManageRegisterModel
   */
  Country?: ManageRegisterModelCountry;
  /**
   *
   * @type {ManageRegisterModelProviderAccessCredential}
   * @memberof ManageRegisterModel
   */
  ProviderAccessCredential?: ManageRegisterModelProviderAccessCredential;
  /**
   *
   * @type {ManageRegisterModelSuggestions}
   * @memberof ManageRegisterModel
   */
  Suggestions?: ManageRegisterModelSuggestions;
  /**
   *
   * @type {ManageRegisterModelSubscription}
   * @memberof ManageRegisterModel
   */
  Subscription?: ManageRegisterModelSubscription;
  /**
   *
   * @type {ManageRegisterModelAgeRange}
   * @memberof ManageRegisterModel
   */
  AgeRange?: ManageRegisterModelAgeRange;
  /**
   *
   * @type {ManageRegisterModelPrivacyPolicy}
   * @memberof ManageRegisterModel
   */
  PrivacyPolicy?: ManageRegisterModelPrivacyPolicy;
  /**
   *
   * @type {ManageRegisterModelPINInfo}
   * @memberof ManageRegisterModel
   */
  PINInfo?: ManageRegisterModelPINInfo;
  /**
   * List of addresses associated with the User.
   * @type {Array<ManageRegisterModelAddressesInner>}
   * @memberof ManageRegisterModel
   */
  Addresses?: Array<ManageRegisterModelAddressesInner>;
  /**
   * List of positions held by the User.
   * @type {Array<ManageRegisterModelPositionsInner>}
   * @memberof ManageRegisterModel
   */
  Positions?: Array<ManageRegisterModelPositionsInner>;
  /**
   * List of educational qualifications of the User.
   * @type {Array<ManageRegisterModelEducationsInner>}
   * @memberof ManageRegisterModel
   */
  Educations?: Array<ManageRegisterModelEducationsInner>;
  /**
   * List of Phone numbers associated with the User.
   * @type {Array<ProfilePhoneNumbersInner>}
   * @memberof ManageRegisterModel
   */
  PhoneNumbers?: Array<ProfilePhoneNumbersInner>;
  /**
   * List of instant messaging accounts associated with the User.
   * @type {Array<ProfileIMAccountsInner>}
   * @memberof ManageRegisterModel
   */
  IMAccounts?: Array<ProfileIMAccountsInner>;
  /**
   * List of interests of the User.
   * @type {Array<ProfileInterestsInner>}
   * @memberof ManageRegisterModel
   */
  Interests?: Array<ProfileInterestsInner>;
  /**
   * List of sports the User is interested in.
   * @type {Array<ProfileSportsInner>}
   * @memberof ManageRegisterModel
   */
  Sports?: Array<ProfileSportsInner>;
  /**
   * List of inspirational people for the User.
   * @type {Array<ProfileInspirationalPeopleInner>}
   * @memberof ManageRegisterModel
   */
  InspirationalPeople?: Array<ProfileInspirationalPeopleInner>;
  /**
   * List of awards received by the User.
   * @type {Array<ProfileAwardsInner>}
   * @memberof ManageRegisterModel
   */
  Awards?: Array<ProfileAwardsInner>;
  /**
   * List of skills possessed by the User.
   * @type {Array<ProfileSkillsInner>}
   * @memberof ManageRegisterModel
   */
  Skills?: Array<ProfileSkillsInner>;
  /**
   * List of current statuses of the User.
   * @type {Array<ProfileCurrentStatusInner>}
   * @memberof ManageRegisterModel
   */
  CurrentStatus?: Array<ProfileCurrentStatusInner>;
  /**
   * List of certifications obtained by the User.
   * @type {Array<ManageRegisterModelCertificationsInner>}
   * @memberof ManageRegisterModel
   */
  Certifications?: Array<ManageRegisterModelCertificationsInner>;
  /**
   * List of courses completed by the User.
   * @type {Array<ManageRegisterModelCoursesInner>}
   * @memberof ManageRegisterModel
   */
  Courses?: Array<ManageRegisterModelCoursesInner>;
  /**
   * List of volunteer experiences of the User.
   * @type {Array<ManageRegisterModelVolunteerInner>}
   * @memberof ManageRegisterModel
   */
  Volunteer?: Array<ManageRegisterModelVolunteerInner>;
  /**
   * List of recommendations received by the User.
   * @type {Array<ManageRegisterModelRecommendationsReceivedInner>}
   * @memberof ManageRegisterModel
   */
  RecommendationsReceived?: Array<ManageRegisterModelRecommendationsReceivedInner>;
  /**
   * List of languages known by the User.
   * @type {Array<ManageRegisterModelLanguagesInner>}
   * @memberof ManageRegisterModel
   */
  Languages?: Array<ManageRegisterModelLanguagesInner>;
  /**
   * List of projects associated with the User.
   * @type {Array<ManageRegisterModelProjectsInner>}
   * @memberof ManageRegisterModel
   */
  Projects?: Array<ManageRegisterModelProjectsInner>;
  /**
   * List of games the User is interested in.
   * @type {Array<ManageRegisterModelGamesInner>}
   * @memberof ManageRegisterModel
   */
  Games?: Array<ManageRegisterModelGamesInner>;
  /**
   * List of family members associated with the User.
   * @type {Array<ManageRegisterModelFamilyInner>}
   * @memberof ManageRegisterModel
   */
  Family?: Array<ManageRegisterModelFamilyInner>;
  /**
   * List of television shows the User is interested in.
   * @type {Array<ManageRegisterModelTelevisionShowInner>}
   * @memberof ManageRegisterModel
   */
  TelevisionShow?: Array<ManageRegisterModelTelevisionShowInner>;
  /**
   * List of mutual friends associated with the User.
   * @type {Array<ManageRegisterModelMutualFriendsInner>}
   * @memberof ManageRegisterModel
   */
  MutualFriends?: Array<ManageRegisterModelMutualFriendsInner>;
  /**
   * List of movies the User is interested in.
   * @type {Array<ManageRegisterModelMoviesInner>}
   * @memberof ManageRegisterModel
   */
  Movies?: Array<ManageRegisterModelMoviesInner>;
  /**
   * List of books the User is interested in.
   * @type {Array<ManageRegisterModelBooksInner>}
   * @memberof ManageRegisterModel
   */
  Books?: Array<ManageRegisterModelBooksInner>;
  /**
   * List of patents associated with the User.
   * @type {Array<ManageRegisterModelPatentsInner>}
   * @memberof ManageRegisterModel
   */
  Patents?: Array<ManageRegisterModelPatentsInner>;
  /**
   * List of favorite things of the User.
   * @type {Array<ManageRegisterModelFavoriteThingsInner>}
   * @memberof ManageRegisterModel
   */
  FavoriteThings?: Array<ManageRegisterModelFavoriteThingsInner>;
  /**
   * List of related profile views for the User.
   * @type {Array<ManageRegisterModelRelatedProfileViewsInner>}
   * @memberof ManageRegisterModel
   */
  RelatedProfileViews?: Array<ManageRegisterModelRelatedProfileViewsInner>;
  /**
   * List of places the User has lived.
   * @type {Array<ManageRegisterModelPlacesLivedInner>}
   * @memberof ManageRegisterModel
   */
  PlacesLived?: Array<ManageRegisterModelPlacesLivedInner>;
  /**
   * List of publications associated with the User.
   * @type {Array<ManageRegisterModelPublicationsInner>}
   * @memberof ManageRegisterModel
   */
  Publications?: Array<ManageRegisterModelPublicationsInner>;
  /**
   * List of job bookmarks associated with the User.
   * @type {Array<ManageRegisterModelJobBookmarksInner>}
   * @memberof ManageRegisterModel
   */
  JobBookmarks?: Array<ManageRegisterModelJobBookmarksInner>;
  /**
   * List of badges associated with the User.
   * @type {Array<ManageRegisterModelBadgesInner>}
   * @memberof ManageRegisterModel
   */
  Badges?: Array<ManageRegisterModelBadgesInner>;
  /**
   * List of member URL resources associated with the User.
   * @type {Array<ManageRegisterModelMemberUrlResourcesInner>}
   * @memberof ManageRegisterModel
   */
  MemberUrlResources?: Array<ManageRegisterModelMemberUrlResourcesInner>;
  /**
   * List of external IDs associated with the User.
   * @type {Array<ProfileExternalIdsInner>}
   * @memberof ManageRegisterModel
   */
  ExternalIds?: Array<ProfileExternalIdsInner>;
  /**
   * Indicates if the User is subscribed to emails.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  IsEmailSubscribed?: boolean | null;
  /**
   * Indicates if the User Account is protected.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  IsProtected?: boolean | null;
  /**
   * Indicates if the User is hireable.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  Hireable?: boolean | null;
  /**
   * Indicates if two-factor authentication is enabled for the User.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  IsTwoFactorAuthenticationEnabled?: boolean | null;
  /**
   * Indicates if the User Account is active.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  IsActive?: boolean | null;
  /**
   * Indicates if the User Account is deleted.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  IsDeleted?: boolean | null;
  /**
   * Indicates if the User\'s Email is verified.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  EmailVerified?: boolean | null;
  /**
   * Indicates if the User\'s Phone ID is verified.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  PhoneIdVerified?: boolean | null;
  /**
   * Indicates if login is disabled for the User.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  DisableLogin?: boolean | null;
  /**
   * Indicates if the User\'s login is locked.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  IsLoginLocked?: boolean | null;
  /**
   * Indicates if the User has accepted the Privacy Policy.
   * @type {boolean}
   * @memberof ManageRegisterModel
   */
  AcceptPrivacyPolicy?: boolean | null;
  /**
   * The response field for reCAPTCHA verification.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ReCaptchaResponseField?: string | null;
  /**
   * The challenge field for reCAPTCHA verification.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  ReCaptchaChallengeField?: string | null;
  /**
   * The source of the User\'s registration.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  RegistrationSource?: string | null;
  /**
   * The full name of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  FullName?: string | null;
  /**
   *
   * @type {ManageRegisterModelConsents}
   * @memberof ManageRegisterModel
   */
  Consents?: ManageRegisterModelConsents;
  /**
   * The Password of the User.
   * @type {string}
   * @memberof ManageRegisterModel
   */
  Password?: string;
  /**
   * List of Email addresses associated with the User.
   * @type {Array<ManageRegisterModelEmailInner>}
   * @memberof ManageRegisterModel
   */
  Email?: Array<ManageRegisterModelEmailInner>;
}
