/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Subscription details of the User.
 * @export
 * @interface ManageRegisterModelSubscription
 */
export interface ManageRegisterModelSubscription {
  /**
   * The name of the subscription.
   * @type {string}
   * @memberof ManageRegisterModelSubscription
   */
  Name?: string | null;
  /**
   * The allocated space for the subscription.
   * @type {string}
   * @memberof ManageRegisterModelSubscription
   */
  Space?: string | null;
  /**
   * The number of private repositories allowed.
   * @type {string}
   * @memberof ManageRegisterModelSubscription
   */
  PrivateRepos?: string | null;
  /**
   * The number of collaborators allowed.
   * @type {string}
   * @memberof ManageRegisterModelSubscription
   */
  Collaborators?: string | null;
}
