/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ManageRegisterModelAddressesInner
 */
export interface ManageRegisterModelAddressesInner {
  /**
   * The type of address (e.g., Home, Work).
   * @type {string}
   * @memberof ManageRegisterModelAddressesInner
   */
  Type?: string;
  /**
   * The first line of the address.
   * @type {string}
   * @memberof ManageRegisterModelAddressesInner
   */
  Address1?: string;
  /**
   * The city of the address.
   * @type {string}
   * @memberof ManageRegisterModelAddressesInner
   */
  City?: string;
  /**
   * The state of the address.
   * @type {string}
   * @memberof ManageRegisterModelAddressesInner
   */
  State?: string;
  /**
   * The country of the address.
   * @type {string}
   * @memberof ManageRegisterModelAddressesInner
   */
  Country?: string;
}
