/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Details of the job.
 * @export
 * @interface ManageRegisterModelJobBookmarksInnerJob
 */
export interface ManageRegisterModelJobBookmarksInnerJob {
  /**
   * The ID of the job.
   * @type {string}
   * @memberof ManageRegisterModelJobBookmarksInnerJob
   */
  Id?: string;
  /**
   * The title of the job.
   * @type {string}
   * @memberof ManageRegisterModelJobBookmarksInnerJob
   */
  Title?: string;
  /**
   * The company offering the job.
   * @type {string}
   * @memberof ManageRegisterModelJobBookmarksInnerJob
   */
  Company?: string;
}
