/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ManageRegisterModelMutualFriendsInner
 */
export interface ManageRegisterModelMutualFriendsInner {
  /**
   * The ID of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  Id?: string;
  /**
   * The name of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  Name?: string;
  /**
   * The first name of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  FirstName?: string;
  /**
   * The last name of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  LastName?: string;
  /**
   * The birthday of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  Birthday?: string;
  /**
   * The hometown of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  Hometown?: string;
  /**
   * The profile link of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  Link?: string;
  /**
   * The gender of the mutual friend.
   * @type {string}
   * @memberof ManageRegisterModelMutualFriendsInner
   */
  Gender?: string;
}
