/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ManageRegisterModelGamesInner
 */
export interface ManageRegisterModelGamesInner {
  /**
   * The ID of the game.
   * @type {string}
   * @memberof ManageRegisterModelGamesInner
   */
  Id?: string;
  /**
   * The category of the game.
   * @type {string}
   * @memberof ManageRegisterModelGamesInner
   */
  Category?: string;
  /**
   * The name of the game.
   * @type {string}
   * @memberof ManageRegisterModelGamesInner
   */
  Name?: string;
  /**
   * The date the game was added.
   * @type {string}
   * @memberof ManageRegisterModelGamesInner
   */
  CreatedDate?: string;
}
