/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * OAuth Revoke Refresh Token Request
 * @export
 * @interface OAuthRevokeRefreshToken
 */
export interface OAuthRevokeRefreshToken {
  /**
   *
   * @type {string}
   * @memberof OAuthRevokeRefreshToken
   */
  client_id: string;
  /**
   *
   * @type {string}
   * @memberof OAuthRevokeRefreshToken
   */
  client_secret: string;
  /**
   *
   * @type {string}
   * @memberof OAuthRevokeRefreshToken
   */
  token: string;
}
