/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OAuthClientResponseBackChannelLogoutLogoutInitiatorIntiators
 */
export interface OAuthClientResponseBackChannelLogoutLogoutInitiatorIntiators {
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponseBackChannelLogoutLogoutInitiatorIntiators
   */
  RPLogout?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponseBackChannelLogoutLogoutInitiatorIntiators
   */
  IDPLogout?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponseBackChannelLogoutLogoutInitiatorIntiators
   */
  PasswordChange?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponseBackChannelLogoutLogoutInitiatorIntiators
   */
  AccountDelete?: boolean;
}
