/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OAuthIntegrationBaseModelConnections } from './oauth-integration-base-model-connections';

/**
 *
 * @export
 * @interface OAuthIntegrationBaseModel
 */
export interface OAuthIntegrationBaseModel {
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthIntegrationBaseModel
   */
  RedirectURIs?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthIntegrationBaseModel
   */
  AllowedScopes?: Array<OAuthIntegrationBaseModelAllowedScopesEnum>;
  /**
   * Only authorization_code and refresh_token are permitted for OAuth integrations.
   * @type {Array<string>}
   * @memberof OAuthIntegrationBaseModel
   */
  GrantTypes?: Array<OAuthIntegrationBaseModelGrantTypesEnum>;
  /**
   *
   * @type {string}
   * @memberof OAuthIntegrationBaseModel
   */
  AccessTokenMappingTemplate?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthIntegrationBaseModel
   */
  IdTokenMappingTemplate?: string;
  /**
   * Access token lifetime in seconds. Defaults to 3600 when omitted.
   * @type {number}
   * @memberof OAuthIntegrationBaseModel
   */
  AccessTokenTTL?: number;
  /**
   * ID token lifetime in seconds. Defaults to 3600 when omitted.
   * @type {number}
   * @memberof OAuthIntegrationBaseModel
   */
  IDTokenTTL?: number;
  /**
   * Refresh token lifetime in seconds. Defaults to 86400 when omitted.
   * @type {number}
   * @memberof OAuthIntegrationBaseModel
   */
  RefreshTokenTTL?: number;
  /**
   *
   * @type {boolean}
   * @memberof OAuthIntegrationBaseModel
   */
  EnablePKCE?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OAuthIntegrationBaseModel
   */
  IsPrebuiltIntegration?: boolean;
  /**
   *
   * @type {string}
   * @memberof OAuthIntegrationBaseModel
   */
  IntegrationType?: string;
  /**
   * Token-endpoint client authentication method. Defaults to client_secret_post when omitted.
   * @type {string}
   * @memberof OAuthIntegrationBaseModel
   */
  TokenAuthMethod?: OAuthIntegrationBaseModelTokenAuthMethodEnum;
  /**
   * Name of the identity-orchestration workflow the authorize request falls back to when it carries no workflow parameter. Requires the IDENTITY_ORCHESTRATION feature; ignored when it is disabled. The workflow must already exist on the tenant, otherwise the request is rejected as an invalid integration configuration. Surrounding whitespace is trimmed; send an empty or blank string to clear it.
   * @type {string}
   * @memberof OAuthIntegrationBaseModel
   */
  DefaultWorkflow?: string;
  /**
   *
   * @type {OAuthIntegrationBaseModelConnections}
   * @memberof OAuthIntegrationBaseModel
   */
  Connections?: OAuthIntegrationBaseModelConnections;
}

/**
 * @export
 * @enum {string}
 */
export enum OAuthIntegrationBaseModelAllowedScopesEnum {
  openid = 'openid',
  email = 'email',
  phone = 'phone',
  profile = 'profile',
  address = 'address',
}
/**
 * @export
 * @enum {string}
 */
export enum OAuthIntegrationBaseModelGrantTypesEnum {
  authorization_code = 'authorization_code',
  refresh_token = 'refresh_token',
}
/**
 * @export
 * @enum {string}
 */
export enum OAuthIntegrationBaseModelTokenAuthMethodEnum {
  client_secret_basic = 'client_secret_basic',
  client_secret_post = 'client_secret_post',
  client_secret_auto = 'client_secret_auto',
  none = 'none',
}
