/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OAuthClientRequestDeviceCodeConfig
 */
export interface OAuthClientRequestDeviceCodeConfig {
  /**
   *
   * @type {string}
   * @memberof OAuthClientRequestDeviceCodeConfig
   */
  AfterVerificationUrl?: string;
  /**
   *
   * @type {number}
   * @memberof OAuthClientRequestDeviceCodeConfig
   */
  DeviceCodeExpire?: number;
  /**
   *
   * @type {number}
   * @memberof OAuthClientRequestDeviceCodeConfig
   */
  PollingInterval?: number;
  /**
   *
   * @type {string}
   * @memberof OAuthClientRequestDeviceCodeConfig
   */
  UserCodeCharacterSet?: OAuthClientRequestDeviceCodeConfigUserCodeCharacterSetEnum;
  /**
   *
   * @type {string}
   * @memberof OAuthClientRequestDeviceCodeConfig
   */
  UserCodeMask?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthClientRequestDeviceCodeConfig
   */
  VerificationUrl?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum OAuthClientRequestDeviceCodeConfigUserCodeCharacterSetEnum {
  Base20 = 'Base20',
  Alpha = 'Alpha',
  Digits = 'Digits',
  Alphanumeric = 'Alphanumeric',
}
