/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Authorization Code PKCE Flow
 * @export
 * @interface OAuthAuthorizationCodePKCEFlow
 */
export interface OAuthAuthorizationCodePKCEFlow {
  /**
   *
   * @type {string}
   * @memberof OAuthAuthorizationCodePKCEFlow
   */
  client_id: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAuthorizationCodePKCEFlow
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAuthorizationCodePKCEFlow
   */
  code_verifier: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAuthorizationCodePKCEFlow
   */
  grant_type: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAuthorizationCodePKCEFlow
   */
  redirect_uri: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAuthorizationCodePKCEFlow
   */
  response_type?: string;
}
