/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OAuthDynamicClientResponseCore
 */
export interface OAuthDynamicClientResponseCore {
  /**
   * Unique client identifier issued by the authorization server.
   * @type {string}
   * @memberof OAuthDynamicClientResponseCore
   */
  client_id?: string;
  /**
   * Client secret. Only returned for confidential clients.
   * @type {string}
   * @memberof OAuthDynamicClientResponseCore
   */
  client_secret?: string;
  /**
   * Unix timestamp when the client_id was issued.
   * @type {number}
   * @memberof OAuthDynamicClientResponseCore
   */
  client_id_issued_at?: number;
  /**
   * Unix timestamp when the client_secret expires. 0 means it does not expire.
   * @type {number}
   * @memberof OAuthDynamicClientResponseCore
   */
  client_secret_expires_at?: number;
  /**
   * Bearer token to access the client configuration endpoint. Only returned on initial registration.
   * @type {string}
   * @memberof OAuthDynamicClientResponseCore
   */
  registration_access_token?: string;
  /**
   * URL of the client configuration endpoint for this client.
   * @type {string}
   * @memberof OAuthDynamicClientResponseCore
   */
  registration_client_uri?: string;
}
