/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OAuthClientResponseBackChannelLogout } from './oauth-client-response-back-channel-logout';
// May contain unused imports in some cases
// @ts-ignore
import type { OAuthClientResponseConnections } from './oauth-client-response-connections';
// May contain unused imports in some cases
// @ts-ignore
import type { OAuthClientResponseDeviceCodeConfig } from './oauth-client-response-device-code-config';
// May contain unused imports in some cases
// @ts-ignore
import type { OAuthClientResponseJwtTokenConfig } from './oauth-client-response-jwt-token-config';
// May contain unused imports in some cases
// @ts-ignore
import type { OAuthClientResponseRefreshTokenRotation } from './oauth-client-response-refresh-token-rotation';

/**
 *
 * @export
 * @interface OAuthClientResponse
 */
export interface OAuthClientResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  AllowedCorsOrigin?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  AllowedScopes?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  AllowedWebOrigin?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof OAuthClientResponse
   */
  AppId?: number;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  AppName?: string;
  /**
   *
   * @type {{ [key: string]: Array<string>; }}
   * @memberof OAuthClientResponse
   */
  AudienceScopes?: { [key: string]: Array<string> };
  /**
   *
   * @type {OAuthClientResponseBackChannelLogout}
   * @memberof OAuthClientResponse
   */
  BackChannelLogout?: OAuthClientResponseBackChannelLogout | null;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  ClientId?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  ClientSecret?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  ClientType?: OAuthClientResponseClientTypeEnum;
  /**
   *
   * @type {OAuthClientResponseConnections}
   * @memberof OAuthClientResponse
   */
  Connections?: OAuthClientResponseConnections;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  CreatedDate?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  Description?: string;
  /**
   *
   * @type {OAuthClientResponseDeviceCodeConfig}
   * @memberof OAuthClientResponse
   */
  DeviceCodeConfig?: OAuthClientResponseDeviceCodeConfig | null;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponse
   */
  EnableCorsOrigin?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponse
   */
  ForceReAuthentication?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponse
   */
  GlobalClient?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  GrantTypes?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  IdTokenAudiences?: Array<string>;
  /**
   *
   * @type {OAuthClientResponseJwtTokenConfig}
   * @memberof OAuthClientResponse
   */
  JwtTokenConfig?: OAuthClientResponseJwtTokenConfig | null;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  LastModifiedDate?: string | null;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  LoginUrl?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  LoginRedirectUri?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OAuthClientResponse
   */
  LogoutRedirectUri?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  AccessTokenMappingTemplate?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  IdTokenMappingTemplate?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof OAuthClientResponse
   */
  Mapping?: { [key: string]: string };
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof OAuthClientResponse
   */
  Metadata?: { [key: string]: string };
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponse
   */
  RedirectURIExactMatch?: boolean;
  /**
   *
   * @type {OAuthClientResponseRefreshTokenRotation}
   * @memberof OAuthClientResponse
   */
  RefreshTokenRotation?: OAuthClientResponseRefreshTokenRotation | null;
  /**
   *
   * @type {number}
   * @memberof OAuthClientResponse
   */
  RefreshTokenTTL?: number;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  Secret?: string;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponse
   */
  SignedUserInfo?: boolean;
  /**
   *
   * @type {string}
   * @memberof OAuthClientResponse
   */
  TokenAuthMethod?: string;
  /**
   *
   * @type {boolean}
   * @memberof OAuthClientResponse
   */
  TokenWebOriginMatch?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum OAuthClientResponseClientTypeEnum {
  public = 'public',
  confidential = 'confidential',
}
