/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * M2M Token Response
 * @export
 * @interface OAuthM2MTokenResponse
 */
export interface OAuthM2MTokenResponse {
  /**
   *
   * @type {string}
   * @memberof OAuthM2MTokenResponse
   */
  access_token?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthM2MTokenResponse
   */
  expire_in?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthM2MTokenResponse
   */
  token_type?: string;
}
