/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * OIDC Discovery Config Response
 * @export
 * @interface OIDCDiscoveryResponse
 */
export interface OIDCDiscoveryResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  acr_values_supported?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  authorization_endpoint?: string;
  /**
   *
   * @type {boolean}
   * @memberof OIDCDiscoveryResponse
   */
  backchannel_logout_session_supported?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OIDCDiscoveryResponse
   */
  backchannel_logout_supported?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  claims_supported?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  code_challenge_methods_supported?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  end_session_endpoint?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  grant_types_supported?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  id_token_signing_alg_values_supported?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  issuer?: string;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  jwks_uri?: string;
  /**
   *
   * @type {boolean}
   * @memberof OIDCDiscoveryResponse
   */
  request_parameter_supported?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  response_modes_supported?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  response_types_supported?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  revocation_endpoint?: string;
  /**
   * OAuth 2.0 Token Introspection endpoint (RFC 7662)
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  introspection_endpoint?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  revocation_endpoint_auth_methods_supported?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  scopes_supported?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  subject_types_supported?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  token_endpoint?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof OIDCDiscoveryResponse
   */
  token_endpoint_auth_methods_supported?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof OIDCDiscoveryResponse
   */
  userinfo_endpoint?: string;
}
