/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * OIDC Device Code Response
 * @export
 * @interface OIDCDeviceCodeResponse
 */
export interface OIDCDeviceCodeResponse {
  /**
   *
   * @type {string}
   * @memberof OIDCDeviceCodeResponse
   */
  device_code?: string;
  /**
   *
   * @type {number}
   * @memberof OIDCDeviceCodeResponse
   */
  expires_in?: number;
  /**
   *
   * @type {number}
   * @memberof OIDCDeviceCodeResponse
   */
  interval?: number;
  /**
   *
   * @type {string}
   * @memberof OIDCDeviceCodeResponse
   */
  user_code?: string;
  /**
   *
   * @type {string}
   * @memberof OIDCDeviceCodeResponse
   */
  verification_uri?: string;
  /**
   *
   * @type {string}
   * @memberof OIDCDeviceCodeResponse
   */
  verification_uri_complete?: string;
}
