/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationBaseDisplay } from './organization-base-display';
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationDomainRequest } from './organization-domain-request';
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsPolicyBase } from './organizations-policy-base';

/**
 *
 * @export
 * @interface OrganizationUpdateRequest
 */
export interface OrganizationUpdateRequest {
  /**
   * Name of the organization
   * @type {string}
   * @memberof OrganizationUpdateRequest
   */
  Name?: string;
  /**
   *
   * @type {OrganizationBaseDisplay}
   * @memberof OrganizationUpdateRequest
   */
  Display?: OrganizationBaseDisplay | null;
  /**
   * Additional metadata for the organization
   * @type {{ [key: string]: string; }}
   * @memberof OrganizationUpdateRequest
   */
  Metadata?: { [key: string]: string };
  /**
   *
   * @type {Array<OrganizationDomainRequest>}
   * @memberof OrganizationUpdateRequest
   */
  Domains?: Array<OrganizationDomainRequest>;
  /**
   * Restricts authentication to registered domains only
   * @type {boolean}
   * @memberof OrganizationUpdateRequest
   */
  IsAuthRestrictedToDomain?: boolean | null;
  /**
   *
   * @type {OrganizationsPolicyBase}
   * @memberof OrganizationUpdateRequest
   */
  Policies?: OrganizationsPolicyBase | null;
  /**
   * Indicates whether the organization is active or not
   * @type {boolean}
   * @memberof OrganizationUpdateRequest
   */
  IsActive?: boolean | null;
}
