/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsConnectionSamlBaseIDPCertificate } from './organizations-connection-saml-base-idpcertificate';

/**
 *
 * @export
 * @interface OrganizationsConnectionSamlBase
 */
export interface OrganizationsConnectionSamlBase {
  /**
   * Unique identifier for the Identity Provider (IdP).
   * @type {string}
   * @memberof OrganizationsConnectionSamlBase
   */
  IDPEntityId?: string;
  /**
   * URL to the IdP metadata XML file.
   * @type {string}
   * @memberof OrganizationsConnectionSamlBase
   */
  IDPMetadataUrl?: string;
  /**
   * Indicates whether the SAML connection is initiated by the IdP.
   * @type {boolean}
   * @memberof OrganizationsConnectionSamlBase
   */
  IsIDPInitiated?: boolean;
  /**
   * The IdP\'s SAML single sign-on (login) URL.
   * @type {string}
   * @memberof OrganizationsConnectionSamlBase
   */
  IDPLoginUrl?: string;
  /**
   * The IdP\'s SAML single logout (SLO) URL.
   * @type {string}
   * @memberof OrganizationsConnectionSamlBase
   */
  IDPLogoutUrl?: string;
  /**
   *
   * @type {OrganizationsConnectionSamlBaseIDPCertificate}
   * @memberof OrganizationsConnectionSamlBase
   */
  IDPCertificate?: OrganizationsConnectionSamlBaseIDPCertificate | null;
}
