/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Attribute mapping between the IdP claims and user fields.
 * @export
 * @interface OrganizationsConnectionBaseAttributes
 */
export interface OrganizationsConnectionBaseAttributes {
  /**
   * Custom attribute mapping for the connection
   * @type {{ [key: string]: string; }}
   * @memberof OrganizationsConnectionBaseAttributes
   */
  CustomMapping?: { [key: string]: string };
  /**
   * Email attribute for the connection
   * @type {string}
   * @memberof OrganizationsConnectionBaseAttributes
   */
  Email?: string;
  /**
   * First name attribute for the connection
   * @type {string}
   * @memberof OrganizationsConnectionBaseAttributes
   */
  FirstName?: string;
  /**
   * Groups attribute for the connection
   * @type {string}
   * @memberof OrganizationsConnectionBaseAttributes
   */
  Groups?: string;
  /**
   * Unique identifier attribute for the connection
   * @type {string}
   * @memberof OrganizationsConnectionBaseAttributes
   */
  ID?: string;
  /**
   * Last name attribute for the connection
   * @type {string}
   * @memberof OrganizationsConnectionBaseAttributes
   */
  LastName?: string;
}
