/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PasskeyCredentialCreationResponseClientExtensionResults } from './passkey-credential-creation-response-client-extension-results';
// May contain unused imports in some cases
// @ts-ignore
import type { PasskeyCredentialCreationResponseResponse } from './passkey-credential-creation-response-response';

/**
 * CredentialCreationResponse represents the response from a client when creating new credentials. It is the result of the navigator.credentials.create() call on the client side and is sent to the server for verification during the registration process.
 * @export
 * @interface PasskeyCredentialCreationResponse
 */
export interface PasskeyCredentialCreationResponse {
  /**
   * Base64URL-encoded string representing the ID of the newly created credential. This is typically the same as rawId, but encoded as a string.
   * @type {string}
   * @memberof PasskeyCredentialCreationResponse
   */
  id: string;
  /**
   * Base64URL-encoded ArrayBuffer containing the credential ID. This ID is used by the Relying Party to identify the credential for future authentications.
   * @type {string}
   * @memberof PasskeyCredentialCreationResponse
   */
  rawId: string;
  /**
   *
   * @type {PasskeyCredentialCreationResponseResponse}
   * @memberof PasskeyCredentialCreationResponse
   */
  response: PasskeyCredentialCreationResponseResponse;
  /**
   * String describing the credential type. For WebAuthn, this is always \"public-key\".
   * @type {string}
   * @memberof PasskeyCredentialCreationResponse
   */
  type: PasskeyCredentialCreationResponseTypeEnum;
  /**
   *
   * @type {PasskeyCredentialCreationResponseClientExtensionResults}
   * @memberof PasskeyCredentialCreationResponse
   */
  clientExtensionResults?: PasskeyCredentialCreationResponseClientExtensionResults;
  /**
   * Indicates the authenticator attachment modality used during credential creation. This helps identify the type of authenticator used, either a platform authenticator integrated into the  device or a roaming authenticator that can be connected to different devices.
   * @type {string}
   * @memberof PasskeyCredentialCreationResponse
   */
  authenticatorAttachment?: PasskeyCredentialCreationResponseAuthenticatorAttachmentEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PasskeyCredentialCreationResponseTypeEnum {
  public_key = 'public-key',
}
/**
 * @export
 * @enum {string}
 */
export enum PasskeyCredentialCreationResponseAuthenticatorAttachmentEnum {
  platform = 'platform',
  cross_platform = 'cross-platform',
}
