/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PasskeyCredentialAssertionResponse } from './passkey-credential-assertion-response';

/**
 * Response payload after a User attempts to authenticate using a Passkey
 * @export
 * @interface PasskeyLoginFinishCore
 */
export interface PasskeyLoginFinishCore {
  /**
   * The security answers
   * @type {{ [key: string]: string; }}
   * @memberof PasskeyLoginFinishCore
   */
  SecurityAnswer?: { [key: string]: string } | null;
  /**
   * Email address of the User attempting authentication
   * @type {string}
   * @memberof PasskeyLoginFinishCore
   */
  email?: string;
  /**
   *
   * @type {PasskeyCredentialAssertionResponse}
   * @memberof PasskeyLoginFinishCore
   */
  PasskeyCredential?: PasskeyCredentialAssertionResponse;
}
