/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PerfectMindSessionResponse
 */
export interface PerfectMindSessionResponse {
  /**
   * PerfectMind session identifier.
   * @type {string}
   * @memberof PerfectMindSessionResponse
   */
  SessionId?: string;
  /**
   * PerfectMind login URL with the session.
   * @type {string}
   * @memberof PerfectMindSessionResponse
   */
  URL?: string;
  /**
   * Whether a new session link was generated.
   * @type {boolean}
   * @memberof PerfectMindSessionResponse
   */
  IsNewLink?: boolean;
}
