/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PermissionPutRequest
 */
export interface PermissionPutRequest {
  /**
   * The name of the Permission. For non-B2B apps, the name cannot be modified and must match the existing permission name.
   * @type {string}
   * @memberof PermissionPutRequest
   */
  Name: string;
  /**
   * The description of the Permission
   * @type {string}
   * @memberof PermissionPutRequest
   */
  Description: string;
  /**
   * The hex ID of the Auth Server API resource to associate this permission with.
   * @type {string}
   * @memberof PermissionPutRequest
   */
  ResourceId?: string;
}
