/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PermissionsPostRequest
 */
export interface PermissionsPostRequest {
  /**
   * The name of the Permission
   * @type {string}
   * @memberof PermissionsPostRequest
   */
  Name: string;
  /**
   * The description of the Permission
   * @type {string}
   * @memberof PermissionsPostRequest
   */
  Description?: string;
  /**
   * The hex ID of the Auth Server API resource to associate this permission with.
   * @type {string}
   * @memberof PermissionsPostRequest
   */
  ResourceId?: string;
}
