/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileRequestModelVolunteerInner
 */
export interface ProfileRequestModelVolunteerInner {
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelVolunteerInner
   */
  Organization?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelVolunteerInner
   */
  Role?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelVolunteerInner
   */
  Cause?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelVolunteerInner
   */
  Id?: string;
}
