/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProfileAddressesInner } from './profile-addresses-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileAgeRange } from './profile-age-range';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileAwardsInner } from './profile-awards-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileBadgesInner } from './profile-badges-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileBooksInner } from './profile-books-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileCertificationsInner } from './profile-certifications-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileConsentProfile } from './profile-consent-profile';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileCountry } from './profile-country';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileCoursesInner } from './profile-courses-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileCurrentStatusInner } from './profile-current-status-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileEducationsInner } from './profile-educations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileEmailInner } from './profile-email-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileExternalIdsInner } from './profile-external-ids-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileFamilyInner } from './profile-family-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileFavoriteThingsInner } from './profile-favorite-things-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileGamesInner } from './profile-games-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileIMAccountsInner } from './profile-imaccounts-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileInspirationalPeopleInner } from './profile-inspirational-people-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileInterestsInner } from './profile-interests-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileJobBookmarksInner } from './profile-job-bookmarks-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileKloutScore } from './profile-klout-score';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileLanguagesInner } from './profile-languages-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileMemberUrlResourcesInner } from './profile-member-url-resources-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileMoviesInner } from './profile-movies-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileMutualFriendsInner } from './profile-mutual-friends-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileOrganizationsInner } from './profile-organizations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePIN } from './profile-pin';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePasskeyLogin } from './profile-passkey-login';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePatentsInner } from './profile-patents-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePhoneNumbersInner } from './profile-phone-numbers-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePlacesLivedInner } from './profile-places-lived-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePositionsInner } from './profile-positions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePrivacyPolicy } from './profile-privacy-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileProjectsInner } from './profile-projects-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileProviderAccessCredential } from './profile-provider-access-credential';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePublicationsInner } from './profile-publications-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileRecommendationsReceivedInner } from './profile-recommendations-received-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileRegistrationData } from './profile-registration-data';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileRelatedProfileViewsInner } from './profile-related-profile-views-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSkillsInner } from './profile-skills-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSportsInner } from './profile-sports-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSubscription } from './profile-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSuggestions } from './profile-suggestions';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileTelevisionShowInner } from './profile-television-show-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileUnverifiedEmailInner } from './profile-unverified-email-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileVolunteerInner } from './profile-volunteer-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SocialIdentity } from './social-identity';

/**
 *
 * @export
 * @interface Profile
 */
export interface Profile {
  /**
   * Indicates if the Password has been breached.
   * @type {boolean}
   * @memberof Profile
   */
  IsPasswordBreached?: boolean;
  /**
   * Indicates if the User Account is active.
   * @type {boolean}
   * @memberof Profile
   */
  IsActive?: boolean;
  /**
   * Indicates if the User Account is deleted.
   * @type {boolean}
   * @memberof Profile
   */
  IsDeleted?: boolean;
  /**
   * Indicates if the User\'s Email is verified.
   * @type {boolean}
   * @memberof Profile
   */
  EmailVerified?: boolean;
  /**
   * Indicates if the User\'s login is locked.
   * @type {boolean}
   * @memberof Profile
   */
  IsLoginLocked?: boolean;
  /**
   * Indicates if required fields have been filled at least once.
   * @type {boolean}
   * @memberof Profile
   */
  IsRequiredFieldsFilledOnce?: boolean;
  /**
   * Indicates if this is the User\'s first login.
   * @type {boolean}
   * @memberof Profile
   */
  FirstLogin?: boolean | null;
  /**
   * Indicates if the User Account is protected.
   * @type {boolean}
   * @memberof Profile
   */
  IsProtected?: boolean;
  /**
   * Indicates if the User is hireable.
   * @type {boolean}
   * @memberof Profile
   */
  Hireable?: boolean;
  /**
   * Indicates if the Password is secure.
   * @type {boolean}
   * @memberof Profile
   */
  IsSecurePassword?: boolean | null;
  /**
   * Indicates if the UID is custom.
   * @type {boolean}
   * @memberof Profile
   */
  IsCustomUid?: boolean;
  /**
   * Indicates if the Phone ID is verified.
   * @type {boolean}
   * @memberof Profile
   */
  PhoneIdVerified?: boolean;
  /**
   * Indicates if the User is subscribed to emails.
   * @type {boolean}
   * @memberof Profile
   */
  IsEmailSubscribed?: boolean;
  /**
   * Number of logins by the User.
   * @type {number}
   * @memberof Profile
   */
  NoOfLogins?: number;
  /**
   * Number of followers the User has.
   * @type {number}
   * @memberof Profile
   */
  FollowersCount?: number;
  /**
   * Number of friends the User has.
   * @type {number}
   * @memberof Profile
   */
  FriendsCount?: number;
  /**
   * Total number of statuses posted by the User.
   * @type {number}
   * @memberof Profile
   */
  TotalStatusesCount?: number;
  /**
   * Number of recommenders for the User.
   * @type {number}
   * @memberof Profile
   */
  NumRecommenders?: number;
  /**
   * Total number of private repositories.
   * @type {number}
   * @memberof Profile
   */
  TotalPrivateRepository?: number;
  /**
   * Total number of public gists.
   * @type {number}
   * @memberof Profile
   */
  PublicGists?: number;
  /**
   * Total number of private gists.
   * @type {number}
   * @memberof Profile
   */
  PrivateGists?: number;
  /**
   * Total number of PINs.
   * @type {number}
   * @memberof Profile
   */
  PinsCount?: number;
  /**
   * Total number of boards.
   * @type {number}
   * @memberof Profile
   */
  BoardsCount?: number;
  /**
   * Total number of likes.
   * @type {number}
   * @memberof Profile
   */
  LikesCount?: number;
  /**
   *
   * @type {number}
   * @memberof Profile
   */
  SessionLimit?: number;
  /**
   * Unique identifier for the User Profile.
   * @type {string}
   * @memberof Profile
   */
  ID?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  Password?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  LoginLockedType?: string;
  /**
   * Provider of the User Profile.
   * @type {string}
   * @memberof Profile
   */
  Provider?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  LastPasswordChangeToken?: string;
  /**
   * Full name of the User.
   * @type {string}
   * @memberof Profile
   */
  FullName?: string | null;
  /**
   * First name of the User.
   * @type {string}
   * @memberof Profile
   */
  FirstName?: string | null;
  /**
   * Last name of the User.
   * @type {string}
   * @memberof Profile
   */
  LastName?: string | null;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  RegistrationProvider?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  RegistrationSource?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  LastLoginLocation?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  ExternalUserLoginId?: string;
  /**
   * Phone ID of the User.
   * @type {string}
   * @memberof Profile
   */
  PhoneId?: string | null;
  /**
   * The Username of the User.
   * @type {string}
   * @memberof Profile
   */
  UserName?: string | null;
  /**
   * The prefix for the User\'s name.
   * @type {string}
   * @memberof Profile
   */
  Prefix?: string | null;
  /**
   * The middle name of the User.
   * @type {string}
   * @memberof Profile
   */
  MiddleName?: string | null;
  /**
   * The suffix for the User\'s name.
   * @type {string}
   * @memberof Profile
   */
  Suffix?: string | null;
  /**
   * The nickname of the User.
   * @type {string}
   * @memberof Profile
   */
  NickName?: string | null;
  /**
   * The profile name of the User.
   * @type {string}
   * @memberof Profile
   */
  ProfileName?: string | null;
  /**
   * The birth date of the User.
   * @type {string}
   * @memberof Profile
   */
  BirthDate?: string | null;
  /**
   * The gender of the User.
   * @type {string}
   * @memberof Profile
   */
  Gender?: string | null;
  /**
   * The website of the User.
   * @type {string}
   * @memberof Profile
   */
  Website?: string | null;
  /**
   * The URL of the User\'s thumbnail image.
   * @type {string}
   * @memberof Profile
   */
  ThumbnailImageUrl?: string | null;
  /**
   * The URL of the User\'s profile image.
   * @type {string}
   * @memberof Profile
   */
  ImageUrl?: string | null;
  /**
   * The URL of the User\'s favicon.
   * @type {string}
   * @memberof Profile
   */
  Favicon?: string | null;
  /**
   * The URL of the User\'s profile.
   * @type {string}
   * @memberof Profile
   */
  ProfileUrl?: string | null;
  /**
   * The hometown of the User.
   * @type {string}
   * @memberof Profile
   */
  HomeTown?: string | null;
  /**
   * The state of the User.
   * @type {string}
   * @memberof Profile
   */
  State?: string | null;
  /**
   * The city of the User.
   * @type {string}
   * @memberof Profile
   */
  City?: string | null;
  /**
   * The industry of the User.
   * @type {string}
   * @memberof Profile
   */
  Industry?: string | null;
  /**
   * A brief description about the User.
   * @type {string}
   * @memberof Profile
   */
  About?: string | null;
  /**
   * The time zone of the User.
   * @type {string}
   * @memberof Profile
   */
  TimeZone?: string | null;
  /**
   * The local language of the User.
   * @type {string}
   * @memberof Profile
   */
  LocalLanguage?: string | null;
  /**
   * The URL of the User\'s cover photo.
   * @type {string}
   * @memberof Profile
   */
  CoverPhoto?: string | null;
  /**
   * The tagline of the User.
   * @type {string}
   * @memberof Profile
   */
  TagLine?: string | null;
  /**
   * The language of the User.
   * @type {string}
   * @memberof Profile
   */
  Language?: string | null;
  /**
   * Indicates if the User is verified.
   * @type {string}
   * @memberof Profile
   */
  Verified?: string | null;
  /**
   * The last updated time of the User\'s profile.
   * @type {string}
   * @memberof Profile
   */
  UpdatedTime?: string | null;
  /**
   * Indicates if geolocation is enabled for the User.
   * @type {string}
   * @memberof Profile
   */
  IsGeoEnabled?: string | null;
  /**
   * The associations of the User.
   * @type {string}
   * @memberof Profile
   */
  Associations?: string | null;
  /**
   * The honors received by the User.
   * @type {string}
   * @memberof Profile
   */
  Honors?: string | null;
  /**
   * The HTTPS URL of the User\'s profile image.
   * @type {string}
   * @memberof Profile
   */
  HttpsImageUrl?: string | null;
  /**
   * The main address of the User.
   * @type {string}
   * @memberof Profile
   */
  MainAddress?: string | null;
  /**
   * The creation date of the User\'s account.
   * @type {string}
   * @memberof Profile
   */
  Created?: string | null;
  /**
   * The local city of the User.
   * @type {string}
   * @memberof Profile
   */
  LocalCity?: string | null;
  /**
   * The profile city of the User.
   * @type {string}
   * @memberof Profile
   */
  ProfileCity?: string | null;
  /**
   * The local country of the User.
   * @type {string}
   * @memberof Profile
   */
  LocalCountry?: string | null;
  /**
   * The profile country of the User.
   * @type {string}
   * @memberof Profile
   */
  ProfileCountry?: string | null;
  /**
   * The relationship status of the User.
   * @type {string}
   * @memberof Profile
   */
  RelationshipStatus?: string | null;
  /**
   * The quota assigned to the User.
   * @type {string}
   * @memberof Profile
   */
  Quota?: string | null;
  /**
   * A quote associated with the User.
   * @type {string}
   * @memberof Profile
   */
  Quote?: string | null;
  /**
   * The religion of the User.
   * @type {string}
   * @memberof Profile
   */
  Religion?: string | null;
  /**
   * The political views of the User.
   * @type {string}
   * @memberof Profile
   */
  Political?: string | null;
  /**
   * The number of public repositories owned by the User.
   * @type {string}
   * @memberof Profile
   */
  PublicRepository?: string | null;
  /**
   * The URL of the User\'s repository.
   * @type {string}
   * @memberof Profile
   */
  RepositoryUrl?: string | null;
  /**
   * The age of the User.
   * @type {string}
   * @memberof Profile
   */
  Age?: string | null;
  /**
   * The professional headline of the User.
   * @type {string}
   * @memberof Profile
   */
  ProfessionalHeadline?: string | null;
  /**
   * The LoginRadius User ID.
   * @type {string}
   * @memberof Profile
   */
  LRUserID?: string | null;
  /**
   * The preferred currency of the User.
   * @type {string}
   * @memberof Profile
   */
  Currency?: string | null;
  /**
   * The URL of the User\'s starred items.
   * @type {string}
   * @memberof Profile
   */
  StarredUrl?: string | null;
  /**
   * The URL of the User\'s gists.
   * @type {string}
   * @memberof Profile
   */
  GistsUrl?: string | null;
  /**
   * The company the User is associated with.
   * @type {string}
   * @memberof Profile
   */
  Company?: string | null;
  /**
   * The URL of the User\'s Gravatar image.
   * @type {string}
   * @memberof Profile
   */
  GravatarImageUrl?: string | null;
  /**
   * The date of the last Password change.
   * @type {string}
   * @memberof Profile
   */
  LastPasswordChangeDate?: string | null;
  /**
   * The expiration date of the Password.
   * @type {string}
   * @memberof Profile
   */
  PasswordExpirationDate?: string | null;
  /**
   * The date the Account was created.
   * @type {string}
   * @memberof Profile
   */
  CreatedDate?: string;
  /**
   * The date the Account was last modified.
   * @type {string}
   * @memberof Profile
   */
  ModifiedDate?: string;
  /**
   * The date the Profile was last modified.
   * @type {string}
   * @memberof Profile
   */
  ProfileModifiedDate?: string | null;
  /**
   * The date of the last login.
   * @type {string}
   * @memberof Profile
   */
  LastLoginDate?: string | null;
  /**
   * The date the User signed up.
   * @type {string}
   * @memberof Profile
   */
  SignupDate?: string;
  /**
   *
   * @type {ProfilePrivacyPolicy}
   * @memberof Profile
   */
  PrivacyPolicy?: ProfilePrivacyPolicy | null;
  /**
   *
   * @type {ProfileCountry}
   * @memberof Profile
   */
  Country?: ProfileCountry | null;
  /**
   *
   * @type {ProfileAgeRange}
   * @memberof Profile
   */
  AgeRange?: ProfileAgeRange | null;
  /**
   *
   * @type {ProfileKloutScore}
   * @memberof Profile
   */
  KloutScore?: ProfileKloutScore | null;
  /**
   *
   * @type {ProfileSuggestions}
   * @memberof Profile
   */
  Suggestions?: ProfileSuggestions | null;
  /**
   *
   * @type {ProfileSubscription}
   * @memberof Profile
   */
  Subscription?: ProfileSubscription | null;
  /**
   *
   * @type {ProfilePIN}
   * @memberof Profile
   */
  PIN?: ProfilePIN | null;
  /**
   *
   * @type {ProfileConsentProfile}
   * @memberof Profile
   */
  ConsentProfile?: ProfileConsentProfile | null;
  /**
   *
   * @type {ProfileRegistrationData}
   * @memberof Profile
   */
  RegistrationData?: ProfileRegistrationData | null;
  /**
   *
   * @type {ProfileProviderAccessCredential}
   * @memberof Profile
   */
  ProviderAccessCredential?: ProfileProviderAccessCredential | null;
  /**
   * Custom fields associated with the User.
   * @type {{ [key: string]: string; }}
   * @memberof Profile
   */
  CustomFields?: { [key: string]: string } | null;
  /**
   * URLs of the User\'s profile images.
   * @type {{ [key: string]: string; }}
   * @memberof Profile
   */
  ProfileImageUrls?: { [key: string]: string } | null;
  /**
   * The User\'s web profiles.
   * @type {{ [key: string]: string; }}
   * @memberof Profile
   */
  WebProfiles?: { [key: string]: string } | null;
  /**
   * Roles assigned to the User.
   * @type {Array<string>}
   * @memberof Profile
   */
  Roles?: Array<string> | null;
  /**
   * the unique id which belongs to the Account
   * @type {string}
   * @memberof Profile
   */
  Uid?: string;
  /**
   * Previous UIDs associated with the Account.
   * @type {Array<string>}
   * @memberof Profile
   */
  PreviousUids?: Array<string> | null;
  /**
   * Interests of the User.
   * @type {Array<string>}
   * @memberof Profile
   */
  InterestedIn?: Array<string> | null;
  /**
   *
   * @type {Array<ProfileExternalIdsInner>}
   * @memberof Profile
   */
  ExternalIds?: Array<ProfileExternalIdsInner> | null;
  /**
   *
   * @type {Array<ProfileUnverifiedEmailInner>}
   * @memberof Profile
   */
  UnverifiedEmail?: Array<ProfileUnverifiedEmailInner> | null;
  /**
   * List of positions held by the User.
   * @type {Array<ProfilePositionsInner>}
   * @memberof Profile
   */
  Positions?: Array<ProfilePositionsInner> | null;
  /**
   * List of educational qualifications of the User.
   * @type {Array<ProfileEducationsInner>}
   * @memberof Profile
   */
  Educations?: Array<ProfileEducationsInner> | null;
  /**
   * List of Phone numbers associated with the User.
   * @type {Array<ProfilePhoneNumbersInner>}
   * @memberof Profile
   */
  PhoneNumbers?: Array<ProfilePhoneNumbersInner> | null;
  /**
   * List of instant messaging accounts associated with the User.
   * @type {Array<ProfileIMAccountsInner>}
   * @memberof Profile
   */
  IMAccounts?: Array<ProfileIMAccountsInner> | null;
  /**
   * List of addresses associated with the User.
   * @type {Array<ProfileAddressesInner>}
   * @memberof Profile
   */
  Addresses?: Array<ProfileAddressesInner> | null;
  /**
   * List of interests of the User.
   * @type {Array<ProfileInterestsInner>}
   * @memberof Profile
   */
  Interests?: Array<ProfileInterestsInner> | null;
  /**
   * List of sports the User is interested in.
   * @type {Array<ProfileSportsInner>}
   * @memberof Profile
   */
  Sports?: Array<ProfileSportsInner> | null;
  /**
   * List of inspirational people for the User.
   * @type {Array<ProfileInspirationalPeopleInner>}
   * @memberof Profile
   */
  InspirationalPeople?: Array<ProfileInspirationalPeopleInner> | null;
  /**
   * List of awards received by the User.
   * @type {Array<ProfileAwardsInner>}
   * @memberof Profile
   */
  Awards?: Array<ProfileAwardsInner> | null;
  /**
   * List of skills possessed by the User.
   * @type {Array<ProfileSkillsInner>}
   * @memberof Profile
   */
  Skills?: Array<ProfileSkillsInner> | null;
  /**
   * List of current statuses of the User.
   * @type {Array<ProfileCurrentStatusInner>}
   * @memberof Profile
   */
  CurrentStatus?: Array<ProfileCurrentStatusInner> | null;
  /**
   * List of certifications obtained by the User.
   * @type {Array<ProfileCertificationsInner>}
   * @memberof Profile
   */
  Certifications?: Array<ProfileCertificationsInner> | null;
  /**
   * List of courses completed by the User.
   * @type {Array<ProfileCoursesInner>}
   * @memberof Profile
   */
  Courses?: Array<ProfileCoursesInner> | null;
  /**
   * List of volunteer activities by the User.
   * @type {Array<ProfileVolunteerInner>}
   * @memberof Profile
   */
  Volunteer?: Array<ProfileVolunteerInner> | null;
  /**
   * List of recommendations received by the User.
   * @type {Array<ProfileRecommendationsReceivedInner>}
   * @memberof Profile
   */
  RecommendationsReceived?: Array<ProfileRecommendationsReceivedInner> | null;
  /**
   * List of languages known by the User.
   * @type {Array<ProfileLanguagesInner>}
   * @memberof Profile
   */
  Languages?: Array<ProfileLanguagesInner> | null;
  /**
   * List of projects undertaken by the User.
   * @type {Array<ProfileProjectsInner>}
   * @memberof Profile
   */
  Projects?: Array<ProfileProjectsInner> | null;
  /**
   * List of games the User is interested in.
   * @type {Array<ProfileGamesInner>}
   * @memberof Profile
   */
  Games?: Array<ProfileGamesInner> | null;
  /**
   * List of family members of the User.
   * @type {Array<ProfileFamilyInner>}
   * @memberof Profile
   */
  Family?: Array<ProfileFamilyInner> | null;
  /**
   * List of television shows the User is interested in.
   * @type {Array<ProfileTelevisionShowInner>}
   * @memberof Profile
   */
  TelevisionShow?: Array<ProfileTelevisionShowInner> | null;
  /**
   * List of mutual friends of the User.
   * @type {Array<ProfileMutualFriendsInner>}
   * @memberof Profile
   */
  MutualFriends?: Array<ProfileMutualFriendsInner> | null;
  /**
   * List of movies the User is interested in.
   * @type {Array<ProfileMoviesInner>}
   * @memberof Profile
   */
  Movies?: Array<ProfileMoviesInner> | null;
  /**
   * List of books the User is interested in.
   * @type {Array<ProfileBooksInner>}
   * @memberof Profile
   */
  Books?: Array<ProfileBooksInner> | null;
  /**
   * List of patents owned by the User.
   * @type {Array<ProfilePatentsInner>}
   * @memberof Profile
   */
  Patents?: Array<ProfilePatentsInner> | null;
  /**
   * List of favorite things of the User.
   * @type {Array<ProfileFavoriteThingsInner>}
   * @memberof Profile
   */
  FavoriteThings?: Array<ProfileFavoriteThingsInner> | null;
  /**
   * List of related profile views of the User.
   * @type {Array<ProfileRelatedProfileViewsInner>}
   * @memberof Profile
   */
  RelatedProfileViews?: Array<ProfileRelatedProfileViewsInner> | null;
  /**
   * List of places the User has lived.
   * @type {Array<ProfilePlacesLivedInner>}
   * @memberof Profile
   */
  PlacesLived?: Array<ProfilePlacesLivedInner> | null;
  /**
   * List of publications by the User.
   * @type {Array<ProfilePublicationsInner>}
   * @memberof Profile
   */
  Publications?: Array<ProfilePublicationsInner> | null;
  /**
   * List of job bookmarks by the User.
   * @type {Array<ProfileJobBookmarksInner>}
   * @memberof Profile
   */
  JobBookmarks?: Array<ProfileJobBookmarksInner> | null;
  /**
   * List of badges earned by the User.
   * @type {Array<ProfileBadgesInner>}
   * @memberof Profile
   */
  Badges?: Array<ProfileBadgesInner> | null;
  /**
   * List of member URL resources.
   * @type {Array<ProfileMemberUrlResourcesInner>}
   * @memberof Profile
   */
  MemberUrlResources?: Array<ProfileMemberUrlResourcesInner> | null;
  /**
   * List of organizations associated with the User.
   * @type {Array<ProfileOrganizationsInner>}
   * @memberof Profile
   */
  Organizations?: Array<ProfileOrganizationsInner> | null;
  /**
   * List of Email addresses associated with the User.
   * @type {Array<ProfileEmailInner>}
   * @memberof Profile
   */
  Email?: Array<ProfileEmailInner> | null;
  /**
   *
   * @type {ProfilePasskeyLogin}
   * @memberof Profile
   */
  PasskeyLogin?: ProfilePasskeyLogin | null;
  /**
   *
   * @type {Array<SocialIdentity>}
   * @memberof Profile
   */
  Identities?: Array<SocialIdentity> | null;
}
