/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProfilePublicationsInnerAuthorsInner } from './profile-publications-inner-authors-inner';

/**
 *
 * @export
 * @interface ProfilePublicationsInner
 */
export interface ProfilePublicationsInner {
  /**
   * The title of the publication.
   * @type {string}
   * @memberof ProfilePublicationsInner
   */
  Title?: string;
  /**
   * The publisher of the publication.
   * @type {string}
   * @memberof ProfilePublicationsInner
   */
  Publisher?: string;
  /**
   * The date the publication was released.
   * @type {string}
   * @memberof ProfilePublicationsInner
   */
  Date?: string;
  /**
   * The ID of the publication.
   * @type {string}
   * @memberof ProfilePublicationsInner
   */
  Id?: string;
  /**
   * The URL of the publication.
   * @type {string}
   * @memberof ProfilePublicationsInner
   */
  Url?: string;
  /**
   * A summary of the publication.
   * @type {string}
   * @memberof ProfilePublicationsInner
   */
  Summary?: string;
  /**
   *
   * @type {Array<ProfilePublicationsInnerAuthorsInner>}
   * @memberof ProfilePublicationsInner
   */
  Authors?: Array<ProfilePublicationsInnerAuthorsInner> | null;
}
