/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileWithoutIdentitiesEducationsInner
 */
export interface ProfileWithoutIdentitiesEducationsInner {
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  School?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  Year?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  Type?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  Notes?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  Activities?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  Degree?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  FieldOfStudy?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  StartDate?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileWithoutIdentitiesEducationsInner
   */
  EndDate?: string;
}
