/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileBadgesInner
 */
export interface ProfileBadgesInner {
  /**
   * The ID of the badge.
   * @type {string}
   * @memberof ProfileBadgesInner
   */
  BadgeId?: string;
  /**
   * The name of the badge.
   * @type {string}
   * @memberof ProfileBadgesInner
   */
  Name?: string;
  /**
   * The message associated with the badge.
   * @type {string}
   * @memberof ProfileBadgesInner
   */
  BadgeMessage?: string;
  /**
   * A description of the badge.
   * @type {string}
   * @memberof ProfileBadgesInner
   */
  Description?: string;
  /**
   * The URL of the badge image.
   * @type {string}
   * @memberof ProfileBadgesInner
   */
  ImageUrl?: string;
}
