/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileEmailInner
 */
export interface ProfileEmailInner {
  /**
   * The type of the Email (e.g., Primary, Secondary).
   * @type {string}
   * @memberof ProfileEmailInner
   */
  Type?: string;
  /**
   * The Email address.
   * @type {string}
   * @memberof ProfileEmailInner
   */
  Value?: string;
}
