/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfilePIN
 */
export interface ProfilePIN {
  /**
   * Indicates if the PIN setup was skipped.
   * @type {boolean}
   * @memberof ProfilePIN
   */
  Skipped?: boolean;
  /**
   * The PIN value.
   * @type {string}
   * @memberof ProfilePIN
   */
  PIN?: string;
  /**
   * The token for the last PIN change.
   * @type {string}
   * @memberof ProfilePIN
   */
  LastPINChangeToken?: string | null;
  /**
   * The date of the last PIN change.
   * @type {string}
   * @memberof ProfilePIN
   */
  LastPINChangeDate?: string | null;
  /**
   * The date the PIN setup was skipped.
   * @type {string}
   * @memberof ProfilePIN
   */
  SkippedDate?: string | null;
}
