/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSuggestionsCompaniesToFollowInner } from './profile-suggestions-companies-to-follow-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSuggestionsIndustriesToFollowInner } from './profile-suggestions-industries-to-follow-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSuggestionsNewssourceToFollowInner } from './profile-suggestions-newssource-to-follow-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSuggestionsPeopleToFollowInner } from './profile-suggestions-people-to-follow-inner';

/**
 *
 * @export
 * @interface ProfileSuggestions
 */
export interface ProfileSuggestions {
  /**
   * List of companies suggested to follow.
   * @type {Array<ProfileSuggestionsCompaniesToFollowInner>}
   * @memberof ProfileSuggestions
   */
  CompaniesToFollow?: Array<ProfileSuggestionsCompaniesToFollowInner>;
  /**
   * List of industries suggested to follow.
   * @type {Array<ProfileSuggestionsIndustriesToFollowInner>}
   * @memberof ProfileSuggestions
   */
  IndustriesToFollow?: Array<ProfileSuggestionsIndustriesToFollowInner>;
  /**
   * List of news sources suggested to follow.
   * @type {Array<ProfileSuggestionsNewssourceToFollowInner>}
   * @memberof ProfileSuggestions
   */
  NewssourceToFollow?: Array<ProfileSuggestionsNewssourceToFollowInner>;
  /**
   * List of people suggested to follow.
   * @type {Array<ProfileSuggestionsPeopleToFollowInner>}
   * @memberof ProfileSuggestions
   */
  PeopleToFollow?: Array<ProfileSuggestionsPeopleToFollowInner>;
}
