/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfilePatentsInner
 */
export interface ProfilePatentsInner {
  /**
   * The ID of the patent.
   * @type {string}
   * @memberof ProfilePatentsInner
   */
  Id?: string;
  /**
   * The title of the patent.
   * @type {string}
   * @memberof ProfilePatentsInner
   */
  Title?: string;
  /**
   * The date the patent was filed.
   * @type {string}
   * @memberof ProfilePatentsInner
   */
  Date?: string;
}
