/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileRequestModelBadgesInner
 */
export interface ProfileRequestModelBadgesInner {
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  BadgeId?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  BageId?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  Name?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  BadgeMessage?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  BageMessage?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  Description?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileRequestModelBadgesInner
   */
  ImageUrl?: string;
}
