/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProfileJobBookmarksInnerJob
 */
export interface ProfileJobBookmarksInnerJob {
  /**
   * Indicates if the job is active.
   * @type {boolean}
   * @memberof ProfileJobBookmarksInnerJob
   */
  Active?: boolean;
  /**
   * The ID of the job.
   * @type {string}
   * @memberof ProfileJobBookmarksInnerJob
   */
  Id?: string;
  /**
   * A snippet of the job description.
   * @type {string}
   * @memberof ProfileJobBookmarksInnerJob
   */
  DescriptionSnippet?: string;
  /**
   * The timestamp of the job posting.
   * @type {string}
   * @memberof ProfileJobBookmarksInnerJob
   */
  PostingTimestamp?: string;
}
