/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PublicKeyCredentialRequestOptionsAllowCredentialsInner } from './public-key-credential-request-options-allow-credentials-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PublicKeyCredentialRequestOptionsExtensions } from './public-key-credential-request-options-extensions';

/**
 * Represents the options for a WebAuthn credential assertion (authentication). This object is typically generated by the server and sent to the client to initiate the authentication ceremony using `navigator.credentials.get()`.
 * @export
 * @interface PublicKeyCredentialRequestOptions
 */
export interface PublicKeyCredentialRequestOptions {
  /**
   * A cryptographic challenge that the authenticator signs over. This is a base64url-encoded string generated by the server to prevent replay attacks.
   * @type {string}
   * @memberof PublicKeyCredentialRequestOptions
   */
  challenge: string;
  /**
   * The relying party identifier (usually the domain of the website) that the credential should be scoped to.
   * @type {string}
   * @memberof PublicKeyCredentialRequestOptions
   */
  rpId: string;
  /**
   * A list of descriptors for credentials acceptable to the server. This allows the server to guide the client to use a particular credential.
   * @type {Array<PublicKeyCredentialRequestOptionsAllowCredentialsInner>}
   * @memberof PublicKeyCredentialRequestOptions
   */
  allowCredentials: Array<PublicKeyCredentialRequestOptionsAllowCredentialsInner>;
  /**
   * Time, in milliseconds, that the caller is willing to wait for the authentication operation to complete.
   * @type {number}
   * @memberof PublicKeyCredentialRequestOptions
   */
  timeout: number;
  /**
   * Specifies the preferred level of User verification for the authentication. Options are \"required\", \"preferred\", or \"discouraged\".
   * @type {string}
   * @memberof PublicKeyCredentialRequestOptions
   */
  userVerification?: PublicKeyCredentialRequestOptionsUserVerificationEnum;
  /**
   *
   * @type {PublicKeyCredentialRequestOptionsExtensions}
   * @memberof PublicKeyCredentialRequestOptions
   */
  extensions?: PublicKeyCredentialRequestOptionsExtensions;
}

/**
 * @export
 * @enum {string}
 */
export enum PublicKeyCredentialRequestOptionsUserVerificationEnum {
  required = 'required',
  preferred = 'preferred',
  discouraged = 'discouraged',
}
