/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RaasOptions } from './raas-options';

/**
 *
 * @export
 * @interface RaasConfig
 */
export interface RaasConfig {
  /**
   * The type of the configuration.
   * @type {string}
   * @memberof RaasConfig
   */
  Type: string | null;
  /**
   * The name of the configuration.
   * @type {string}
   * @memberof RaasConfig
   */
  Name: string | null;
  /**
   * The display name of the configuration.
   * @type {string}
   * @memberof RaasConfig
   */
  Display?: string | null;
  /**
   * The rules associated with the configuration.
   * @type {string}
   * @memberof RaasConfig
   */
  Rules?: string | null;
  /**
   * The permission level required for the configuration.
   * @type {string}
   * @memberof RaasConfig
   */
  Permission?: string | null;
  /**
   * The options available for the configuration.
   * @type {Array<RaasOptions>}
   * @memberof RaasConfig
   */
  Options?: Array<RaasOptions>;
  /**
   * Indicates if the configuration is checked.
   * @type {boolean}
   * @memberof RaasConfig
   */
  Checked?: boolean | null;
}
