/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResetPasswordBySecurityAnswer
 */
export interface ResetPasswordBySecurityAnswer {
  /**
   * A map of question IDs or keys to answers
   * @type {{ [key: string]: string; }}
   * @memberof ResetPasswordBySecurityAnswer
   */
  SecurityAnswer: { [key: string]: string };
  /**
   * Optional Email template to use for Password reset
   * @type {string}
   * @memberof ResetPasswordBySecurityAnswer
   */
  ResetPasswordEmailTemplate?: string;
  /**
   * New Password to set
   * @type {string}
   * @memberof ResetPasswordBySecurityAnswer
   */
  password: string;
  /**
   * User\'s Phone number
   * @type {string}
   * @memberof ResetPasswordBySecurityAnswer
   */
  Phone?: string;
  /**
   * User\'s Email address
   * @type {string}
   * @memberof ResetPasswordBySecurityAnswer
   */
  Email?: string;
  /**
   * Optional username
   * @type {string}
   * @memberof ResetPasswordBySecurityAnswer
   */
  UserName?: string;
  /**
   * Optional User ID
   * @type {string}
   * @memberof ResetPasswordBySecurityAnswer
   */
  userid?: string;
}
