/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResetPasswordByEmailOtpCore
 */
export interface ResetPasswordByEmailOtpCore {
  /**
   * One-time passcode sent to the User\'s Email.
   * @type {string}
   * @memberof ResetPasswordByEmailOtpCore
   */
  otp: string;
  /**
   * User\'s Email address.
   * @type {string}
   * @memberof ResetPasswordByEmailOtpCore
   */
  email: string;
  /**
   * The new Password for the Account.
   * @type {string}
   * @memberof ResetPasswordByEmailOtpCore
   */
  Password: string;
  /**
   * Optional welcome Email template.
   * @type {string}
   * @memberof ResetPasswordByEmailOtpCore
   */
  welcomeemailtemplate?: string;
  /**
   * Optional reset Password Email template.
   * @type {string}
   * @memberof ResetPasswordByEmailOtpCore
   */
  ResetPasswordEmailTemplate?: string;
  /**
   * A map of security question keys and their corresponding answers.
   * @type {{ [key: string]: string; }}
   * @memberof ResetPasswordByEmailOtpCore
   */
  SecurityAnswer?: { [key: string]: string } | null;
}
