/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Reset Password by Phone and otp
 * @export
 * @interface ResetPasswordWithOTPCore
 */
export interface ResetPasswordWithOTPCore {
  /**
   * Email template for Password reset (optional)
   * @type {string}
   * @memberof ResetPasswordWithOTPCore
   */
  resetpasswordemailtemplate?: string;
  /**
   * SMS template for Password reset (optional)
   * @type {string}
   * @memberof ResetPasswordWithOTPCore
   */
  resetPasswordSmsTemplate?: string;
  /**
   * SMS template (optional)
   * @type {string}
   * @memberof ResetPasswordWithOTPCore
   */
  smstemplate?: string;
  /**
   * Map of security question answers
   * @type {{ [key: string]: string; }}
   * @memberof ResetPasswordWithOTPCore
   */
  SecurityAnswer?: { [key: string]: string };
  /**
   * New password
   * @type {string}
   * @memberof ResetPasswordWithOTPCore
   */
  Password: string;
  /**
   * One-Time Password received via SMS/email
   * @type {string}
   * @memberof ResetPasswordWithOTPCore
   */
  otp: string;
  /**
   * Phone number for OTP delivery
   * @type {string}
   * @memberof ResetPasswordWithOTPCore
   */
  phone: string;
}
