/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResetPINByOTP
 */
export interface ResetPINByOTP {
  /**
   * One-Time Password received by the User for verification.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  otp: string;
  /**
   * New PIN to be set by the User.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  pin: string;
  /**
   * Phone number associated with the User\'s account.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  phone?: string;
  /**
   * Username of the User.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  username?: string;
  /**
   * Email address associated with the User\'s account.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  email?: string;
  /**
   * Google reCAPTCHA response.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  'g-recaptcha-response'?: string | null;
  /**
   * QQ captcha ticket.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  qq_captcha_ticket?: string | null;
  /**
   * QQ captcha random string.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  qq_captcha_randstr?: string | null;
  /**
   * hCaptcha response.
   * @type {string}
   * @memberof ResetPINByOTP
   */
  'h-captcha-response'?: string | null;
}
