/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SamlConnectionRequestCore
 */
export interface SamlConnectionRequestCore {
  /**
   * Type of the connection, which is SAML in this case.
   * @type {string}
   * @memberof SamlConnectionRequestCore
   */
  ConnectionType?: SamlConnectionRequestCoreConnectionTypeEnum;
  /**
   * PEM-encoded IdP signing certificate used to verify SAML assertions.
   * @type {string}
   * @memberof SamlConnectionRequestCore
   */
  IDPCertificate?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum SamlConnectionRequestCoreConnectionTypeEnum {
  custom = 'saml_custom',
  okta = 'saml_okta',
  entraid = 'saml_entraid',
  google_workspace = 'saml_google_workspace',
  salesforce = 'saml_salesforce',
}
