/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsConnectionSamlBase } from './organizations-connection-saml-base';
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationsConnectionSamlBaseIDPCertificate } from './organizations-connection-saml-base-idpcertificate';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlConnectionResponseCore } from './saml-connection-response-core';
// May contain unused imports in some cases
// @ts-ignore
import type { SamlConnectionResponseCoreSPCertificate } from './saml-connection-response-core-spcertificate';

/**
 * @type SamlConnectionResponse
 * @export
 */
export type SamlConnectionResponse = OrganizationsConnectionSamlBase & SamlConnectionResponseCore;
