/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Structure of the request body for set or change username
 * @export
 * @interface SetUserNameRequest
 */
export interface SetUserNameRequest {
  /**
   * The Username to change of the User
   * @type {string}
   * @memberof SetUserNameRequest
   */
  username: string;
}
