/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SocialIdentityAddressesInner
 */
export interface SocialIdentityAddressesInner {
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  Type?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  AddressType?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  Address1?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  Address2?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  City?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  State?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  PostalCode?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  Region?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  Op?: string;
  /**
   *
   * @type {string}
   * @memberof SocialIdentityAddressesInner
   */
  Country?: string;
}
