/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The technologies provided by LR
 * @export
 * @enum {string}
 */

export enum Technology {
  android = 'android',
  ios = 'ios',
  phonegap = 'phonegap',
  ionic = 'ionic',
  xamarin = 'xamarin',
  reactnative = 'reactnative',
}
