/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TwoFAAuthBySecQuesAuthModelSecurityquestionanswerInner
 */
export interface TwoFAAuthBySecQuesAuthModelSecurityquestionanswerInner {
  /**
   * ID of the security question (required, not blank)
   * @type {string}
   * @memberof TwoFAAuthBySecQuesAuthModelSecurityquestionanswerInner
   */
  QuestionId: string;
  /**
   * Answer to the security question (required, not blank)
   * @type {string}
   * @memberof TwoFAAuthBySecQuesAuthModelSecurityquestionanswerInner
   */
  Answer: string;
}
