/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateWorkflowConfig
 */
export interface UpdateWorkflowConfig {
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowConfig
   */
  Name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowConfig
   */
  ThemeName?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowConfig
   */
  Description?: string;
  /**
   *
   * @type {object}
   * @memberof UpdateWorkflowConfig
   */
  Data?: object;
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowConfig
   */
  State?: UpdateWorkflowConfigStateEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateWorkflowConfigStateEnum {
  ACTIVE = 'ACTIVE',
  DEBUG = 'DEBUG',
  ARCHIVE = 'ARCHIVE',
}
