/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RoleContextBodyModel } from './role-context-body-model';

/**
 *
 * @export
 * @interface UpdateRoleContextBodyModel
 */
export interface UpdateRoleContextBodyModel {
  /**
   * List of Role Context objects.
   * @type {Array<RoleContextBodyModel>}
   * @memberof UpdateRoleContextBodyModel
   */
  rolecontext: Array<RoleContextBodyModel>;
}
