/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExtendUserProfileWithCustomObject } from './extend-user-profile-with-custom-object';

/**
 *
 * @export
 * @interface UserProfileScrollResponseWithCustomObject
 */
export interface UserProfileScrollResponseWithCustomObject {
  /**
   * Total number of User profiles matching the query.
   * @type {number}
   * @memberof UserProfileScrollResponseWithCustomObject
   */
  total?: number;
  /**
   * List of User profiles.
   * @type {Array<ExtendUserProfileWithCustomObject>}
   * @memberof UserProfileScrollResponseWithCustomObject
   */
  data?: Array<ExtendUserProfileWithCustomObject>;
  /**
   * Scroll or pagination token for fetching the next set of results.
   * @type {string}
   * @memberof UserProfileScrollResponseWithCustomObject
   */
  next?: string;
}
