/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileAddresses } from './user-profile-addresses';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileAgeRange } from './user-profile-age-range';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileAwards } from './user-profile-awards';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileBadges } from './user-profile-badges';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileBooks } from './user-profile-books';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCertifications } from './user-profile-certifications';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCountry } from './user-profile-country';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCourses } from './user-profile-courses';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCoverPhoto } from './user-profile-cover-photo';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCurrentStatus } from './user-profile-current-status';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCustomFields } from './user-profile-custom-fields';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileEducations } from './user-profile-educations';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileEmail } from './user-profile-email';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileExternalIds } from './user-profile-external-ids';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileFamily } from './user-profile-family';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileFavicon } from './user-profile-favicon';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileFavoriteThings } from './user-profile-favorite-things';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileGames } from './user-profile-games';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileGistsUrl } from './user-profile-gists-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileGravatarImageUrl } from './user-profile-gravatar-image-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileHttpsImageUrl } from './user-profile-https-image-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileIMAccounts } from './user-profile-imaccounts';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileImageUrl } from './user-profile-image-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileInspirationalPeople } from './user-profile-inspirational-people';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileInterests } from './user-profile-interests';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileJobBookmarks } from './user-profile-job-bookmarks';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileKloutScore } from './user-profile-klout-score';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileKnownLoginVariables } from './user-profile-known-login-variables';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileLanguages } from './user-profile-languages';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileMemberUrlResources } from './user-profile-member-url-resources';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileMovies } from './user-profile-movies';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileMutualFriends } from './user-profile-mutual-friends';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePatents } from './user-profile-patents';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePhoneNumbers } from './user-profile-phone-numbers';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePlacesLived } from './user-profile-places-lived';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePositions } from './user-profile-positions';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePrivacyPolicy } from './user-profile-privacy-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileProfileImageUrls } from './user-profile-profile-image-urls';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileProfileUrl } from './user-profile-profile-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileProjects } from './user-profile-projects';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePublicRepository } from './user-profile-public-repository';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfilePublications } from './user-profile-publications';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileRecommendationsReceived } from './user-profile-recommendations-received';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileRelatedProfileViews } from './user-profile-related-profile-views';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileRepositoryUrl } from './user-profile-repository-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileRoleContext } from './user-profile-role-context';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileSignupLog } from './user-profile-signup-log';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileSkills } from './user-profile-skills';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileSports } from './user-profile-sports';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileStarredUrl } from './user-profile-starred-url';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileSubscription } from './user-profile-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileSuggestions } from './user-profile-suggestions';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileTeleVisionShow } from './user-profile-tele-vision-show';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileUnverifiedEmail } from './user-profile-unverified-email';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileUserAgent } from './user-profile-user-agent';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileVolunteer } from './user-profile-volunteer';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileWebProfiles } from './user-profile-web-profiles';

/**
 *
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
  /**
   * Application name.
   * @type {string}
   * @memberof UserProfile
   */
  AppName?: string;
  /**
   * Unique User identifier.
   * @type {string}
   * @memberof UserProfile
   */
  Uid?: string;
  /**
   * Internal User ID.
   * @type {string}
   * @memberof UserProfile
   */
  ID?: string | null;
  /**
   * Authentication provider.
   * @type {string}
   * @memberof UserProfile
   */
  Provider?: string | null;
  /**
   * Name prefix.
   * @type {string}
   * @memberof UserProfile
   */
  Prefix?: string | null;
  /**
   * User\'s first name.
   * @type {string}
   * @memberof UserProfile
   */
  FirstName?: string | null;
  /**
   * User\'s middle name.
   * @type {string}
   * @memberof UserProfile
   */
  MiddleName?: string | null;
  /**
   * User\'s last name.
   * @type {string}
   * @memberof UserProfile
   */
  LastName?: string | null;
  /**
   * Name suffix.
   * @type {string}
   * @memberof UserProfile
   */
  Suffix?: string | null;
  /**
   * Full name.
   * @type {string}
   * @memberof UserProfile
   */
  FullName?: string | null;
  /**
   * Nickname.
   * @type {string}
   * @memberof UserProfile
   */
  NickName?: string | null;
  /**
   * Profile name.
   * @type {string}
   * @memberof UserProfile
   */
  ProfileName?: string | null;
  /**
   * Birth date.
   * @type {string}
   * @memberof UserProfile
   */
  BirthDate?: string | null;
  /**
   * Gender.
   * @type {string}
   * @memberof UserProfile
   */
  Gender?: string | null;
  /**
   * Personal website URL.
   * @type {string}
   * @memberof UserProfile
   */
  Website?: string | null;
  /**
   *
   * @type {UserProfileEmail}
   * @memberof UserProfile
   */
  Email?: UserProfileEmail;
  /**
   *
   * @type {UserProfileCountry}
   * @memberof UserProfile
   */
  Country?: UserProfileCountry;
  /**
   * Thumbnail image URL.
   * @type {string}
   * @memberof UserProfile
   */
  ThumbnailImageUrl?: string | null;
  /**
   *
   * @type {UserProfileImageUrl}
   * @memberof UserProfile
   */
  ImageUrl?: UserProfileImageUrl;
  /**
   *
   * @type {UserProfileFavicon}
   * @memberof UserProfile
   */
  Favicon?: UserProfileFavicon;
  /**
   *
   * @type {UserProfileProfileUrl}
   * @memberof UserProfile
   */
  ProfileUrl?: UserProfileProfileUrl;
  /**
   * Hometown.
   * @type {string}
   * @memberof UserProfile
   */
  HomeTown?: string | null;
  /**
   * State.
   * @type {string}
   * @memberof UserProfile
   */
  State?: string | null;
  /**
   * City.
   * @type {string}
   * @memberof UserProfile
   */
  City?: string | null;
  /**
   * Industry.
   * @type {string}
   * @memberof UserProfile
   */
  Industry?: string | null;
  /**
   * About the User.
   * @type {string}
   * @memberof UserProfile
   */
  About?: string | null;
  /**
   * Time zone.
   * @type {string}
   * @memberof UserProfile
   */
  TimeZone?: string | null;
  /**
   * Local language.
   * @type {string}
   * @memberof UserProfile
   */
  LocalLanguage?: string | null;
  /**
   *
   * @type {UserProfileCoverPhoto}
   * @memberof UserProfile
   */
  CoverPhoto?: UserProfileCoverPhoto;
  /**
   * Tag line.
   * @type {string}
   * @memberof UserProfile
   */
  TagLine?: string | null;
  /**
   * Preferred language.
   * @type {string}
   * @memberof UserProfile
   */
  Language?: string | null;
  /**
   * Verification status.
   * @type {string}
   * @memberof UserProfile
   */
  Verified?: string | null;
  /**
   * Last updated time.
   * @type {string}
   * @memberof UserProfile
   */
  UpdatedTime?: string | null;
  /**
   *
   * @type {UserProfilePositions}
   * @memberof UserProfile
   */
  Positions?: UserProfilePositions;
  /**
   *
   * @type {UserProfileEducations}
   * @memberof UserProfile
   */
  Educations?: UserProfileEducations;
  /**
   *
   * @type {UserProfilePhoneNumbers}
   * @memberof UserProfile
   */
  PhoneNumbers?: UserProfilePhoneNumbers;
  /**
   *
   * @type {UserProfileIMAccounts}
   * @memberof UserProfile
   */
  IMAccounts?: UserProfileIMAccounts;
  /**
   *
   * @type {UserProfileAddresses}
   * @memberof UserProfile
   */
  Addresses?: UserProfileAddresses;
  /**
   * Main address.
   * @type {string}
   * @memberof UserProfile
   */
  MainAddress?: string | null;
  /**
   * Created timestamp.
   * @type {string}
   * @memberof UserProfile
   */
  Created?: string | null;
  /**
   * Created date.
   * @type {string}
   * @memberof UserProfile
   */
  CreatedDate?: string | null;
  /**
   * Modified date.
   * @type {string}
   * @memberof UserProfile
   */
  ModifiedDate?: string | null;
  /**
   * Profile modified date.
   * @type {string}
   * @memberof UserProfile
   */
  ProfileModifiedDate?: string | null;
  /**
   * Local city.
   * @type {string}
   * @memberof UserProfile
   */
  LocalCity?: string | null;
  /**
   * Profile city.
   * @type {string}
   * @memberof UserProfile
   */
  ProfileCity?: string | null;
  /**
   * Local country.
   * @type {string}
   * @memberof UserProfile
   */
  LocalCountry?: string | null;
  /**
   * Profile country.
   * @type {string}
   * @memberof UserProfile
   */
  ProfileCountry?: string | null;
  /**
   * Whether this is the User\'s first login.
   * @type {boolean}
   * @memberof UserProfile
   */
  FirstLogin?: boolean;
  /**
   * Whether the profile is protected.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsProtected?: boolean;
  /**
   * Relationship status.
   * @type {string}
   * @memberof UserProfile
   */
  RelationshipStatus?: string | null;
  /**
   * Quota.
   * @type {string}
   * @memberof UserProfile
   */
  Quota?: string | null;
  /**
   * List of interests.
   * @type {Array<string>}
   * @memberof UserProfile
   */
  InterestedIn?: Array<string> | null;
  /**
   *
   * @type {UserProfileInterests}
   * @memberof UserProfile
   */
  Interests?: UserProfileInterests;
  /**
   * Religion.
   * @type {string}
   * @memberof UserProfile
   */
  Religion?: string | null;
  /**
   * Political views.
   * @type {string}
   * @memberof UserProfile
   */
  Political?: string | null;
  /**
   *
   * @type {UserProfileSports}
   * @memberof UserProfile
   */
  Sports?: UserProfileSports;
  /**
   *
   * @type {UserProfileInspirationalPeople}
   * @memberof UserProfile
   */
  InspirationalPeople?: UserProfileInspirationalPeople;
  /**
   *
   * @type {UserProfileHttpsImageUrl}
   * @memberof UserProfile
   */
  HttpsImageUrl?: UserProfileHttpsImageUrl;
  /**
   * Number of followers.
   * @type {number}
   * @memberof UserProfile
   */
  FollowersCount?: number;
  /**
   * Number of friends.
   * @type {number}
   * @memberof UserProfile
   */
  FriendsCount?: number;
  /**
   * Whether geo is enabled.
   * @type {string}
   * @memberof UserProfile
   */
  IsGeoEnabled?: string | null;
  /**
   * Total number of statuses.
   * @type {number}
   * @memberof UserProfile
   */
  TotalStatusesCount?: number;
  /**
   * Associations.
   * @type {string}
   * @memberof UserProfile
   */
  Associations?: string | null;
  /**
   * Number of recommenders.
   * @type {number}
   * @memberof UserProfile
   */
  NumRecommenders?: number;
  /**
   * Honors.
   * @type {string}
   * @memberof UserProfile
   */
  Honors?: string | null;
  /**
   *
   * @type {UserProfileAwards}
   * @memberof UserProfile
   */
  Awards?: UserProfileAwards;
  /**
   *
   * @type {UserProfileSkills}
   * @memberof UserProfile
   */
  Skills?: UserProfileSkills;
  /**
   *
   * @type {UserProfileCurrentStatus}
   * @memberof UserProfile
   */
  CurrentStatus?: UserProfileCurrentStatus;
  /**
   *
   * @type {UserProfileCertifications}
   * @memberof UserProfile
   */
  Certifications?: UserProfileCertifications;
  /**
   *
   * @type {UserProfileCourses}
   * @memberof UserProfile
   */
  Courses?: UserProfileCourses;
  /**
   *
   * @type {UserProfileVolunteer}
   * @memberof UserProfile
   */
  Volunteer?: UserProfileVolunteer;
  /**
   *
   * @type {UserProfileRecommendationsReceived}
   * @memberof UserProfile
   */
  RecommendationsReceived?: UserProfileRecommendationsReceived;
  /**
   *
   * @type {UserProfileLanguages}
   * @memberof UserProfile
   */
  Languages?: UserProfileLanguages;
  /**
   *
   * @type {UserProfileProjects}
   * @memberof UserProfile
   */
  Projects?: UserProfileProjects;
  /**
   *
   * @type {UserProfileGames}
   * @memberof UserProfile
   */
  Games?: UserProfileGames;
  /**
   *
   * @type {UserProfileFamily}
   * @memberof UserProfile
   */
  Family?: UserProfileFamily;
  /**
   *
   * @type {UserProfileTeleVisionShow}
   * @memberof UserProfile
   */
  TeleVisionShow?: UserProfileTeleVisionShow;
  /**
   *
   * @type {UserProfileMutualFriends}
   * @memberof UserProfile
   */
  MutualFriends?: UserProfileMutualFriends;
  /**
   *
   * @type {UserProfileMovies}
   * @memberof UserProfile
   */
  Movies?: UserProfileMovies;
  /**
   *
   * @type {UserProfileBooks}
   * @memberof UserProfile
   */
  Books?: UserProfileBooks;
  /**
   *
   * @type {UserProfileAgeRange}
   * @memberof UserProfile
   */
  AgeRange?: UserProfileAgeRange;
  /**
   *
   * @type {UserProfilePublicRepository}
   * @memberof UserProfile
   */
  PublicRepository?: UserProfilePublicRepository;
  /**
   * Whether the User is hireable.
   * @type {boolean}
   * @memberof UserProfile
   */
  Hireable?: boolean;
  /**
   *
   * @type {UserProfileRepositoryUrl}
   * @memberof UserProfile
   */
  RepositoryUrl?: UserProfileRepositoryUrl;
  /**
   * Age of the User.
   * @type {number}
   * @memberof UserProfile
   */
  Age?: number | null;
  /**
   *
   * @type {UserProfilePatents}
   * @memberof UserProfile
   */
  Patents?: UserProfilePatents;
  /**
   *
   * @type {UserProfileFavoriteThings}
   * @memberof UserProfile
   */
  FavoriteThings?: UserProfileFavoriteThings;
  /**
   * Professional headline.
   * @type {string}
   * @memberof UserProfile
   */
  ProfessionalHeadline?: string | null;
  /**
   *
   * @type {UserProfileRelatedProfileViews}
   * @memberof UserProfile
   */
  RelatedProfileViews?: UserProfileRelatedProfileViews;
  /**
   *
   * @type {UserProfileKloutScore}
   * @memberof UserProfile
   */
  KloutScore?: UserProfileKloutScore;
  /**
   * LoginRadius User ID.
   * @type {string}
   * @memberof UserProfile
   */
  LRUserID?: string | null;
  /**
   *
   * @type {UserProfilePlacesLived}
   * @memberof UserProfile
   */
  PlacesLived?: UserProfilePlacesLived;
  /**
   *
   * @type {UserProfilePublications}
   * @memberof UserProfile
   */
  Publications?: UserProfilePublications;
  /**
   *
   * @type {UserProfileJobBookmarks}
   * @memberof UserProfile
   */
  JobBookmarks?: UserProfileJobBookmarks;
  /**
   *
   * @type {UserProfileSuggestions}
   * @memberof UserProfile
   */
  Suggestions?: UserProfileSuggestions;
  /**
   *
   * @type {UserProfileBadges}
   * @memberof UserProfile
   */
  Badges?: UserProfileBadges;
  /**
   *
   * @type {UserProfileMemberUrlResources}
   * @memberof UserProfile
   */
  MemberUrlResources?: UserProfileMemberUrlResources;
  /**
   * Total number of private repositories.
   * @type {number}
   * @memberof UserProfile
   */
  TotalPrivateRepository?: number;
  /**
   * Currency.
   * @type {string}
   * @memberof UserProfile
   */
  Currency?: string | null;
  /**
   *
   * @type {UserProfileStarredUrl}
   * @memberof UserProfile
   */
  StarredUrl?: UserProfileStarredUrl;
  /**
   *
   * @type {UserProfileGistsUrl}
   * @memberof UserProfile
   */
  GistsUrl?: UserProfileGistsUrl;
  /**
   * Number of public gists.
   * @type {number}
   * @memberof UserProfile
   */
  PublicGists?: number;
  /**
   * Number of private gists.
   * @type {number}
   * @memberof UserProfile
   */
  PrivateGists?: number;
  /**
   *
   * @type {UserProfileSubscription}
   * @memberof UserProfile
   */
  Subscription?: UserProfileSubscription;
  /**
   * Company name.
   * @type {string}
   * @memberof UserProfile
   */
  Company?: string | null;
  /**
   *
   * @type {UserProfileGravatarImageUrl}
   * @memberof UserProfile
   */
  GravatarImageUrl?: UserProfileGravatarImageUrl;
  /**
   *
   * @type {UserProfileProfileImageUrls}
   * @memberof UserProfile
   */
  ProfileImageUrls?: UserProfileProfileImageUrls;
  /**
   *
   * @type {UserProfileWebProfiles}
   * @memberof UserProfile
   */
  WebProfiles?: UserProfileWebProfiles;
  /**
   * Number of PINs.
   * @type {number}
   * @memberof UserProfile
   */
  PinsCount?: number;
  /**
   * Number of boards.
   * @type {number}
   * @memberof UserProfile
   */
  BoardsCount?: number;
  /**
   * Number of likes.
   * @type {number}
   * @memberof UserProfile
   */
  LikesCount?: number;
  /**
   * Whether Email is verified from social login.
   * @type {boolean}
   * @memberof UserProfile
   */
  EmailVerifiedFromSocial?: boolean;
  /**
   * Signup date.
   * @type {string}
   * @memberof UserProfile
   */
  SignupDate?: string | null;
  /**
   * Last login date.
   * @type {string}
   * @memberof UserProfile
   */
  LastLoginDate?: string | null;
  /**
   *
   * @type {UserProfileCustomFields}
   * @memberof UserProfile
   */
  CustomFields?: UserProfileCustomFields;
  /**
   * Last Password change date.
   * @type {string}
   * @memberof UserProfile
   */
  LastPasswordChangeDate?: string | null;
  /**
   * Password expiration date.
   * @type {string}
   * @memberof UserProfile
   */
  PasswordExpirationDate?: string | null;
  /**
   * Last Password change token.
   * @type {string}
   * @memberof UserProfile
   */
  LastPasswordChangeToken?: string | null;
  /**
   * Whether Email is verified.
   * @type {boolean}
   * @memberof UserProfile
   */
  EmailVerified?: boolean;
  /**
   * Whether the User is active.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsActive?: boolean;
  /**
   * Whether the User is deleted.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsDeleted?: boolean;
  /**
   * Whether the User is subscribed to emails.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsEmailSubscribed?: boolean;
  /**
   * Username.
   * @type {string}
   * @memberof UserProfile
   */
  UserName?: string | null;
  /**
   * Number of logins.
   * @type {number}
   * @memberof UserProfile
   */
  NoOfLogins?: number;
  /**
   * Previous UIDs.
   * @type {Array<string>}
   * @memberof UserProfile
   */
  PreviousUids?: Array<string> | null;
  /**
   * Phone ID.
   * @type {string}
   * @memberof UserProfile
   */
  PhoneId?: string | null;
  /**
   * Whether Phone ID is verified.
   * @type {boolean}
   * @memberof UserProfile
   */
  PhoneIdVerified?: boolean;
  /**
   * List of Roles.
   * @type {Array<string>}
   * @memberof UserProfile
   */
  Roles?: Array<string> | null;
  /**
   * External User login ID.
   * @type {string}
   * @memberof UserProfile
   */
  ExternalUserLoginId?: string | null;
  /**
   * Number of failed login attempts.
   * @type {number}
   * @memberof UserProfile
   */
  FailedLoginAttempt?: number;
  /**
   * Failed security question attempts for Password reset.
   * @type {number}
   * @memberof UserProfile
   */
  SecurityQuestionFailedResetPasswordAttempts?: number;
  /**
   * Failed security question attempts for login.
   * @type {number}
   * @memberof UserProfile
   */
  SecurityQuestionFailedLoginAttempt?: number;
  /**
   * Whether login is disabled.
   * @type {boolean}
   * @memberof UserProfile
   */
  DisableLogin?: boolean;
  /**
   * Registration provider.
   * @type {string}
   * @memberof UserProfile
   */
  RegistrationProvider?: string | null;
  /**
   * Whether login is locked.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsLoginLocked?: boolean;
  /**
   * Type of login lock.
   * @type {string}
   * @memberof UserProfile
   */
  LoginLockedType?: string | null;
  /**
   * Last login location.
   * @type {string}
   * @memberof UserProfile
   */
  LastLoginLocation?: string | null;
  /**
   * Registration source.
   * @type {string}
   * @memberof UserProfile
   */
  RegistrationSource?: string | null;
  /**
   * Whether UID is custom.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsCustomUid?: boolean;
  /**
   *
   * @type {UserProfileUnverifiedEmail}
   * @memberof UserProfile
   */
  UnverifiedEmail?: UserProfileUnverifiedEmail;
  /**
   *
   * @type {UserProfileRoleContext}
   * @memberof UserProfile
   */
  RoleContext?: UserProfileRoleContext;
  /**
   *
   * @type {UserProfileKnownLoginVariables}
   * @memberof UserProfile
   */
  KnownLoginVariables?: UserProfileKnownLoginVariables;
  /**
   * Whether the Password is secure.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsSecurePassword?: boolean | null;
  /**
   *
   * @type {UserProfilePrivacyPolicy}
   * @memberof UserProfile
   */
  PrivacyPolicy?: UserProfilePrivacyPolicy;
  /**
   * Login locked timeout.
   * @type {string}
   * @memberof UserProfile
   */
  LoginLockedTimeout?: string | null;
  /**
   *
   * @type {UserProfileExternalIds}
   * @memberof UserProfile
   */
  ExternalIds?: UserProfileExternalIds;
  /**
   * Whether required fields are filled at least once.
   * @type {boolean}
   * @memberof UserProfile
   */
  IsRequiredFieldsFilledOnce?: boolean;
  /**
   *
   * @type {UserProfileSignupLog}
   * @memberof UserProfile
   */
  SignupLog?: UserProfileSignupLog;
  /**
   * Last accepted consent version.
   * @type {number}
   * @memberof UserProfile
   */
  LastAcceptedConsentVersion?: number;
  /**
   *
   * @type {UserProfileUserAgent}
   * @memberof UserProfile
   */
  user_agent?: UserProfileUserAgent;
}
