/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BasicAuthWebhook } from './basic-auth-webhook';
// May contain unused imports in some cases
// @ts-ignore
import type { Bearertoken } from './bearertoken';

/**
 *
 * @export
 * @interface WebhookAuthentication
 */
export interface WebhookAuthentication {
  /**
   * The type of authentication used for the webhook
   * @type {string}
   * @memberof WebhookAuthentication
   */
  AuthType?: WebhookAuthenticationAuthTypeEnum;
  /**
   *
   * @type {BasicAuthWebhook}
   * @memberof WebhookAuthentication
   */
  BasicAuth?: BasicAuthWebhook;
  /**
   *
   * @type {Bearertoken}
   * @memberof WebhookAuthentication
   */
  BearerToken?: Bearertoken;
}

/**
 * @export
 * @enum {string}
 */
export enum WebhookAuthenticationAuthTypeEnum {
  Basic = 'Basic',
  Bearer = 'Bearer',
}
