// Code generated by the LoginRadius SDK generator; DO NOT EDIT.
//
// Behaviour is declared in the shared SDK manifest and rendered through
// the SDK generator templates Edit those and regenerate —
// changes made here are lost on the next run and never reach the other SDKs.

// VERSION is stamped into the User-Agent header on every request. It comes
// from the shared SDK manifest `sdkVersion`, the same value package.json is rendered
// with, so the two can no longer drift.
export const VERSION = '12.0.0-rc.1';
