// Code generated by sdk-factory (scripts/generate.sh); DO NOT EDIT.
//
// Behaviour is declared in manifest/sdk.yaml and rendered through
// languages/node/templates/version.mustache. Edit those and regenerate —
// changes made here are lost on the next run and never reach the other SDKs.

// VERSION is stamped into the User-Agent header on every request. It comes
// from manifest/sdk.yaml `sdkVersion`, the same value package.json is rendered
// with, so the two can no longer drift.
export const VERSION = '12.0.0-rc.1';
