/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ConsentForm } from '../model';
// @ts-ignore
import type { ConsentFormModel } from '../model';
// @ts-ignore
import type { ConsentOptionModel } from '../model';
// @ts-ignore
import type { ConsentOptions } from '../model';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { GetConsentForms200Response } from '../model';
// @ts-ignore
import type { GetConsentOptions200Response } from '../model';
// @ts-ignore
import type { IsDeleted } from '../model';
/**
 * ConsentApi - axios parameter creator
 * @export
 */
export const ConsentApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Adds a new Consent Form for the Tenant.
     * @summary Add Consent Form
     * @param {ConsentFormModel} consentFormModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addConsentForm: async (
      consentFormModel: ConsentFormModel,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'consentFormModel' is not null or undefined
      assertParamExists('addConsentForm', 'consentFormModel', consentFormModel);
      const localVarPath = `/consent/forms`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        consentFormModel,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Creates a new consent option for a specific Tenant.
     * @summary Create Consent Option
     * @param {ConsentOptionModel} consentOptionModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConsentOption: async (
      consentOptionModel: ConsentOptionModel,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'consentOptionModel' is not null or undefined
      assertParamExists('createConsentOption', 'consentOptionModel', consentOptionModel);
      const localVarPath = `/consent/options`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        consentOptionModel,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes the Consent Form identified by the form version for the Tenant.
     * @summary Delete Consent Form
     * @param {string} version The version of the Consent form to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConsentForm: async (
      version: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'version' is not null or undefined
      assertParamExists('deleteConsentForm', 'version', version);
      const localVarPath = `/consent/forms/{version}`.replace(
        `{${'version'}}`,
        encodeURIComponent(String(version)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes the consent option identified by the option ID for the Tenant.
     * @summary Delete Consent Option
     * @param {string} optionId The ID of the Consent option to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConsentOption: async (
      optionId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'optionId' is not null or undefined
      assertParamExists('deleteConsentOption', 'optionId', optionId);
      const localVarPath = `/consent/options/{optionId}`.replace(
        `{${'optionId'}}`,
        encodeURIComponent(String(optionId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves a list of active Consent Forms configured for the Tenant.
     * @summary Retrieve Active Consent Forms
     * @param {string} event Event type to filter consent verification (e.g., &#x60;login&#x60;).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActiveConsentForms: async (
      event: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'event' is not null or undefined
      assertParamExists('getActiveConsentForms', 'event', event);
      const localVarPath = `/consent/forms/active`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (event !== undefined) {
        localVarQueryParameter['event'] = event;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves all Consent Forms configured for the Tenant.
     * @summary Retrieve Consent Forms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConsentForms: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/consent/forms`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Lists all consent options available for a specific Tenant.
     * @summary Retrieve Consent Options
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConsentOptions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/consent/options`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ConsentApi - functional programming interface
 * @export
 */
export const ConsentApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ConsentApiAxiosParamCreator(configuration);
  return {
    /**
     * Adds a new Consent Form for the Tenant.
     * @summary Add Consent Form
     * @param {ConsentFormModel} consentFormModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addConsentForm(
      consentFormModel: ConsentFormModel,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsentForm>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addConsentForm(
        consentFormModel,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.addConsentForm']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Creates a new consent option for a specific Tenant.
     * @summary Create Consent Option
     * @param {ConsentOptionModel} consentOptionModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createConsentOption(
      consentOptionModel: ConsentOptionModel,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsentOptions>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createConsentOption(
        consentOptionModel,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.createConsentOption']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes the Consent Form identified by the form version for the Tenant.
     * @summary Delete Consent Form
     * @param {string} version The version of the Consent form to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteConsentForm(
      version: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IsDeleted>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteConsentForm(version, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.deleteConsentForm']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes the consent option identified by the option ID for the Tenant.
     * @summary Delete Consent Option
     * @param {string} optionId The ID of the Consent option to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteConsentOption(
      optionId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IsDeleted>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteConsentOption(
        optionId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.deleteConsentOption']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves a list of active Consent Forms configured for the Tenant.
     * @summary Retrieve Active Consent Forms
     * @param {string} event Event type to filter consent verification (e.g., &#x60;login&#x60;).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getActiveConsentForms(
      event: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetConsentForms200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getActiveConsentForms(
        event,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.getActiveConsentForms']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves all Consent Forms configured for the Tenant.
     * @summary Retrieve Consent Forms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getConsentForms(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetConsentForms200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getConsentForms(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.getConsentForms']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Lists all consent options available for a specific Tenant.
     * @summary Retrieve Consent Options
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getConsentOptions(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetConsentOptions200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getConsentOptions(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentApi.getConsentOptions']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ConsentApi - factory interface
 * @export
 */
export const ConsentApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ConsentApiFp(configuration);
  return {
    /**
     * Adds a new Consent Form for the Tenant.
     * @summary Add Consent Form
     * @param {ConsentApiAddConsentFormRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addConsentForm(
      requestParameters: ConsentApiAddConsentFormRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ConsentForm> {
      return localVarFp
        .addConsentForm(requestParameters.consentFormModel, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Creates a new consent option for a specific Tenant.
     * @summary Create Consent Option
     * @param {ConsentApiCreateConsentOptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConsentOption(
      requestParameters: ConsentApiCreateConsentOptionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ConsentOptions> {
      return localVarFp
        .createConsentOption(requestParameters.consentOptionModel, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes the Consent Form identified by the form version for the Tenant.
     * @summary Delete Consent Form
     * @param {ConsentApiDeleteConsentFormRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConsentForm(
      requestParameters: ConsentApiDeleteConsentFormRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<IsDeleted> {
      return localVarFp
        .deleteConsentForm(requestParameters.version, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes the consent option identified by the option ID for the Tenant.
     * @summary Delete Consent Option
     * @param {ConsentApiDeleteConsentOptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConsentOption(
      requestParameters: ConsentApiDeleteConsentOptionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<IsDeleted> {
      return localVarFp
        .deleteConsentOption(requestParameters.optionId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves a list of active Consent Forms configured for the Tenant.
     * @summary Retrieve Active Consent Forms
     * @param {ConsentApiGetActiveConsentFormsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActiveConsentForms(
      requestParameters: ConsentApiGetActiveConsentFormsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetConsentForms200Response> {
      return localVarFp
        .getActiveConsentForms(requestParameters.event, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves all Consent Forms configured for the Tenant.
     * @summary Retrieve Consent Forms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConsentForms(options?: RawAxiosRequestConfig): AxiosPromise<GetConsentForms200Response> {
      return localVarFp.getConsentForms(options).then((request) => request(axios, basePath));
    },
    /**
     * Lists all consent options available for a specific Tenant.
     * @summary Retrieve Consent Options
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConsentOptions(options?: RawAxiosRequestConfig): AxiosPromise<GetConsentOptions200Response> {
      return localVarFp.getConsentOptions(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * ConsentApi - interface
 * @export
 * @interface ConsentApi
 */
export interface ConsentApiInterface {
  /**
   * Adds a new Consent Form for the Tenant.
   * @summary Add Consent Form
   * @param {ConsentApiAddConsentFormRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  addConsentForm(
    requestParameters: ConsentApiAddConsentFormRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ConsentForm>;

  /**
   * Creates a new consent option for a specific Tenant.
   * @summary Create Consent Option
   * @param {ConsentApiCreateConsentOptionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  createConsentOption(
    requestParameters: ConsentApiCreateConsentOptionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ConsentOptions>;

  /**
   * Deletes the Consent Form identified by the form version for the Tenant.
   * @summary Delete Consent Form
   * @param {ConsentApiDeleteConsentFormRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  deleteConsentForm(
    requestParameters: ConsentApiDeleteConsentFormRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<IsDeleted>;

  /**
   * Deletes the consent option identified by the option ID for the Tenant.
   * @summary Delete Consent Option
   * @param {ConsentApiDeleteConsentOptionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  deleteConsentOption(
    requestParameters: ConsentApiDeleteConsentOptionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<IsDeleted>;

  /**
   * Retrieves a list of active Consent Forms configured for the Tenant.
   * @summary Retrieve Active Consent Forms
   * @param {ConsentApiGetActiveConsentFormsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  getActiveConsentForms(
    requestParameters: ConsentApiGetActiveConsentFormsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetConsentForms200Response>;

  /**
   * Retrieves all Consent Forms configured for the Tenant.
   * @summary Retrieve Consent Forms
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  getConsentForms(options?: RawAxiosRequestConfig): AxiosPromise<GetConsentForms200Response>;

  /**
   * Lists all consent options available for a specific Tenant.
   * @summary Retrieve Consent Options
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApiInterface
   */
  getConsentOptions(options?: RawAxiosRequestConfig): AxiosPromise<GetConsentOptions200Response>;
}

/**
 * Request parameters for addConsentForm operation in ConsentApi.
 * @export
 * @interface ConsentApiAddConsentFormRequest
 */
export interface ConsentApiAddConsentFormRequest {
  /**
   *
   * @type {ConsentFormModel}
   * @memberof ConsentApiAddConsentForm
   */
  readonly consentFormModel: ConsentFormModel;
}

/**
 * Request parameters for createConsentOption operation in ConsentApi.
 * @export
 * @interface ConsentApiCreateConsentOptionRequest
 */
export interface ConsentApiCreateConsentOptionRequest {
  /**
   *
   * @type {ConsentOptionModel}
   * @memberof ConsentApiCreateConsentOption
   */
  readonly consentOptionModel: ConsentOptionModel;
}

/**
 * Request parameters for deleteConsentForm operation in ConsentApi.
 * @export
 * @interface ConsentApiDeleteConsentFormRequest
 */
export interface ConsentApiDeleteConsentFormRequest {
  /**
   * The version of the Consent form to delete.
   * @type {string}
   * @memberof ConsentApiDeleteConsentForm
   */
  readonly version: string;
}

/**
 * Request parameters for deleteConsentOption operation in ConsentApi.
 * @export
 * @interface ConsentApiDeleteConsentOptionRequest
 */
export interface ConsentApiDeleteConsentOptionRequest {
  /**
   * The ID of the Consent option to delete.
   * @type {string}
   * @memberof ConsentApiDeleteConsentOption
   */
  readonly optionId: string;
}

/**
 * Request parameters for getActiveConsentForms operation in ConsentApi.
 * @export
 * @interface ConsentApiGetActiveConsentFormsRequest
 */
export interface ConsentApiGetActiveConsentFormsRequest {
  /**
   * Event type to filter consent verification (e.g., &#x60;login&#x60;).
   * @type {string}
   * @memberof ConsentApiGetActiveConsentForms
   */
  readonly event: string;
}

/**
 * ConsentApi - object-oriented interface
 * @export
 * @class ConsentApi
 * @extends {BaseAPI}
 */
export class ConsentApi extends BaseAPI implements ConsentApiInterface {
  /**
   * Adds a new Consent Form for the Tenant.
   * @summary Add Consent Form
   * @param {ConsentApiAddConsentFormRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public addConsentForm(
    requestParameters: ConsentApiAddConsentFormRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConsentApiFp(this.configuration)
      .addConsentForm(requestParameters.consentFormModel, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Creates a new consent option for a specific Tenant.
   * @summary Create Consent Option
   * @param {ConsentApiCreateConsentOptionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public createConsentOption(
    requestParameters: ConsentApiCreateConsentOptionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConsentApiFp(this.configuration)
      .createConsentOption(requestParameters.consentOptionModel, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes the Consent Form identified by the form version for the Tenant.
   * @summary Delete Consent Form
   * @param {ConsentApiDeleteConsentFormRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public deleteConsentForm(
    requestParameters: ConsentApiDeleteConsentFormRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConsentApiFp(this.configuration)
      .deleteConsentForm(requestParameters.version, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes the consent option identified by the option ID for the Tenant.
   * @summary Delete Consent Option
   * @param {ConsentApiDeleteConsentOptionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public deleteConsentOption(
    requestParameters: ConsentApiDeleteConsentOptionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConsentApiFp(this.configuration)
      .deleteConsentOption(requestParameters.optionId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves a list of active Consent Forms configured for the Tenant.
   * @summary Retrieve Active Consent Forms
   * @param {ConsentApiGetActiveConsentFormsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public getActiveConsentForms(
    requestParameters: ConsentApiGetActiveConsentFormsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConsentApiFp(this.configuration)
      .getActiveConsentForms(requestParameters.event, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves all Consent Forms configured for the Tenant.
   * @summary Retrieve Consent Forms
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public getConsentForms(options?: RawAxiosRequestConfig) {
    return ConsentApiFp(this.configuration)
      .getConsentForms(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Lists all consent options available for a specific Tenant.
   * @summary Retrieve Consent Options
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConsentApi
   */
  public getConsentOptions(options?: RawAxiosRequestConfig) {
    return ConsentApiFp(this.configuration)
      .getConsentOptions(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
