/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { CustomFieldLimitResponse } from '../model';
// @ts-ignore
import type { DeleteResponse } from '../model';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { GetAllCustomFields200Response } from '../model';
// @ts-ignore
import type { RaasCustomField } from '../model';
// @ts-ignore
import type { RaasCustomFieldModel } from '../model';
// @ts-ignore
import type { SetCustomField200Response } from '../model';
// @ts-ignore
import type { SetCustomFieldRequest } from '../model';
// @ts-ignore
import type { SetProvidersOrderRequest } from '../model';
/**
 * CustomFieldsApi - axios parameter creator
 * @export
 */
export const CustomFieldsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a new Custom Field for the Tenant.
     * @summary Create custom field
     * @param {RaasCustomFieldModel} raasCustomFieldModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCustomField: async (
      raasCustomFieldModel: RaasCustomFieldModel,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'raasCustomFieldModel' is not null or undefined
      assertParamExists('createCustomField', 'raasCustomFieldModel', raasCustomFieldModel);
      const localVarPath = `/v2/manage/custom-fields`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        raasCustomFieldModel,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes a Custom Field by name for the Tenant.
     * @summary Delete custom field
     * @param {string} cfname Custom Fields Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCustomField: async (
      cfname: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'cfname' is not null or undefined
      assertParamExists('deleteCustomField', 'cfname', cfname);
      const localVarPath = `/v2/manage/custom-fields/{cfname}`.replace(
        `{${'cfname'}}`,
        encodeURIComponent(String(cfname)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves all custom fields currently active in the registration form for the Tenant.
     * @summary List active custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActiveCustomFields: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/custom-fields/active`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves all Custom Fields created for the Tenant.
     * @summary List custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllCustomFields: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/custom-fields`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves the Custom Field Limit configured for the Tenant.
     * @summary Retrieve custom field limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCustomFieldLimit: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/custom-fields/limit`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves all custom fields for the Tenant, returned as an array of strings.
     * @summary List custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCustomFields: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/custom-fields/list`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates or sets a Custom Field instance in RAAS to be displayed on forms for the Tenant.
     * @summary Set custom field
     * @param {SetCustomFieldRequest} setCustomFieldRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setCustomField: async (
      setCustomFieldRequest: SetCustomFieldRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'setCustomFieldRequest' is not null or undefined
      assertParamExists('setCustomField', 'setCustomFieldRequest', setCustomFieldRequest);
      const localVarPath = `/v2/manage/custom-fields`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        setCustomFieldRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CustomFieldsApi - functional programming interface
 * @export
 */
export const CustomFieldsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CustomFieldsApiAxiosParamCreator(configuration);
  return {
    /**
     * Creates a new Custom Field for the Tenant.
     * @summary Create custom field
     * @param {RaasCustomFieldModel} raasCustomFieldModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createCustomField(
      raasCustomFieldModel: RaasCustomFieldModel,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RaasCustomField>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createCustomField(
        raasCustomFieldModel,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.createCustomField']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes a Custom Field by name for the Tenant.
     * @summary Delete custom field
     * @param {string} cfname Custom Fields Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteCustomField(
      cfname: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCustomField(cfname, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.deleteCustomField']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves all custom fields currently active in the registration form for the Tenant.
     * @summary List active custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getActiveCustomFields(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetCustomField200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getActiveCustomFields(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.getActiveCustomFields']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves all Custom Fields created for the Tenant.
     * @summary List custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllCustomFields(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllCustomFields200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAllCustomFields(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.getAllCustomFields']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves the Custom Field Limit configured for the Tenant.
     * @summary Retrieve custom field limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCustomFieldLimit(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomFieldLimitResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomFieldLimit(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.getCustomFieldLimit']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves all custom fields for the Tenant, returned as an array of strings.
     * @summary List custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listCustomFields(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetProvidersOrderRequest>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listCustomFields(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.listCustomFields']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Updates or sets a Custom Field instance in RAAS to be displayed on forms for the Tenant.
     * @summary Set custom field
     * @param {SetCustomFieldRequest} setCustomFieldRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async setCustomField(
      setCustomFieldRequest: SetCustomFieldRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetCustomField200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.setCustomField(
        setCustomFieldRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CustomFieldsApi.setCustomField']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CustomFieldsApi - factory interface
 * @export
 */
export const CustomFieldsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CustomFieldsApiFp(configuration);
  return {
    /**
     * Creates a new Custom Field for the Tenant.
     * @summary Create custom field
     * @param {CustomFieldsApiCreateCustomFieldRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCustomField(
      requestParameters: CustomFieldsApiCreateCustomFieldRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RaasCustomField> {
      return localVarFp
        .createCustomField(requestParameters.raasCustomFieldModel, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes a Custom Field by name for the Tenant.
     * @summary Delete custom field
     * @param {CustomFieldsApiDeleteCustomFieldRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCustomField(
      requestParameters: CustomFieldsApiDeleteCustomFieldRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<DeleteResponse> {
      return localVarFp
        .deleteCustomField(requestParameters.cfname, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves all custom fields currently active in the registration form for the Tenant.
     * @summary List active custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActiveCustomFields(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SetCustomField200Response> {
      return localVarFp.getActiveCustomFields(options).then((request) => request(axios, basePath));
    },
    /**
     * Retrieves all Custom Fields created for the Tenant.
     * @summary List custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllCustomFields(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetAllCustomFields200Response> {
      return localVarFp.getAllCustomFields(options).then((request) => request(axios, basePath));
    },
    /**
     * Retrieves the Custom Field Limit configured for the Tenant.
     * @summary Retrieve custom field limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCustomFieldLimit(options?: RawAxiosRequestConfig): AxiosPromise<CustomFieldLimitResponse> {
      return localVarFp.getCustomFieldLimit(options).then((request) => request(axios, basePath));
    },
    /**
     * Retrieves all custom fields for the Tenant, returned as an array of strings.
     * @summary List custom fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCustomFields(options?: RawAxiosRequestConfig): AxiosPromise<SetProvidersOrderRequest> {
      return localVarFp.listCustomFields(options).then((request) => request(axios, basePath));
    },
    /**
     * Updates or sets a Custom Field instance in RAAS to be displayed on forms for the Tenant.
     * @summary Set custom field
     * @param {CustomFieldsApiSetCustomFieldRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setCustomField(
      requestParameters: CustomFieldsApiSetCustomFieldRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SetCustomField200Response> {
      return localVarFp
        .setCustomField(requestParameters.setCustomFieldRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CustomFieldsApi - interface
 * @export
 * @interface CustomFieldsApi
 */
export interface CustomFieldsApiInterface {
  /**
   * Creates a new Custom Field for the Tenant.
   * @summary Create custom field
   * @param {CustomFieldsApiCreateCustomFieldRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  createCustomField(
    requestParameters: CustomFieldsApiCreateCustomFieldRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RaasCustomField>;

  /**
   * Deletes a Custom Field by name for the Tenant.
   * @summary Delete custom field
   * @param {CustomFieldsApiDeleteCustomFieldRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  deleteCustomField(
    requestParameters: CustomFieldsApiDeleteCustomFieldRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<DeleteResponse>;

  /**
   * Retrieves all custom fields currently active in the registration form for the Tenant.
   * @summary List active custom fields
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  getActiveCustomFields(options?: RawAxiosRequestConfig): AxiosPromise<SetCustomField200Response>;

  /**
   * Retrieves all Custom Fields created for the Tenant.
   * @summary List custom fields
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  getAllCustomFields(options?: RawAxiosRequestConfig): AxiosPromise<GetAllCustomFields200Response>;

  /**
   * Retrieves the Custom Field Limit configured for the Tenant.
   * @summary Retrieve custom field limit
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  getCustomFieldLimit(options?: RawAxiosRequestConfig): AxiosPromise<CustomFieldLimitResponse>;

  /**
   * Retrieves all custom fields for the Tenant, returned as an array of strings.
   * @summary List custom fields
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  listCustomFields(options?: RawAxiosRequestConfig): AxiosPromise<SetProvidersOrderRequest>;

  /**
   * Updates or sets a Custom Field instance in RAAS to be displayed on forms for the Tenant.
   * @summary Set custom field
   * @param {CustomFieldsApiSetCustomFieldRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApiInterface
   */
  setCustomField(
    requestParameters: CustomFieldsApiSetCustomFieldRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SetCustomField200Response>;
}

/**
 * Request parameters for createCustomField operation in CustomFieldsApi.
 * @export
 * @interface CustomFieldsApiCreateCustomFieldRequest
 */
export interface CustomFieldsApiCreateCustomFieldRequest {
  /**
   *
   * @type {RaasCustomFieldModel}
   * @memberof CustomFieldsApiCreateCustomField
   */
  readonly raasCustomFieldModel: RaasCustomFieldModel;
}

/**
 * Request parameters for deleteCustomField operation in CustomFieldsApi.
 * @export
 * @interface CustomFieldsApiDeleteCustomFieldRequest
 */
export interface CustomFieldsApiDeleteCustomFieldRequest {
  /**
   * Custom Fields Name
   * @type {string}
   * @memberof CustomFieldsApiDeleteCustomField
   */
  readonly cfname: string;
}

/**
 * Request parameters for setCustomField operation in CustomFieldsApi.
 * @export
 * @interface CustomFieldsApiSetCustomFieldRequest
 */
export interface CustomFieldsApiSetCustomFieldRequest {
  /**
   *
   * @type {SetCustomFieldRequest}
   * @memberof CustomFieldsApiSetCustomField
   */
  readonly setCustomFieldRequest: SetCustomFieldRequest;
}

/**
 * CustomFieldsApi - object-oriented interface
 * @export
 * @class CustomFieldsApi
 * @extends {BaseAPI}
 */
export class CustomFieldsApi extends BaseAPI implements CustomFieldsApiInterface {
  /**
   * Creates a new Custom Field for the Tenant.
   * @summary Create custom field
   * @param {CustomFieldsApiCreateCustomFieldRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public createCustomField(
    requestParameters: CustomFieldsApiCreateCustomFieldRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CustomFieldsApiFp(this.configuration)
      .createCustomField(requestParameters.raasCustomFieldModel, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes a Custom Field by name for the Tenant.
   * @summary Delete custom field
   * @param {CustomFieldsApiDeleteCustomFieldRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public deleteCustomField(
    requestParameters: CustomFieldsApiDeleteCustomFieldRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CustomFieldsApiFp(this.configuration)
      .deleteCustomField(requestParameters.cfname, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves all custom fields currently active in the registration form for the Tenant.
   * @summary List active custom fields
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public getActiveCustomFields(options?: RawAxiosRequestConfig) {
    return CustomFieldsApiFp(this.configuration)
      .getActiveCustomFields(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves all Custom Fields created for the Tenant.
   * @summary List custom fields
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public getAllCustomFields(options?: RawAxiosRequestConfig) {
    return CustomFieldsApiFp(this.configuration)
      .getAllCustomFields(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves the Custom Field Limit configured for the Tenant.
   * @summary Retrieve custom field limit
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public getCustomFieldLimit(options?: RawAxiosRequestConfig) {
    return CustomFieldsApiFp(this.configuration)
      .getCustomFieldLimit(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves all custom fields for the Tenant, returned as an array of strings.
   * @summary List custom fields
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public listCustomFields(options?: RawAxiosRequestConfig) {
    return CustomFieldsApiFp(this.configuration)
      .listCustomFields(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates or sets a Custom Field instance in RAAS to be displayed on forms for the Tenant.
   * @summary Set custom field
   * @param {CustomFieldsApiSetCustomFieldRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomFieldsApi
   */
  public setCustomField(
    requestParameters: CustomFieldsApiSetCustomFieldRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CustomFieldsApiFp(this.configuration)
      .setCustomField(requestParameters.setCustomFieldRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
