/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ApiError } from '../model';
// @ts-ignore
import type { UserProfileRequestBody } from '../model';
// @ts-ignore
import type { UserProfileResponse } from '../model';
// @ts-ignore
import type { UserProfileScrollResponse } from '../model';
/**
 * IdentityApi - axios parameter creator
 * @export
 */
export const IdentityApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Retrieves User\'s data using the specified pagination parameters.
     * @summary Retrieve User\'s by pagination
     * @param {string} [next] Scroll or pagination token for fetching the next set of results. This token is used to retrieve the next page of results in a paginated response. If not provided, the API will return the first page of results.
     * @param {string} [region] The region to filter results by.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserProfilesByPageId: async (
      next?: string,
      region?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/identity`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication APIKey required
      await setApiKeyToObject(localVarQueryParameter, 'apikey', configuration);

      // authentication XLoginRadiusAPIKey required
      await setApiKeyToObject(localVarHeaderParameter, 'X-LoginRadius-ApiKey', configuration);

      // authentication XLoginRadiusAPISecret required
      await setApiKeyToObject(localVarHeaderParameter, 'X-LoginRadius-ApiSecret', configuration);

      // authentication APISecret required
      await setApiKeyToObject(localVarQueryParameter, 'apisecret', configuration);

      if (next !== undefined) {
        localVarQueryParameter['next'] = next;
      }

      if (region !== undefined) {
        localVarQueryParameter['region'] = region;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves User\'s data based on specified query filters.
     * @summary Retrieve User\'s by query
     * @param {UserProfileRequestBody} userProfileRequestBody
     * @param {string} [region] The region to filter results by.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    queryUserProfiles: async (
      userProfileRequestBody: UserProfileRequestBody,
      region?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userProfileRequestBody' is not null or undefined
      assertParamExists('queryUserProfiles', 'userProfileRequestBody', userProfileRequestBody);
      const localVarPath = `/identity`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication APIKey required
      await setApiKeyToObject(localVarQueryParameter, 'apikey', configuration);

      // authentication XLoginRadiusAPIKey required
      await setApiKeyToObject(localVarHeaderParameter, 'X-LoginRadius-ApiKey', configuration);

      // authentication XLoginRadiusAPISecret required
      await setApiKeyToObject(localVarHeaderParameter, 'X-LoginRadius-ApiSecret', configuration);

      // authentication APISecret required
      await setApiKeyToObject(localVarQueryParameter, 'apisecret', configuration);

      if (region !== undefined) {
        localVarQueryParameter['region'] = region;
      }

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userProfileRequestBody,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * IdentityApi - functional programming interface
 * @export
 */
export const IdentityApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = IdentityApiAxiosParamCreator(configuration);
  return {
    /**
     * Retrieves User\'s data using the specified pagination parameters.
     * @summary Retrieve User\'s by pagination
     * @param {string} [next] Scroll or pagination token for fetching the next set of results. This token is used to retrieve the next page of results in a paginated response. If not provided, the API will return the first page of results.
     * @param {string} [region] The region to filter results by.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getUserProfilesByPageId(
      next?: string,
      region?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserProfileResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getUserProfilesByPageId(
        next,
        region,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['IdentityApi.getUserProfilesByPageId']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves User\'s data based on specified query filters.
     * @summary Retrieve User\'s by query
     * @param {UserProfileRequestBody} userProfileRequestBody
     * @param {string} [region] The region to filter results by.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async queryUserProfiles(
      userProfileRequestBody: UserProfileRequestBody,
      region?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserProfileScrollResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.queryUserProfiles(
        userProfileRequestBody,
        region,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['IdentityApi.queryUserProfiles']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * IdentityApi - factory interface
 * @export
 */
export const IdentityApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = IdentityApiFp(configuration);
  return {
    /**
     * Retrieves User\'s data using the specified pagination parameters.
     * @summary Retrieve User\'s by pagination
     * @param {IdentityApiGetUserProfilesByPageIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserProfilesByPageId(
      requestParameters: IdentityApiGetUserProfilesByPageIdRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserProfileResponse> {
      return localVarFp
        .getUserProfilesByPageId(requestParameters.next, requestParameters.region, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves User\'s data based on specified query filters.
     * @summary Retrieve User\'s by query
     * @param {IdentityApiQueryUserProfilesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    queryUserProfiles(
      requestParameters: IdentityApiQueryUserProfilesRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserProfileScrollResponse> {
      return localVarFp
        .queryUserProfiles(
          requestParameters.userProfileRequestBody,
          requestParameters.region,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * IdentityApi - interface
 * @export
 * @interface IdentityApi
 */
export interface IdentityApiInterface {
  /**
   * Retrieves User\'s data using the specified pagination parameters.
   * @summary Retrieve User\'s by pagination
   * @param {IdentityApiGetUserProfilesByPageIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IdentityApiInterface
   */
  getUserProfilesByPageId(
    requestParameters?: IdentityApiGetUserProfilesByPageIdRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<UserProfileResponse>;

  /**
   * Retrieves User\'s data based on specified query filters.
   * @summary Retrieve User\'s by query
   * @param {IdentityApiQueryUserProfilesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IdentityApiInterface
   */
  queryUserProfiles(
    requestParameters: IdentityApiQueryUserProfilesRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<UserProfileScrollResponse>;
}

/**
 * Request parameters for getUserProfilesByPageId operation in IdentityApi.
 * @export
 * @interface IdentityApiGetUserProfilesByPageIdRequest
 */
export interface IdentityApiGetUserProfilesByPageIdRequest {
  /**
   * Scroll or pagination token for fetching the next set of results. This token is used to retrieve the next page of results in a paginated response. If not provided, the API will return the first page of results.
   * @type {string}
   * @memberof IdentityApiGetUserProfilesByPageId
   */
  readonly next?: string;

  /**
   * The region to filter results by.
   * @type {string}
   * @memberof IdentityApiGetUserProfilesByPageId
   */
  readonly region?: string;
}

/**
 * Request parameters for queryUserProfiles operation in IdentityApi.
 * @export
 * @interface IdentityApiQueryUserProfilesRequest
 */
export interface IdentityApiQueryUserProfilesRequest {
  /**
   *
   * @type {UserProfileRequestBody}
   * @memberof IdentityApiQueryUserProfiles
   */
  readonly userProfileRequestBody: UserProfileRequestBody;

  /**
   * The region to filter results by.
   * @type {string}
   * @memberof IdentityApiQueryUserProfiles
   */
  readonly region?: string;
}

/**
 * IdentityApi - object-oriented interface
 * @export
 * @class IdentityApi
 * @extends {BaseAPI}
 */
export class IdentityApi extends BaseAPI implements IdentityApiInterface {
  /**
   * Retrieves User\'s data using the specified pagination parameters.
   * @summary Retrieve User\'s by pagination
   * @param {IdentityApiGetUserProfilesByPageIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IdentityApi
   */
  public getUserProfilesByPageId(
    requestParameters: IdentityApiGetUserProfilesByPageIdRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return IdentityApiFp(this.configuration)
      .getUserProfilesByPageId(requestParameters.next, requestParameters.region, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves User\'s data based on specified query filters.
   * @summary Retrieve User\'s by query
   * @param {IdentityApiQueryUserProfilesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IdentityApi
   */
  public queryUserProfiles(
    requestParameters: IdentityApiQueryUserProfilesRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return IdentityApiFp(this.configuration)
      .queryUserProfiles(
        requestParameters.userProfileRequestBody,
        requestParameters.region,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
