/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { CreateOAuthClientConfigurationRequest } from '../model';
// @ts-ignore
import type { DeleteResponse } from '../model';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { GetAllOAuthClientsConfigurations200Response } from '../model';
// @ts-ignore
import type { GetOAuthClientConnectionsMetadata200Response } from '../model';
// @ts-ignore
import type { OAuthClientRequest } from '../model';
// @ts-ignore
import type { OAuthClientResponse } from '../model';
// @ts-ignore
import type { OAuthClientSecretResetResponse } from '../model';
/**
 * OAuthClientsApi - axios parameter creator
 * @export
 */
export const OAuthClientsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a new OAuth client configuration for the Tenant by specifying redirect URIs, scopes, and other necessary settings to enable OAuth authentication and authorization.
     * @summary Create OAuth client
     * @param {CreateOAuthClientConfigurationRequest} createOAuthClientConfigurationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createOAuthClientConfiguration: async (
      createOAuthClientConfigurationRequest: CreateOAuthClientConfigurationRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createOAuthClientConfigurationRequest' is not null or undefined
      assertParamExists(
        'createOAuthClientConfiguration',
        'createOAuthClientConfigurationRequest',
        createOAuthClientConfigurationRequest,
      );
      const localVarPath = `/v2/manage/oauth-clients`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createOAuthClientConfigurationRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes the OAuth client configuration for the Tenant identified by the application name.
     * @summary Delete OAuth Client Configuration
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOAuthClient: async (
      oAuthClientName: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'oAuthClientName' is not null or undefined
      assertParamExists('deleteOAuthClient', 'oAuthClientName', oAuthClientName);
      const localVarPath = `/v2/manage/oauth-clients/{oAuthClientName}`.replace(
        `{${'oAuthClientName'}}`,
        encodeURIComponent(String(oAuthClientName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves a comprehensive list of OAuth client configurations for the Tenant, including client IDs, redirect URIs, scopes, and other relevant settings.
     * @summary List OAuth clients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllOAuthClientsConfigurations: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/oauth-clients`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves the OAuth client configuration details for the Tenant using the application name.
     * @summary Retrieve OAuth Client Configuration
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOAuthClientConfigurationByAppName: async (
      oAuthClientName: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'oAuthClientName' is not null or undefined
      assertParamExists('getOAuthClientConfigurationByAppName', 'oAuthClientName', oAuthClientName);
      const localVarPath = `/v2/manage/oauth-clients/{oAuthClientName}`.replace(
        `{${'oAuthClientName'}}`,
        encodeURIComponent(String(oAuthClientName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves metadata for OAuth client connections within the Tenant.
     * @summary Retrieve OAuth Client Metadata
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOAuthClientConnectionsMetadata: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/oauth-clients/connections-metadata`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Resets the client secret for the OAuth client configuration identified by the AppName within the Tenant, generating a new client secret and invalidating the previous one to enhance security.
     * @summary Reset OAuth client secret
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resetOAuthClientConfigurationSecretByAppName: async (
      oAuthClientName: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'oAuthClientName' is not null or undefined
      assertParamExists(
        'resetOAuthClientConfigurationSecretByAppName',
        'oAuthClientName',
        oAuthClientName,
      );
      const localVarPath = `/v2/manage/oauth-clients/credentials/{oAuthClientName}`.replace(
        `{${'oAuthClientName'}}`,
        encodeURIComponent(String(oAuthClientName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates the OAuth client configuration for the Tenant identified by the application name.
     * @summary Update OAuth Client Configuration
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {OAuthClientRequest} oAuthClientRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOAuthClientConfigurationByAppName: async (
      oAuthClientName: string,
      oAuthClientRequest: OAuthClientRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'oAuthClientName' is not null or undefined
      assertParamExists(
        'updateOAuthClientConfigurationByAppName',
        'oAuthClientName',
        oAuthClientName,
      );
      // verify required parameter 'oAuthClientRequest' is not null or undefined
      assertParamExists(
        'updateOAuthClientConfigurationByAppName',
        'oAuthClientRequest',
        oAuthClientRequest,
      );
      const localVarPath = `/v2/manage/oauth-clients/{oAuthClientName}`.replace(
        `{${'oAuthClientName'}}`,
        encodeURIComponent(String(oAuthClientName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        oAuthClientRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * OAuthClientsApi - functional programming interface
 * @export
 */
export const OAuthClientsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = OAuthClientsApiAxiosParamCreator(configuration);
  return {
    /**
     * Creates a new OAuth client configuration for the Tenant by specifying redirect URIs, scopes, and other necessary settings to enable OAuth authentication and authorization.
     * @summary Create OAuth client
     * @param {CreateOAuthClientConfigurationRequest} createOAuthClientConfigurationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createOAuthClientConfiguration(
      createOAuthClientConfigurationRequest: CreateOAuthClientConfigurationRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuthClientResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createOAuthClientConfiguration(
        createOAuthClientConfigurationRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.createOAuthClientConfiguration']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes the OAuth client configuration for the Tenant identified by the application name.
     * @summary Delete OAuth Client Configuration
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteOAuthClient(
      oAuthClientName: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOAuthClient(
        oAuthClientName,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.deleteOAuthClient']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves a comprehensive list of OAuth client configurations for the Tenant, including client IDs, redirect URIs, scopes, and other relevant settings.
     * @summary List OAuth clients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllOAuthClientsConfigurations(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetAllOAuthClientsConfigurations200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAllOAuthClientsConfigurations(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.getAllOAuthClientsConfigurations']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves the OAuth client configuration details for the Tenant using the application name.
     * @summary Retrieve OAuth Client Configuration
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getOAuthClientConfigurationByAppName(
      oAuthClientName: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuthClientResponse>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getOAuthClientConfigurationByAppName(
          oAuthClientName,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.getOAuthClientConfigurationByAppName']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves metadata for OAuth client connections within the Tenant.
     * @summary Retrieve OAuth Client Metadata
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getOAuthClientConnectionsMetadata(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetOAuthClientConnectionsMetadata200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getOAuthClientConnectionsMetadata(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.getOAuthClientConnectionsMetadata']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Resets the client secret for the OAuth client configuration identified by the AppName within the Tenant, generating a new client secret and invalidating the previous one to enhance security.
     * @summary Reset OAuth client secret
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async resetOAuthClientConfigurationSecretByAppName(
      oAuthClientName: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuthClientSecretResetResponse>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.resetOAuthClientConfigurationSecretByAppName(
          oAuthClientName,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.resetOAuthClientConfigurationSecretByAppName']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Updates the OAuth client configuration for the Tenant identified by the application name.
     * @summary Update OAuth Client Configuration
     * @param {string} oAuthClientName Name of the OAuth Client
     * @param {OAuthClientRequest} oAuthClientRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateOAuthClientConfigurationByAppName(
      oAuthClientName: string,
      oAuthClientRequest: OAuthClientRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuthClientResponse>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateOAuthClientConfigurationByAppName(
          oAuthClientName,
          oAuthClientRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OAuthClientsApi.updateOAuthClientConfigurationByAppName']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * OAuthClientsApi - factory interface
 * @export
 */
export const OAuthClientsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = OAuthClientsApiFp(configuration);
  return {
    /**
     * Creates a new OAuth client configuration for the Tenant by specifying redirect URIs, scopes, and other necessary settings to enable OAuth authentication and authorization.
     * @summary Create OAuth client
     * @param {OAuthClientsApiCreateOAuthClientConfigurationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createOAuthClientConfiguration(
      requestParameters: OAuthClientsApiCreateOAuthClientConfigurationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<OAuthClientResponse> {
      return localVarFp
        .createOAuthClientConfiguration(
          requestParameters.createOAuthClientConfigurationRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes the OAuth client configuration for the Tenant identified by the application name.
     * @summary Delete OAuth Client Configuration
     * @param {OAuthClientsApiDeleteOAuthClientRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOAuthClient(
      requestParameters: OAuthClientsApiDeleteOAuthClientRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<DeleteResponse> {
      return localVarFp
        .deleteOAuthClient(requestParameters.oAuthClientName, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves a comprehensive list of OAuth client configurations for the Tenant, including client IDs, redirect URIs, scopes, and other relevant settings.
     * @summary List OAuth clients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllOAuthClientsConfigurations(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetAllOAuthClientsConfigurations200Response> {
      return localVarFp
        .getAllOAuthClientsConfigurations(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves the OAuth client configuration details for the Tenant using the application name.
     * @summary Retrieve OAuth Client Configuration
     * @param {OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOAuthClientConfigurationByAppName(
      requestParameters: OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<OAuthClientResponse> {
      return localVarFp
        .getOAuthClientConfigurationByAppName(requestParameters.oAuthClientName, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves metadata for OAuth client connections within the Tenant.
     * @summary Retrieve OAuth Client Metadata
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOAuthClientConnectionsMetadata(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetOAuthClientConnectionsMetadata200Response> {
      return localVarFp
        .getOAuthClientConnectionsMetadata(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Resets the client secret for the OAuth client configuration identified by the AppName within the Tenant, generating a new client secret and invalidating the previous one to enhance security.
     * @summary Reset OAuth client secret
     * @param {OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resetOAuthClientConfigurationSecretByAppName(
      requestParameters: OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<OAuthClientSecretResetResponse> {
      return localVarFp
        .resetOAuthClientConfigurationSecretByAppName(requestParameters.oAuthClientName, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Updates the OAuth client configuration for the Tenant identified by the application name.
     * @summary Update OAuth Client Configuration
     * @param {OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOAuthClientConfigurationByAppName(
      requestParameters: OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<OAuthClientResponse> {
      return localVarFp
        .updateOAuthClientConfigurationByAppName(
          requestParameters.oAuthClientName,
          requestParameters.oAuthClientRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * OAuthClientsApi - interface
 * @export
 * @interface OAuthClientsApi
 */
export interface OAuthClientsApiInterface {
  /**
   * Creates a new OAuth client configuration for the Tenant by specifying redirect URIs, scopes, and other necessary settings to enable OAuth authentication and authorization.
   * @summary Create OAuth client
   * @param {OAuthClientsApiCreateOAuthClientConfigurationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  createOAuthClientConfiguration(
    requestParameters: OAuthClientsApiCreateOAuthClientConfigurationRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<OAuthClientResponse>;

  /**
   * Deletes the OAuth client configuration for the Tenant identified by the application name.
   * @summary Delete OAuth Client Configuration
   * @param {OAuthClientsApiDeleteOAuthClientRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  deleteOAuthClient(
    requestParameters: OAuthClientsApiDeleteOAuthClientRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<DeleteResponse>;

  /**
   * Retrieves a comprehensive list of OAuth client configurations for the Tenant, including client IDs, redirect URIs, scopes, and other relevant settings.
   * @summary List OAuth clients
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  getAllOAuthClientsConfigurations(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetAllOAuthClientsConfigurations200Response>;

  /**
   * Retrieves the OAuth client configuration details for the Tenant using the application name.
   * @summary Retrieve OAuth Client Configuration
   * @param {OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  getOAuthClientConfigurationByAppName(
    requestParameters: OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<OAuthClientResponse>;

  /**
   * Retrieves metadata for OAuth client connections within the Tenant.
   * @summary Retrieve OAuth Client Metadata
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  getOAuthClientConnectionsMetadata(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetOAuthClientConnectionsMetadata200Response>;

  /**
   * Resets the client secret for the OAuth client configuration identified by the AppName within the Tenant, generating a new client secret and invalidating the previous one to enhance security.
   * @summary Reset OAuth client secret
   * @param {OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  resetOAuthClientConfigurationSecretByAppName(
    requestParameters: OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<OAuthClientSecretResetResponse>;

  /**
   * Updates the OAuth client configuration for the Tenant identified by the application name.
   * @summary Update OAuth Client Configuration
   * @param {OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApiInterface
   */
  updateOAuthClientConfigurationByAppName(
    requestParameters: OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<OAuthClientResponse>;
}

/**
 * Request parameters for createOAuthClientConfiguration operation in OAuthClientsApi.
 * @export
 * @interface OAuthClientsApiCreateOAuthClientConfigurationRequest
 */
export interface OAuthClientsApiCreateOAuthClientConfigurationRequest {
  /**
   *
   * @type {CreateOAuthClientConfigurationRequest}
   * @memberof OAuthClientsApiCreateOAuthClientConfiguration
   */
  readonly createOAuthClientConfigurationRequest: CreateOAuthClientConfigurationRequest;
}

/**
 * Request parameters for deleteOAuthClient operation in OAuthClientsApi.
 * @export
 * @interface OAuthClientsApiDeleteOAuthClientRequest
 */
export interface OAuthClientsApiDeleteOAuthClientRequest {
  /**
   * Name of the OAuth Client
   * @type {string}
   * @memberof OAuthClientsApiDeleteOAuthClient
   */
  readonly oAuthClientName: string;
}

/**
 * Request parameters for getOAuthClientConfigurationByAppName operation in OAuthClientsApi.
 * @export
 * @interface OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest
 */
export interface OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest {
  /**
   * Name of the OAuth Client
   * @type {string}
   * @memberof OAuthClientsApiGetOAuthClientConfigurationByAppName
   */
  readonly oAuthClientName: string;
}

/**
 * Request parameters for resetOAuthClientConfigurationSecretByAppName operation in OAuthClientsApi.
 * @export
 * @interface OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest
 */
export interface OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest {
  /**
   * Name of the OAuth Client
   * @type {string}
   * @memberof OAuthClientsApiResetOAuthClientConfigurationSecretByAppName
   */
  readonly oAuthClientName: string;
}

/**
 * Request parameters for updateOAuthClientConfigurationByAppName operation in OAuthClientsApi.
 * @export
 * @interface OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest
 */
export interface OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest {
  /**
   * Name of the OAuth Client
   * @type {string}
   * @memberof OAuthClientsApiUpdateOAuthClientConfigurationByAppName
   */
  readonly oAuthClientName: string;

  /**
   *
   * @type {OAuthClientRequest}
   * @memberof OAuthClientsApiUpdateOAuthClientConfigurationByAppName
   */
  readonly oAuthClientRequest: OAuthClientRequest;
}

/**
 * OAuthClientsApi - object-oriented interface
 * @export
 * @class OAuthClientsApi
 * @extends {BaseAPI}
 */
export class OAuthClientsApi extends BaseAPI implements OAuthClientsApiInterface {
  /**
   * Creates a new OAuth client configuration for the Tenant by specifying redirect URIs, scopes, and other necessary settings to enable OAuth authentication and authorization.
   * @summary Create OAuth client
   * @param {OAuthClientsApiCreateOAuthClientConfigurationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public createOAuthClientConfiguration(
    requestParameters: OAuthClientsApiCreateOAuthClientConfigurationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return OAuthClientsApiFp(this.configuration)
      .createOAuthClientConfiguration(
        requestParameters.createOAuthClientConfigurationRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes the OAuth client configuration for the Tenant identified by the application name.
   * @summary Delete OAuth Client Configuration
   * @param {OAuthClientsApiDeleteOAuthClientRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public deleteOAuthClient(
    requestParameters: OAuthClientsApiDeleteOAuthClientRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return OAuthClientsApiFp(this.configuration)
      .deleteOAuthClient(requestParameters.oAuthClientName, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves a comprehensive list of OAuth client configurations for the Tenant, including client IDs, redirect URIs, scopes, and other relevant settings.
   * @summary List OAuth clients
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public getAllOAuthClientsConfigurations(options?: RawAxiosRequestConfig) {
    return OAuthClientsApiFp(this.configuration)
      .getAllOAuthClientsConfigurations(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves the OAuth client configuration details for the Tenant using the application name.
   * @summary Retrieve OAuth Client Configuration
   * @param {OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public getOAuthClientConfigurationByAppName(
    requestParameters: OAuthClientsApiGetOAuthClientConfigurationByAppNameRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return OAuthClientsApiFp(this.configuration)
      .getOAuthClientConfigurationByAppName(requestParameters.oAuthClientName, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves metadata for OAuth client connections within the Tenant.
   * @summary Retrieve OAuth Client Metadata
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public getOAuthClientConnectionsMetadata(options?: RawAxiosRequestConfig) {
    return OAuthClientsApiFp(this.configuration)
      .getOAuthClientConnectionsMetadata(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Resets the client secret for the OAuth client configuration identified by the AppName within the Tenant, generating a new client secret and invalidating the previous one to enhance security.
   * @summary Reset OAuth client secret
   * @param {OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public resetOAuthClientConfigurationSecretByAppName(
    requestParameters: OAuthClientsApiResetOAuthClientConfigurationSecretByAppNameRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return OAuthClientsApiFp(this.configuration)
      .resetOAuthClientConfigurationSecretByAppName(requestParameters.oAuthClientName, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates the OAuth client configuration for the Tenant identified by the application name.
   * @summary Update OAuth Client Configuration
   * @param {OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OAuthClientsApi
   */
  public updateOAuthClientConfigurationByAppName(
    requestParameters: OAuthClientsApiUpdateOAuthClientConfigurationByAppNameRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return OAuthClientsApiFp(this.configuration)
      .updateOAuthClientConfigurationByAppName(
        requestParameters.oAuthClientName,
        requestParameters.oAuthClientRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
