/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { PassKeyConfig } from '../model';
/**
 * PasskeyConfigurationApi - axios parameter creator
 * @export
 */
export const PasskeyConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Retrieves the current Passkey configuration settings for the Tenant.
     * @summary Retrieve Passkey configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPassKeyConfig: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/passkey`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Creates or updates the Passkey configuration settings for the Tenant.
     * @summary Update Passkey configuration
     * @param {PassKeyConfig} passKeyConfig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    upsertPassKeyConfig: async (
      passKeyConfig: PassKeyConfig,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'passKeyConfig' is not null or undefined
      assertParamExists('upsertPassKeyConfig', 'passKeyConfig', passKeyConfig);
      const localVarPath = `/v2/manage/passkey`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        passKeyConfig,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PasskeyConfigurationApi - functional programming interface
 * @export
 */
export const PasskeyConfigurationApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PasskeyConfigurationApiAxiosParamCreator(configuration);
  return {
    /**
     * Retrieves the current Passkey configuration settings for the Tenant.
     * @summary Retrieve Passkey configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPassKeyConfig(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PassKeyConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPassKeyConfig(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PasskeyConfigurationApi.getPassKeyConfig']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Creates or updates the Passkey configuration settings for the Tenant.
     * @summary Update Passkey configuration
     * @param {PassKeyConfig} passKeyConfig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async upsertPassKeyConfig(
      passKeyConfig: PassKeyConfig,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PassKeyConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.upsertPassKeyConfig(
        passKeyConfig,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PasskeyConfigurationApi.upsertPassKeyConfig']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PasskeyConfigurationApi - factory interface
 * @export
 */
export const PasskeyConfigurationApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PasskeyConfigurationApiFp(configuration);
  return {
    /**
     * Retrieves the current Passkey configuration settings for the Tenant.
     * @summary Retrieve Passkey configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPassKeyConfig(options?: RawAxiosRequestConfig): AxiosPromise<PassKeyConfig> {
      return localVarFp.getPassKeyConfig(options).then((request) => request(axios, basePath));
    },
    /**
     * Creates or updates the Passkey configuration settings for the Tenant.
     * @summary Update Passkey configuration
     * @param {PasskeyConfigurationApiUpsertPassKeyConfigRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    upsertPassKeyConfig(
      requestParameters: PasskeyConfigurationApiUpsertPassKeyConfigRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PassKeyConfig> {
      return localVarFp
        .upsertPassKeyConfig(requestParameters.passKeyConfig, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PasskeyConfigurationApi - interface
 * @export
 * @interface PasskeyConfigurationApi
 */
export interface PasskeyConfigurationApiInterface {
  /**
   * Retrieves the current Passkey configuration settings for the Tenant.
   * @summary Retrieve Passkey configuration
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PasskeyConfigurationApiInterface
   */
  getPassKeyConfig(options?: RawAxiosRequestConfig): AxiosPromise<PassKeyConfig>;

  /**
   * Creates or updates the Passkey configuration settings for the Tenant.
   * @summary Update Passkey configuration
   * @param {PasskeyConfigurationApiUpsertPassKeyConfigRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PasskeyConfigurationApiInterface
   */
  upsertPassKeyConfig(
    requestParameters: PasskeyConfigurationApiUpsertPassKeyConfigRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PassKeyConfig>;
}

/**
 * Request parameters for upsertPassKeyConfig operation in PasskeyConfigurationApi.
 * @export
 * @interface PasskeyConfigurationApiUpsertPassKeyConfigRequest
 */
export interface PasskeyConfigurationApiUpsertPassKeyConfigRequest {
  /**
   *
   * @type {PassKeyConfig}
   * @memberof PasskeyConfigurationApiUpsertPassKeyConfig
   */
  readonly passKeyConfig: PassKeyConfig;
}

/**
 * PasskeyConfigurationApi - object-oriented interface
 * @export
 * @class PasskeyConfigurationApi
 * @extends {BaseAPI}
 */
export class PasskeyConfigurationApi extends BaseAPI implements PasskeyConfigurationApiInterface {
  /**
   * Retrieves the current Passkey configuration settings for the Tenant.
   * @summary Retrieve Passkey configuration
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PasskeyConfigurationApi
   */
  public getPassKeyConfig(options?: RawAxiosRequestConfig) {
    return PasskeyConfigurationApiFp(this.configuration)
      .getPassKeyConfig(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Creates or updates the Passkey configuration settings for the Tenant.
   * @summary Update Passkey configuration
   * @param {PasskeyConfigurationApiUpsertPassKeyConfigRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PasskeyConfigurationApi
   */
  public upsertPassKeyConfig(
    requestParameters: PasskeyConfigurationApiUpsertPassKeyConfigRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PasskeyConfigurationApiFp(this.configuration)
      .upsertPassKeyConfig(requestParameters.passKeyConfig, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
