/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { PerfectMindContactResponse } from '../model';
// @ts-ignore
import type { PerfectMindSessionResponse } from '../model';
/**
 * PerfectMindSSOApi - axios parameter creator
 * @export
 */
export const PerfectMindSSOApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Retrieves PerfectMind contact IDs associated with the user\'s email address. Uses the LoginRadius access token to look up the user and match them against PerfectMind contacts using email and birth date.
     * @summary Get PerfectMind Contact IDs
     * @param {string} accessToken Access Token of the User
     * @param {string} perfectmindsitename PerfectMind site name identifier
     * @param {string} [birthdate] User\&#39;s birth date for PerfectMind contact lookup
     * @param {string} [perfectScanID] PerfectMind scan ID for contact lookup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPerfectMindContact: async (
      accessToken: string,
      perfectmindsitename: string,
      birthdate?: string,
      perfectScanID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'accessToken' is not null or undefined
      assertParamExists('getPerfectMindContact', 'accessToken', accessToken);
      // verify required parameter 'perfectmindsitename' is not null or undefined
      assertParamExists('getPerfectMindContact', 'perfectmindsitename', perfectmindsitename);
      const localVarPath = `/sso/perfectmind/contact`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication APIKey required
      await setApiKeyToObject(localVarQueryParameter, 'apikey', configuration);

      // authentication XLoginRadiusAPIKey required
      await setApiKeyToObject(localVarHeaderParameter, 'X-LoginRadius-ApiKey', configuration);

      if (accessToken !== undefined) {
        localVarQueryParameter['access_token'] = accessToken;
      }

      if (perfectmindsitename !== undefined) {
        localVarQueryParameter['perfectmindsitename'] = perfectmindsitename;
      }

      if (birthdate !== undefined) {
        localVarQueryParameter['birthdate'] = birthdate;
      }

      if (perfectScanID !== undefined) {
        localVarQueryParameter['perfectScanID'] = perfectScanID;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Generates a PerfectMind login session using the provided LoginRadius access token. Returns a session ID and URL that can be used to authenticate the user into the PerfectMind platform.
     * @summary Generate PerfectMind Login Session
     * @param {string} accessToken Access Token of the User
     * @param {string} perfectmindsitename PerfectMind site name identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPerfectMindSession: async (
      accessToken: string,
      perfectmindsitename: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'accessToken' is not null or undefined
      assertParamExists('getPerfectMindSession', 'accessToken', accessToken);
      // verify required parameter 'perfectmindsitename' is not null or undefined
      assertParamExists('getPerfectMindSession', 'perfectmindsitename', perfectmindsitename);
      const localVarPath = `/sso/perfectmind/session`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication APIKey required
      await setApiKeyToObject(localVarQueryParameter, 'apikey', configuration);

      // authentication XLoginRadiusAPIKey required
      await setApiKeyToObject(localVarHeaderParameter, 'X-LoginRadius-ApiKey', configuration);

      if (accessToken !== undefined) {
        localVarQueryParameter['access_token'] = accessToken;
      }

      if (perfectmindsitename !== undefined) {
        localVarQueryParameter['perfectmindsitename'] = perfectmindsitename;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PerfectMindSSOApi - functional programming interface
 * @export
 */
export const PerfectMindSSOApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PerfectMindSSOApiAxiosParamCreator(configuration);
  return {
    /**
     * Retrieves PerfectMind contact IDs associated with the user\'s email address. Uses the LoginRadius access token to look up the user and match them against PerfectMind contacts using email and birth date.
     * @summary Get PerfectMind Contact IDs
     * @param {string} accessToken Access Token of the User
     * @param {string} perfectmindsitename PerfectMind site name identifier
     * @param {string} [birthdate] User\&#39;s birth date for PerfectMind contact lookup
     * @param {string} [perfectScanID] PerfectMind scan ID for contact lookup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPerfectMindContact(
      accessToken: string,
      perfectmindsitename: string,
      birthdate?: string,
      perfectScanID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PerfectMindContactResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPerfectMindContact(
        accessToken,
        perfectmindsitename,
        birthdate,
        perfectScanID,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PerfectMindSSOApi.getPerfectMindContact']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Generates a PerfectMind login session using the provided LoginRadius access token. Returns a session ID and URL that can be used to authenticate the user into the PerfectMind platform.
     * @summary Generate PerfectMind Login Session
     * @param {string} accessToken Access Token of the User
     * @param {string} perfectmindsitename PerfectMind site name identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPerfectMindSession(
      accessToken: string,
      perfectmindsitename: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PerfectMindSessionResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPerfectMindSession(
        accessToken,
        perfectmindsitename,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PerfectMindSSOApi.getPerfectMindSession']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PerfectMindSSOApi - factory interface
 * @export
 */
export const PerfectMindSSOApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PerfectMindSSOApiFp(configuration);
  return {
    /**
     * Retrieves PerfectMind contact IDs associated with the user\'s email address. Uses the LoginRadius access token to look up the user and match them against PerfectMind contacts using email and birth date.
     * @summary Get PerfectMind Contact IDs
     * @param {PerfectMindSSOApiGetPerfectMindContactRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPerfectMindContact(
      requestParameters: PerfectMindSSOApiGetPerfectMindContactRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PerfectMindContactResponse> {
      return localVarFp
        .getPerfectMindContact(
          requestParameters.accessToken,
          requestParameters.perfectmindsitename,
          requestParameters.birthdate,
          requestParameters.perfectScanID,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Generates a PerfectMind login session using the provided LoginRadius access token. Returns a session ID and URL that can be used to authenticate the user into the PerfectMind platform.
     * @summary Generate PerfectMind Login Session
     * @param {PerfectMindSSOApiGetPerfectMindSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPerfectMindSession(
      requestParameters: PerfectMindSSOApiGetPerfectMindSessionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PerfectMindSessionResponse> {
      return localVarFp
        .getPerfectMindSession(
          requestParameters.accessToken,
          requestParameters.perfectmindsitename,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PerfectMindSSOApi - interface
 * @export
 * @interface PerfectMindSSOApi
 */
export interface PerfectMindSSOApiInterface {
  /**
   * Retrieves PerfectMind contact IDs associated with the user\'s email address. Uses the LoginRadius access token to look up the user and match them against PerfectMind contacts using email and birth date.
   * @summary Get PerfectMind Contact IDs
   * @param {PerfectMindSSOApiGetPerfectMindContactRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PerfectMindSSOApiInterface
   */
  getPerfectMindContact(
    requestParameters: PerfectMindSSOApiGetPerfectMindContactRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PerfectMindContactResponse>;

  /**
   * Generates a PerfectMind login session using the provided LoginRadius access token. Returns a session ID and URL that can be used to authenticate the user into the PerfectMind platform.
   * @summary Generate PerfectMind Login Session
   * @param {PerfectMindSSOApiGetPerfectMindSessionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PerfectMindSSOApiInterface
   */
  getPerfectMindSession(
    requestParameters: PerfectMindSSOApiGetPerfectMindSessionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PerfectMindSessionResponse>;
}

/**
 * Request parameters for getPerfectMindContact operation in PerfectMindSSOApi.
 * @export
 * @interface PerfectMindSSOApiGetPerfectMindContactRequest
 */
export interface PerfectMindSSOApiGetPerfectMindContactRequest {
  /**
   * Access Token of the User
   * @type {string}
   * @memberof PerfectMindSSOApiGetPerfectMindContact
   */
  readonly accessToken: string;

  /**
   * PerfectMind site name identifier
   * @type {string}
   * @memberof PerfectMindSSOApiGetPerfectMindContact
   */
  readonly perfectmindsitename: string;

  /**
   * User\&#39;s birth date for PerfectMind contact lookup
   * @type {string}
   * @memberof PerfectMindSSOApiGetPerfectMindContact
   */
  readonly birthdate?: string;

  /**
   * PerfectMind scan ID for contact lookup
   * @type {string}
   * @memberof PerfectMindSSOApiGetPerfectMindContact
   */
  readonly perfectScanID?: string;
}

/**
 * Request parameters for getPerfectMindSession operation in PerfectMindSSOApi.
 * @export
 * @interface PerfectMindSSOApiGetPerfectMindSessionRequest
 */
export interface PerfectMindSSOApiGetPerfectMindSessionRequest {
  /**
   * Access Token of the User
   * @type {string}
   * @memberof PerfectMindSSOApiGetPerfectMindSession
   */
  readonly accessToken: string;

  /**
   * PerfectMind site name identifier
   * @type {string}
   * @memberof PerfectMindSSOApiGetPerfectMindSession
   */
  readonly perfectmindsitename: string;
}

/**
 * PerfectMindSSOApi - object-oriented interface
 * @export
 * @class PerfectMindSSOApi
 * @extends {BaseAPI}
 */
export class PerfectMindSSOApi extends BaseAPI implements PerfectMindSSOApiInterface {
  /**
   * Retrieves PerfectMind contact IDs associated with the user\'s email address. Uses the LoginRadius access token to look up the user and match them against PerfectMind contacts using email and birth date.
   * @summary Get PerfectMind Contact IDs
   * @param {PerfectMindSSOApiGetPerfectMindContactRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PerfectMindSSOApi
   */
  public getPerfectMindContact(
    requestParameters: PerfectMindSSOApiGetPerfectMindContactRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PerfectMindSSOApiFp(this.configuration)
      .getPerfectMindContact(
        requestParameters.accessToken,
        requestParameters.perfectmindsitename,
        requestParameters.birthdate,
        requestParameters.perfectScanID,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Generates a PerfectMind login session using the provided LoginRadius access token. Returns a session ID and URL that can be used to authenticate the user into the PerfectMind platform.
   * @summary Generate PerfectMind Login Session
   * @param {PerfectMindSSOApiGetPerfectMindSessionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PerfectMindSSOApi
   */
  public getPerfectMindSession(
    requestParameters: PerfectMindSSOApiGetPerfectMindSessionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PerfectMindSSOApiFp(this.configuration)
      .getPerfectMindSession(
        requestParameters.accessToken,
        requestParameters.perfectmindsitename,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
