/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { PushAuthenticator } from '../model';
/**
 * PushNotificationConfigurationApi - axios parameter creator
 * @export
 */
export const PushNotificationConfigurationApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Creates new Push Notification settings for second factor authentication.
     * @summary Create Push Notification settings
     * @param {PushAuthenticator} pushAuthenticator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createPushSettings: async (
      pushAuthenticator: PushAuthenticator,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'pushAuthenticator' is not null or undefined
      assertParamExists('createPushSettings', 'pushAuthenticator', pushAuthenticator);
      const localVarPath = `/v2/manage/2fa/push-notification-settings`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        pushAuthenticator,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves the current Push Notification settings for second factor authentication.
     * @summary Retrieve Push Notification settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPushSettings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/2fa/push-notification-settings`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates existing Push Notification settings for second factor authentication.
     * @summary Update Push Notification settings
     * @param {PushAuthenticator} pushAuthenticator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatePushSettings: async (
      pushAuthenticator: PushAuthenticator,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'pushAuthenticator' is not null or undefined
      assertParamExists('updatePushSettings', 'pushAuthenticator', pushAuthenticator);
      const localVarPath = `/v2/manage/2fa/push-notification-settings`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        pushAuthenticator,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PushNotificationConfigurationApi - functional programming interface
 * @export
 */
export const PushNotificationConfigurationApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    PushNotificationConfigurationApiAxiosParamCreator(configuration);
  return {
    /**
     * Creates new Push Notification settings for second factor authentication.
     * @summary Create Push Notification settings
     * @param {PushAuthenticator} pushAuthenticator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createPushSettings(
      pushAuthenticator: PushAuthenticator,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PushAuthenticator>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createPushSettings(
        pushAuthenticator,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PushNotificationConfigurationApi.createPushSettings']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves the current Push Notification settings for second factor authentication.
     * @summary Retrieve Push Notification settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPushSettings(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PushAuthenticator>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPushSettings(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PushNotificationConfigurationApi.getPushSettings']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Updates existing Push Notification settings for second factor authentication.
     * @summary Update Push Notification settings
     * @param {PushAuthenticator} pushAuthenticator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updatePushSettings(
      pushAuthenticator: PushAuthenticator,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PushAuthenticator>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updatePushSettings(
        pushAuthenticator,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PushNotificationConfigurationApi.updatePushSettings']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PushNotificationConfigurationApi - factory interface
 * @export
 */
export const PushNotificationConfigurationApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PushNotificationConfigurationApiFp(configuration);
  return {
    /**
     * Creates new Push Notification settings for second factor authentication.
     * @summary Create Push Notification settings
     * @param {PushNotificationConfigurationApiCreatePushSettingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createPushSettings(
      requestParameters: PushNotificationConfigurationApiCreatePushSettingsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PushAuthenticator> {
      return localVarFp
        .createPushSettings(requestParameters.pushAuthenticator, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves the current Push Notification settings for second factor authentication.
     * @summary Retrieve Push Notification settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPushSettings(options?: RawAxiosRequestConfig): AxiosPromise<PushAuthenticator> {
      return localVarFp.getPushSettings(options).then((request) => request(axios, basePath));
    },
    /**
     * Updates existing Push Notification settings for second factor authentication.
     * @summary Update Push Notification settings
     * @param {PushNotificationConfigurationApiUpdatePushSettingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatePushSettings(
      requestParameters: PushNotificationConfigurationApiUpdatePushSettingsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PushAuthenticator> {
      return localVarFp
        .updatePushSettings(requestParameters.pushAuthenticator, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PushNotificationConfigurationApi - interface
 * @export
 * @interface PushNotificationConfigurationApi
 */
export interface PushNotificationConfigurationApiInterface {
  /**
   * Creates new Push Notification settings for second factor authentication.
   * @summary Create Push Notification settings
   * @param {PushNotificationConfigurationApiCreatePushSettingsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PushNotificationConfigurationApiInterface
   */
  createPushSettings(
    requestParameters: PushNotificationConfigurationApiCreatePushSettingsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PushAuthenticator>;

  /**
   * Retrieves the current Push Notification settings for second factor authentication.
   * @summary Retrieve Push Notification settings
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PushNotificationConfigurationApiInterface
   */
  getPushSettings(options?: RawAxiosRequestConfig): AxiosPromise<PushAuthenticator>;

  /**
   * Updates existing Push Notification settings for second factor authentication.
   * @summary Update Push Notification settings
   * @param {PushNotificationConfigurationApiUpdatePushSettingsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PushNotificationConfigurationApiInterface
   */
  updatePushSettings(
    requestParameters: PushNotificationConfigurationApiUpdatePushSettingsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PushAuthenticator>;
}

/**
 * Request parameters for createPushSettings operation in PushNotificationConfigurationApi.
 * @export
 * @interface PushNotificationConfigurationApiCreatePushSettingsRequest
 */
export interface PushNotificationConfigurationApiCreatePushSettingsRequest {
  /**
   *
   * @type {PushAuthenticator}
   * @memberof PushNotificationConfigurationApiCreatePushSettings
   */
  readonly pushAuthenticator: PushAuthenticator;
}

/**
 * Request parameters for updatePushSettings operation in PushNotificationConfigurationApi.
 * @export
 * @interface PushNotificationConfigurationApiUpdatePushSettingsRequest
 */
export interface PushNotificationConfigurationApiUpdatePushSettingsRequest {
  /**
   *
   * @type {PushAuthenticator}
   * @memberof PushNotificationConfigurationApiUpdatePushSettings
   */
  readonly pushAuthenticator: PushAuthenticator;
}

/**
 * PushNotificationConfigurationApi - object-oriented interface
 * @export
 * @class PushNotificationConfigurationApi
 * @extends {BaseAPI}
 */
export class PushNotificationConfigurationApi
  extends BaseAPI
  implements PushNotificationConfigurationApiInterface
{
  /**
   * Creates new Push Notification settings for second factor authentication.
   * @summary Create Push Notification settings
   * @param {PushNotificationConfigurationApiCreatePushSettingsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PushNotificationConfigurationApi
   */
  public createPushSettings(
    requestParameters: PushNotificationConfigurationApiCreatePushSettingsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PushNotificationConfigurationApiFp(this.configuration)
      .createPushSettings(requestParameters.pushAuthenticator, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves the current Push Notification settings for second factor authentication.
   * @summary Retrieve Push Notification settings
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PushNotificationConfigurationApi
   */
  public getPushSettings(options?: RawAxiosRequestConfig) {
    return PushNotificationConfigurationApiFp(this.configuration)
      .getPushSettings(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates existing Push Notification settings for second factor authentication.
   * @summary Update Push Notification settings
   * @param {PushNotificationConfigurationApiUpdatePushSettingsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PushNotificationConfigurationApi
   */
  public updatePushSettings(
    requestParameters: PushNotificationConfigurationApiUpdatePushSettingsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PushNotificationConfigurationApiFp(this.configuration)
      .updatePushSettings(requestParameters.pushAuthenticator, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
