/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { DeleteResponse } from '../model';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { GetSecurityQuestions200Response } from '../model';
// @ts-ignore
import type { SecurityQuestion } from '../model';
// @ts-ignore
import type { SecurityQuestionInput } from '../model';
// @ts-ignore
import type { SecurityQuestionsRender } from '../model';
/**
 * SecurityQuestionsApi - axios parameter creator
 * @export
 */
export const SecurityQuestionsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Adds a new security question to the Tenant\'s configuration.
     * @summary Add security question
     * @param {SecurityQuestionInput} securityQuestionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addSecurityQuestion: async (
      securityQuestionInput: SecurityQuestionInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'securityQuestionInput' is not null or undefined
      assertParamExists('addSecurityQuestion', 'securityQuestionInput', securityQuestionInput);
      const localVarPath = `/v2/manage/security-questions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        securityQuestionInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes a security question by its ID.
     * @summary Delete security question
     * @param {string} securityQuestionID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSecurityQuestion: async (
      securityQuestionID: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'securityQuestionID' is not null or undefined
      assertParamExists('deleteSecurityQuestion', 'securityQuestionID', securityQuestionID);
      const localVarPath = `/v2/manage/security-questions/{securityQuestionID}`.replace(
        `{${'securityQuestionID'}}`,
        encodeURIComponent(String(securityQuestionID)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves the number of security questions to render for a User.
     * @summary Retrieve security question count
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSecurityQuestionRenderCount: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/security-questions/count`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves a list of all available security questions for the Tenant.
     * @summary Retrieve security questions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSecurityQuestions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/security-questions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates an existing security question by its ID.
     * @summary Update security question
     * @param {string} securityQuestionID
     * @param {SecurityQuestionInput} securityQuestionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSecurityQuestion: async (
      securityQuestionID: string,
      securityQuestionInput: SecurityQuestionInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'securityQuestionID' is not null or undefined
      assertParamExists('updateSecurityQuestion', 'securityQuestionID', securityQuestionID);
      // verify required parameter 'securityQuestionInput' is not null or undefined
      assertParamExists('updateSecurityQuestion', 'securityQuestionInput', securityQuestionInput);
      const localVarPath = `/v2/manage/security-questions/{securityQuestionID}`.replace(
        `{${'securityQuestionID'}}`,
        encodeURIComponent(String(securityQuestionID)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        securityQuestionInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates the number of security questions to render for a User.
     * @summary Update security question count
     * @param {SecurityQuestionsRender} securityQuestionsRender
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSecurityQuestionRenderCount: async (
      securityQuestionsRender: SecurityQuestionsRender,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'securityQuestionsRender' is not null or undefined
      assertParamExists(
        'updateSecurityQuestionRenderCount',
        'securityQuestionsRender',
        securityQuestionsRender,
      );
      const localVarPath = `/v2/manage/security-questions/count`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        securityQuestionsRender,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * SecurityQuestionsApi - functional programming interface
 * @export
 */
export const SecurityQuestionsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SecurityQuestionsApiAxiosParamCreator(configuration);
  return {
    /**
     * Adds a new security question to the Tenant\'s configuration.
     * @summary Add security question
     * @param {SecurityQuestionInput} securityQuestionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addSecurityQuestion(
      securityQuestionInput: SecurityQuestionInput,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecurityQuestion>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addSecurityQuestion(
        securityQuestionInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SecurityQuestionsApi.addSecurityQuestion']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes a security question by its ID.
     * @summary Delete security question
     * @param {string} securityQuestionID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteSecurityQuestion(
      securityQuestionID: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSecurityQuestion(
        securityQuestionID,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SecurityQuestionsApi.deleteSecurityQuestion']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves the number of security questions to render for a User.
     * @summary Retrieve security question count
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSecurityQuestionRenderCount(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecurityQuestionsRender>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getSecurityQuestionRenderCount(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SecurityQuestionsApi.getSecurityQuestionRenderCount']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves a list of all available security questions for the Tenant.
     * @summary Retrieve security questions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSecurityQuestions(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSecurityQuestions200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getSecurityQuestions(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SecurityQuestionsApi.getSecurityQuestions']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Updates an existing security question by its ID.
     * @summary Update security question
     * @param {string} securityQuestionID
     * @param {SecurityQuestionInput} securityQuestionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateSecurityQuestion(
      securityQuestionID: string,
      securityQuestionInput: SecurityQuestionInput,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecurityQuestion>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateSecurityQuestion(
        securityQuestionID,
        securityQuestionInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SecurityQuestionsApi.updateSecurityQuestion']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Updates the number of security questions to render for a User.
     * @summary Update security question count
     * @param {SecurityQuestionsRender} securityQuestionsRender
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateSecurityQuestionRenderCount(
      securityQuestionsRender: SecurityQuestionsRender,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecurityQuestionsRender>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateSecurityQuestionRenderCount(
        securityQuestionsRender,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SecurityQuestionsApi.updateSecurityQuestionRenderCount']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * SecurityQuestionsApi - factory interface
 * @export
 */
export const SecurityQuestionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = SecurityQuestionsApiFp(configuration);
  return {
    /**
     * Adds a new security question to the Tenant\'s configuration.
     * @summary Add security question
     * @param {SecurityQuestionsApiAddSecurityQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addSecurityQuestion(
      requestParameters: SecurityQuestionsApiAddSecurityQuestionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SecurityQuestion> {
      return localVarFp
        .addSecurityQuestion(requestParameters.securityQuestionInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes a security question by its ID.
     * @summary Delete security question
     * @param {SecurityQuestionsApiDeleteSecurityQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSecurityQuestion(
      requestParameters: SecurityQuestionsApiDeleteSecurityQuestionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<DeleteResponse> {
      return localVarFp
        .deleteSecurityQuestion(requestParameters.securityQuestionID, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves the number of security questions to render for a User.
     * @summary Retrieve security question count
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSecurityQuestionRenderCount(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SecurityQuestionsRender> {
      return localVarFp
        .getSecurityQuestionRenderCount(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves a list of all available security questions for the Tenant.
     * @summary Retrieve security questions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSecurityQuestions(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetSecurityQuestions200Response> {
      return localVarFp.getSecurityQuestions(options).then((request) => request(axios, basePath));
    },
    /**
     * Updates an existing security question by its ID.
     * @summary Update security question
     * @param {SecurityQuestionsApiUpdateSecurityQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSecurityQuestion(
      requestParameters: SecurityQuestionsApiUpdateSecurityQuestionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SecurityQuestion> {
      return localVarFp
        .updateSecurityQuestion(
          requestParameters.securityQuestionID,
          requestParameters.securityQuestionInput,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Updates the number of security questions to render for a User.
     * @summary Update security question count
     * @param {SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSecurityQuestionRenderCount(
      requestParameters: SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SecurityQuestionsRender> {
      return localVarFp
        .updateSecurityQuestionRenderCount(requestParameters.securityQuestionsRender, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * SecurityQuestionsApi - interface
 * @export
 * @interface SecurityQuestionsApi
 */
export interface SecurityQuestionsApiInterface {
  /**
   * Adds a new security question to the Tenant\'s configuration.
   * @summary Add security question
   * @param {SecurityQuestionsApiAddSecurityQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApiInterface
   */
  addSecurityQuestion(
    requestParameters: SecurityQuestionsApiAddSecurityQuestionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SecurityQuestion>;

  /**
   * Deletes a security question by its ID.
   * @summary Delete security question
   * @param {SecurityQuestionsApiDeleteSecurityQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApiInterface
   */
  deleteSecurityQuestion(
    requestParameters: SecurityQuestionsApiDeleteSecurityQuestionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<DeleteResponse>;

  /**
   * Retrieves the number of security questions to render for a User.
   * @summary Retrieve security question count
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApiInterface
   */
  getSecurityQuestionRenderCount(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SecurityQuestionsRender>;

  /**
   * Retrieves a list of all available security questions for the Tenant.
   * @summary Retrieve security questions
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApiInterface
   */
  getSecurityQuestions(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetSecurityQuestions200Response>;

  /**
   * Updates an existing security question by its ID.
   * @summary Update security question
   * @param {SecurityQuestionsApiUpdateSecurityQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApiInterface
   */
  updateSecurityQuestion(
    requestParameters: SecurityQuestionsApiUpdateSecurityQuestionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SecurityQuestion>;

  /**
   * Updates the number of security questions to render for a User.
   * @summary Update security question count
   * @param {SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApiInterface
   */
  updateSecurityQuestionRenderCount(
    requestParameters: SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SecurityQuestionsRender>;
}

/**
 * Request parameters for addSecurityQuestion operation in SecurityQuestionsApi.
 * @export
 * @interface SecurityQuestionsApiAddSecurityQuestionRequest
 */
export interface SecurityQuestionsApiAddSecurityQuestionRequest {
  /**
   *
   * @type {SecurityQuestionInput}
   * @memberof SecurityQuestionsApiAddSecurityQuestion
   */
  readonly securityQuestionInput: SecurityQuestionInput;
}

/**
 * Request parameters for deleteSecurityQuestion operation in SecurityQuestionsApi.
 * @export
 * @interface SecurityQuestionsApiDeleteSecurityQuestionRequest
 */
export interface SecurityQuestionsApiDeleteSecurityQuestionRequest {
  /**
   *
   * @type {string}
   * @memberof SecurityQuestionsApiDeleteSecurityQuestion
   */
  readonly securityQuestionID: string;
}

/**
 * Request parameters for updateSecurityQuestion operation in SecurityQuestionsApi.
 * @export
 * @interface SecurityQuestionsApiUpdateSecurityQuestionRequest
 */
export interface SecurityQuestionsApiUpdateSecurityQuestionRequest {
  /**
   *
   * @type {string}
   * @memberof SecurityQuestionsApiUpdateSecurityQuestion
   */
  readonly securityQuestionID: string;

  /**
   *
   * @type {SecurityQuestionInput}
   * @memberof SecurityQuestionsApiUpdateSecurityQuestion
   */
  readonly securityQuestionInput: SecurityQuestionInput;
}

/**
 * Request parameters for updateSecurityQuestionRenderCount operation in SecurityQuestionsApi.
 * @export
 * @interface SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest
 */
export interface SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest {
  /**
   *
   * @type {SecurityQuestionsRender}
   * @memberof SecurityQuestionsApiUpdateSecurityQuestionRenderCount
   */
  readonly securityQuestionsRender: SecurityQuestionsRender;
}

/**
 * SecurityQuestionsApi - object-oriented interface
 * @export
 * @class SecurityQuestionsApi
 * @extends {BaseAPI}
 */
export class SecurityQuestionsApi extends BaseAPI implements SecurityQuestionsApiInterface {
  /**
   * Adds a new security question to the Tenant\'s configuration.
   * @summary Add security question
   * @param {SecurityQuestionsApiAddSecurityQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApi
   */
  public addSecurityQuestion(
    requestParameters: SecurityQuestionsApiAddSecurityQuestionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return SecurityQuestionsApiFp(this.configuration)
      .addSecurityQuestion(requestParameters.securityQuestionInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes a security question by its ID.
   * @summary Delete security question
   * @param {SecurityQuestionsApiDeleteSecurityQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApi
   */
  public deleteSecurityQuestion(
    requestParameters: SecurityQuestionsApiDeleteSecurityQuestionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return SecurityQuestionsApiFp(this.configuration)
      .deleteSecurityQuestion(requestParameters.securityQuestionID, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves the number of security questions to render for a User.
   * @summary Retrieve security question count
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApi
   */
  public getSecurityQuestionRenderCount(options?: RawAxiosRequestConfig) {
    return SecurityQuestionsApiFp(this.configuration)
      .getSecurityQuestionRenderCount(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves a list of all available security questions for the Tenant.
   * @summary Retrieve security questions
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApi
   */
  public getSecurityQuestions(options?: RawAxiosRequestConfig) {
    return SecurityQuestionsApiFp(this.configuration)
      .getSecurityQuestions(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates an existing security question by its ID.
   * @summary Update security question
   * @param {SecurityQuestionsApiUpdateSecurityQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApi
   */
  public updateSecurityQuestion(
    requestParameters: SecurityQuestionsApiUpdateSecurityQuestionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return SecurityQuestionsApiFp(this.configuration)
      .updateSecurityQuestion(
        requestParameters.securityQuestionID,
        requestParameters.securityQuestionInput,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates the number of security questions to render for a User.
   * @summary Update security question count
   * @param {SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SecurityQuestionsApi
   */
  public updateSecurityQuestionRenderCount(
    requestParameters: SecurityQuestionsApiUpdateSecurityQuestionRenderCountRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return SecurityQuestionsApiFp(this.configuration)
      .updateSecurityQuestionRenderCount(requestParameters.securityQuestionsRender, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
