/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { BatchUpload } from '../model';
// @ts-ignore
import type { BatchUploadErrorResponse } from '../model';
// @ts-ignore
import type { BatchUploadResponse } from '../model';
// @ts-ignore
import type { ErrorResponse } from '../model';
/**
 * UserMigrationApi - axios parameter creator
 * @export
 */
export const UserMigrationApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Uploads an array of Users with optional Password and migration configuration.
     * @summary Batch upload Users
     * @param {BatchUpload} batchUpload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    batchUpload: async (
      batchUpload: BatchUpload,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'batchUpload' is not null or undefined
      assertParamExists('batchUpload', 'batchUpload', batchUpload);
      const localVarPath = `/bulk/upsert`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication APIKey required
      await setApiKeyToObject(localVarQueryParameter, 'apikey', configuration);

      // authentication APISecret required
      await setApiKeyToObject(localVarQueryParameter, 'apisecret', configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        batchUpload,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * UserMigrationApi - functional programming interface
 * @export
 */
export const UserMigrationApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UserMigrationApiAxiosParamCreator(configuration);
  return {
    /**
     * Uploads an array of Users with optional Password and migration configuration.
     * @summary Batch upload Users
     * @param {BatchUpload} batchUpload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async batchUpload(
      batchUpload: BatchUpload,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BatchUploadResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.batchUpload(batchUpload, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UserMigrationApi.batchUpload']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * UserMigrationApi - factory interface
 * @export
 */
export const UserMigrationApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = UserMigrationApiFp(configuration);
  return {
    /**
     * Uploads an array of Users with optional Password and migration configuration.
     * @summary Batch upload Users
     * @param {UserMigrationApiBatchUploadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    batchUpload(
      requestParameters: UserMigrationApiBatchUploadRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BatchUploadResponse> {
      return localVarFp
        .batchUpload(requestParameters.batchUpload, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * UserMigrationApi - interface
 * @export
 * @interface UserMigrationApi
 */
export interface UserMigrationApiInterface {
  /**
   * Uploads an array of Users with optional Password and migration configuration.
   * @summary Batch upload Users
   * @param {UserMigrationApiBatchUploadRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserMigrationApiInterface
   */
  batchUpload(
    requestParameters: UserMigrationApiBatchUploadRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<BatchUploadResponse>;
}

/**
 * Request parameters for batchUpload operation in UserMigrationApi.
 * @export
 * @interface UserMigrationApiBatchUploadRequest
 */
export interface UserMigrationApiBatchUploadRequest {
  /**
   *
   * @type {BatchUpload}
   * @memberof UserMigrationApiBatchUpload
   */
  readonly batchUpload: BatchUpload;
}

/**
 * UserMigrationApi - object-oriented interface
 * @export
 * @class UserMigrationApi
 * @extends {BaseAPI}
 */
export class UserMigrationApi extends BaseAPI implements UserMigrationApiInterface {
  /**
   * Uploads an array of Users with optional Password and migration configuration.
   * @summary Batch upload Users
   * @param {UserMigrationApiBatchUploadRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserMigrationApi
   */
  public batchUpload(
    requestParameters: UserMigrationApiBatchUploadRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return UserMigrationApiFp(this.configuration)
      .batchUpload(requestParameters.batchUpload, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
