/* tslint:disable */
/* eslint-disable */
/**
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { AddWorkflowConfig } from '../model';
// @ts-ignore
import type { DeleteResponse } from '../model';
// @ts-ignore
import type { ErrorResponse } from '../model';
// @ts-ignore
import type { GetAllWorkflows200Response } from '../model';
// @ts-ignore
import type { IsDeleted } from '../model';
// @ts-ignore
import type { RestoreWorkflowVersion200Response } from '../model';
// @ts-ignore
import type { UpdateWorkflowConfig } from '../model';
// @ts-ignore
import type { VersionListResponse } from '../model';
// @ts-ignore
import type { WorkflowConfig } from '../model';
/**
 * WorkflowsApi - axios parameter creator
 * @export
 */
export const WorkflowsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Adds a new workflow configuration to the Tenant.
     * @summary Add workflow
     * @param {AddWorkflowConfig} addWorkflowConfig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addWorkflow: async (
      addWorkflowConfig: AddWorkflowConfig,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'addWorkflowConfig' is not null or undefined
      assertParamExists('addWorkflow', 'addWorkflowConfig', addWorkflowConfig);
      const localVarPath = `/v2/manage/workflows`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        addWorkflowConfig,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes an existing Workflow from the system.
     * @summary Delete Workflow
     * @param {string} workflowId The ID of the workflow.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWorkflow: async (
      workflowId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workflowId' is not null or undefined
      assertParamExists('deleteWorkflow', 'workflowId', workflowId);
      const localVarPath = `/v2/manage/workflows/{workflowId}`.replace(
        `{${'workflowId'}}`,
        encodeURIComponent(String(workflowId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes a specific version of a Workflow from the system.
     * @summary Delete Workflow Version
     * @param {string} workflowId The ID of the workflow.
     * @param {string} version The version identifier to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWorkflowVersion: async (
      workflowId: string,
      version: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workflowId' is not null or undefined
      assertParamExists('deleteWorkflowVersion', 'workflowId', workflowId);
      // verify required parameter 'version' is not null or undefined
      assertParamExists('deleteWorkflowVersion', 'version', version);
      const localVarPath = `/v2/manage/workflows/{workflowId}/versions/{version}`
        .replace(`{${'workflowId'}}`, encodeURIComponent(String(workflowId)))
        .replace(`{${'version'}}`, encodeURIComponent(String(version)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Returns a list of all available versions for a specified Workflow.
     * @summary List Workflow Versions
     * @param {string} workflowId The ID of the workflow.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllWorkflowVersionList: async (
      workflowId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workflowId' is not null or undefined
      assertParamExists('getAllWorkflowVersionList', 'workflowId', workflowId);
      const localVarPath = `/v2/manage/workflows/{workflowId}/versions`.replace(
        `{${'workflowId'}}`,
        encodeURIComponent(String(workflowId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves a list of all workflows configured for the Tenant.
     * @summary List workflows
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllWorkflows: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/manage/workflows`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves details of a specific Workflow using its unique identifier.
     * @summary Retrieve Workflow
     * @param {string} workflowId The ID of the workflow.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getWorkflowById: async (
      workflowId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workflowId' is not null or undefined
      assertParamExists('getWorkflowById', 'workflowId', workflowId);
      const localVarPath = `/v2/manage/workflows/{workflowId}`.replace(
        `{${'workflowId'}}`,
        encodeURIComponent(String(workflowId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Restores a specific version of a Workflow to its active state.
     * @summary Restore Workflow Version
     * @param {string} workflowId The ID of the workflow.
     * @param {string} version The version identifier to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    restoreWorkflowVersion: async (
      workflowId: string,
      version: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workflowId' is not null or undefined
      assertParamExists('restoreWorkflowVersion', 'workflowId', workflowId);
      // verify required parameter 'version' is not null or undefined
      assertParamExists('restoreWorkflowVersion', 'version', version);
      const localVarPath = `/v2/manage/workflows/{workflowId}/versions/{version}`
        .replace(`{${'workflowId'}}`, encodeURIComponent(String(workflowId)))
        .replace(`{${'version'}}`, encodeURIComponent(String(version)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates the configuration of an existing Workflow.
     * @summary Update Workflow
     * @param {string} workflowId The ID of the workflow.
     * @param {UpdateWorkflowConfig} updateWorkflowConfig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateWorkflow: async (
      workflowId: string,
      updateWorkflowConfig: UpdateWorkflowConfig,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workflowId' is not null or undefined
      assertParamExists('updateWorkflow', 'workflowId', workflowId);
      // verify required parameter 'updateWorkflowConfig' is not null or undefined
      assertParamExists('updateWorkflow', 'updateWorkflowConfig', updateWorkflowConfig);
      const localVarPath = `/v2/manage/workflows/{workflowId}`.replace(
        `{${'workflowId'}}`,
        encodeURIComponent(String(workflowId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication M2MBearerToken required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateWorkflowConfig,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * WorkflowsApi - functional programming interface
 * @export
 */
export const WorkflowsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = WorkflowsApiAxiosParamCreator(configuration);
  return {
    /**
     * Adds a new workflow configuration to the Tenant.
     * @summary Add workflow
     * @param {AddWorkflowConfig} addWorkflowConfig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addWorkflow(
      addWorkflowConfig: AddWorkflowConfig,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addWorkflow(
        addWorkflowConfig,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.addWorkflow']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes an existing Workflow from the system.
     * @summary Delete Workflow
     * @param {string} workflowId The ID of the workflow.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteWorkflow(
      workflowId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWorkflow(workflowId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.deleteWorkflow']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes a specific version of a Workflow from the system.
     * @summary Delete Workflow Version
     * @param {string} workflowId The ID of the workflow.
     * @param {string} version The version identifier to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteWorkflowVersion(
      workflowId: string,
      version: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IsDeleted>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWorkflowVersion(
        workflowId,
        version,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.deleteWorkflowVersion']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Returns a list of all available versions for a specified Workflow.
     * @summary List Workflow Versions
     * @param {string} workflowId The ID of the workflow.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllWorkflowVersionList(
      workflowId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VersionListResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAllWorkflowVersionList(
        workflowId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.getAllWorkflowVersionList']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves a list of all workflows configured for the Tenant.
     * @summary List workflows
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllWorkflows(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllWorkflows200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAllWorkflows(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.getAllWorkflows']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieves details of a specific Workflow using its unique identifier.
     * @summary Retrieve Workflow
     * @param {string} workflowId The ID of the workflow.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getWorkflowById(
      workflowId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkflowById(
        workflowId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.getWorkflowById']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Restores a specific version of a Workflow to its active state.
     * @summary Restore Workflow Version
     * @param {string} workflowId The ID of the workflow.
     * @param {string} version The version identifier to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async restoreWorkflowVersion(
      workflowId: string,
      version: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<RestoreWorkflowVersion200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.restoreWorkflowVersion(
        workflowId,
        version,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.restoreWorkflowVersion']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Updates the configuration of an existing Workflow.
     * @summary Update Workflow
     * @param {string} workflowId The ID of the workflow.
     * @param {UpdateWorkflowConfig} updateWorkflowConfig
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateWorkflow(
      workflowId: string,
      updateWorkflowConfig: UpdateWorkflowConfig,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateWorkflow(
        workflowId,
        updateWorkflowConfig,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['WorkflowsApi.updateWorkflow']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * WorkflowsApi - factory interface
 * @export
 */
export const WorkflowsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = WorkflowsApiFp(configuration);
  return {
    /**
     * Adds a new workflow configuration to the Tenant.
     * @summary Add workflow
     * @param {WorkflowsApiAddWorkflowRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addWorkflow(
      requestParameters: WorkflowsApiAddWorkflowRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<WorkflowConfig> {
      return localVarFp
        .addWorkflow(requestParameters.addWorkflowConfig, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes an existing Workflow from the system.
     * @summary Delete Workflow
     * @param {WorkflowsApiDeleteWorkflowRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWorkflow(
      requestParameters: WorkflowsApiDeleteWorkflowRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<DeleteResponse> {
      return localVarFp
        .deleteWorkflow(requestParameters.workflowId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes a specific version of a Workflow from the system.
     * @summary Delete Workflow Version
     * @param {WorkflowsApiDeleteWorkflowVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWorkflowVersion(
      requestParameters: WorkflowsApiDeleteWorkflowVersionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<IsDeleted> {
      return localVarFp
        .deleteWorkflowVersion(requestParameters.workflowId, requestParameters.version, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Returns a list of all available versions for a specified Workflow.
     * @summary List Workflow Versions
     * @param {WorkflowsApiGetAllWorkflowVersionListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllWorkflowVersionList(
      requestParameters: WorkflowsApiGetAllWorkflowVersionListRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<VersionListResponse> {
      return localVarFp
        .getAllWorkflowVersionList(requestParameters.workflowId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves a list of all workflows configured for the Tenant.
     * @summary List workflows
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllWorkflows(options?: RawAxiosRequestConfig): AxiosPromise<GetAllWorkflows200Response> {
      return localVarFp.getAllWorkflows(options).then((request) => request(axios, basePath));
    },
    /**
     * Retrieves details of a specific Workflow using its unique identifier.
     * @summary Retrieve Workflow
     * @param {WorkflowsApiGetWorkflowByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getWorkflowById(
      requestParameters: WorkflowsApiGetWorkflowByIdRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<WorkflowConfig> {
      return localVarFp
        .getWorkflowById(requestParameters.workflowId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Restores a specific version of a Workflow to its active state.
     * @summary Restore Workflow Version
     * @param {WorkflowsApiRestoreWorkflowVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    restoreWorkflowVersion(
      requestParameters: WorkflowsApiRestoreWorkflowVersionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RestoreWorkflowVersion200Response> {
      return localVarFp
        .restoreWorkflowVersion(requestParameters.workflowId, requestParameters.version, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Updates the configuration of an existing Workflow.
     * @summary Update Workflow
     * @param {WorkflowsApiUpdateWorkflowRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateWorkflow(
      requestParameters: WorkflowsApiUpdateWorkflowRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<WorkflowConfig> {
      return localVarFp
        .updateWorkflow(
          requestParameters.workflowId,
          requestParameters.updateWorkflowConfig,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * WorkflowsApi - interface
 * @export
 * @interface WorkflowsApi
 */
export interface WorkflowsApiInterface {
  /**
   * Adds a new workflow configuration to the Tenant.
   * @summary Add workflow
   * @param {WorkflowsApiAddWorkflowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  addWorkflow(
    requestParameters: WorkflowsApiAddWorkflowRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<WorkflowConfig>;

  /**
   * Deletes an existing Workflow from the system.
   * @summary Delete Workflow
   * @param {WorkflowsApiDeleteWorkflowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  deleteWorkflow(
    requestParameters: WorkflowsApiDeleteWorkflowRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<DeleteResponse>;

  /**
   * Deletes a specific version of a Workflow from the system.
   * @summary Delete Workflow Version
   * @param {WorkflowsApiDeleteWorkflowVersionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  deleteWorkflowVersion(
    requestParameters: WorkflowsApiDeleteWorkflowVersionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<IsDeleted>;

  /**
   * Returns a list of all available versions for a specified Workflow.
   * @summary List Workflow Versions
   * @param {WorkflowsApiGetAllWorkflowVersionListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  getAllWorkflowVersionList(
    requestParameters: WorkflowsApiGetAllWorkflowVersionListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<VersionListResponse>;

  /**
   * Retrieves a list of all workflows configured for the Tenant.
   * @summary List workflows
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  getAllWorkflows(options?: RawAxiosRequestConfig): AxiosPromise<GetAllWorkflows200Response>;

  /**
   * Retrieves details of a specific Workflow using its unique identifier.
   * @summary Retrieve Workflow
   * @param {WorkflowsApiGetWorkflowByIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  getWorkflowById(
    requestParameters: WorkflowsApiGetWorkflowByIdRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<WorkflowConfig>;

  /**
   * Restores a specific version of a Workflow to its active state.
   * @summary Restore Workflow Version
   * @param {WorkflowsApiRestoreWorkflowVersionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  restoreWorkflowVersion(
    requestParameters: WorkflowsApiRestoreWorkflowVersionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RestoreWorkflowVersion200Response>;

  /**
   * Updates the configuration of an existing Workflow.
   * @summary Update Workflow
   * @param {WorkflowsApiUpdateWorkflowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApiInterface
   */
  updateWorkflow(
    requestParameters: WorkflowsApiUpdateWorkflowRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<WorkflowConfig>;
}

/**
 * Request parameters for addWorkflow operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiAddWorkflowRequest
 */
export interface WorkflowsApiAddWorkflowRequest {
  /**
   *
   * @type {AddWorkflowConfig}
   * @memberof WorkflowsApiAddWorkflow
   */
  readonly addWorkflowConfig: AddWorkflowConfig;
}

/**
 * Request parameters for deleteWorkflow operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiDeleteWorkflowRequest
 */
export interface WorkflowsApiDeleteWorkflowRequest {
  /**
   * The ID of the workflow.
   * @type {string}
   * @memberof WorkflowsApiDeleteWorkflow
   */
  readonly workflowId: string;
}

/**
 * Request parameters for deleteWorkflowVersion operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiDeleteWorkflowVersionRequest
 */
export interface WorkflowsApiDeleteWorkflowVersionRequest {
  /**
   * The ID of the workflow.
   * @type {string}
   * @memberof WorkflowsApiDeleteWorkflowVersion
   */
  readonly workflowId: string;

  /**
   * The version identifier to delete.
   * @type {string}
   * @memberof WorkflowsApiDeleteWorkflowVersion
   */
  readonly version: string;
}

/**
 * Request parameters for getAllWorkflowVersionList operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiGetAllWorkflowVersionListRequest
 */
export interface WorkflowsApiGetAllWorkflowVersionListRequest {
  /**
   * The ID of the workflow.
   * @type {string}
   * @memberof WorkflowsApiGetAllWorkflowVersionList
   */
  readonly workflowId: string;
}

/**
 * Request parameters for getWorkflowById operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiGetWorkflowByIdRequest
 */
export interface WorkflowsApiGetWorkflowByIdRequest {
  /**
   * The ID of the workflow.
   * @type {string}
   * @memberof WorkflowsApiGetWorkflowById
   */
  readonly workflowId: string;
}

/**
 * Request parameters for restoreWorkflowVersion operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiRestoreWorkflowVersionRequest
 */
export interface WorkflowsApiRestoreWorkflowVersionRequest {
  /**
   * The ID of the workflow.
   * @type {string}
   * @memberof WorkflowsApiRestoreWorkflowVersion
   */
  readonly workflowId: string;

  /**
   * The version identifier to delete.
   * @type {string}
   * @memberof WorkflowsApiRestoreWorkflowVersion
   */
  readonly version: string;
}

/**
 * Request parameters for updateWorkflow operation in WorkflowsApi.
 * @export
 * @interface WorkflowsApiUpdateWorkflowRequest
 */
export interface WorkflowsApiUpdateWorkflowRequest {
  /**
   * The ID of the workflow.
   * @type {string}
   * @memberof WorkflowsApiUpdateWorkflow
   */
  readonly workflowId: string;

  /**
   *
   * @type {UpdateWorkflowConfig}
   * @memberof WorkflowsApiUpdateWorkflow
   */
  readonly updateWorkflowConfig: UpdateWorkflowConfig;
}

/**
 * WorkflowsApi - object-oriented interface
 * @export
 * @class WorkflowsApi
 * @extends {BaseAPI}
 */
export class WorkflowsApi extends BaseAPI implements WorkflowsApiInterface {
  /**
   * Adds a new workflow configuration to the Tenant.
   * @summary Add workflow
   * @param {WorkflowsApiAddWorkflowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public addWorkflow(
    requestParameters: WorkflowsApiAddWorkflowRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .addWorkflow(requestParameters.addWorkflowConfig, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes an existing Workflow from the system.
   * @summary Delete Workflow
   * @param {WorkflowsApiDeleteWorkflowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public deleteWorkflow(
    requestParameters: WorkflowsApiDeleteWorkflowRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .deleteWorkflow(requestParameters.workflowId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes a specific version of a Workflow from the system.
   * @summary Delete Workflow Version
   * @param {WorkflowsApiDeleteWorkflowVersionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public deleteWorkflowVersion(
    requestParameters: WorkflowsApiDeleteWorkflowVersionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .deleteWorkflowVersion(requestParameters.workflowId, requestParameters.version, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Returns a list of all available versions for a specified Workflow.
   * @summary List Workflow Versions
   * @param {WorkflowsApiGetAllWorkflowVersionListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public getAllWorkflowVersionList(
    requestParameters: WorkflowsApiGetAllWorkflowVersionListRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .getAllWorkflowVersionList(requestParameters.workflowId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves a list of all workflows configured for the Tenant.
   * @summary List workflows
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public getAllWorkflows(options?: RawAxiosRequestConfig) {
    return WorkflowsApiFp(this.configuration)
      .getAllWorkflows(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieves details of a specific Workflow using its unique identifier.
   * @summary Retrieve Workflow
   * @param {WorkflowsApiGetWorkflowByIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public getWorkflowById(
    requestParameters: WorkflowsApiGetWorkflowByIdRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .getWorkflowById(requestParameters.workflowId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Restores a specific version of a Workflow to its active state.
   * @summary Restore Workflow Version
   * @param {WorkflowsApiRestoreWorkflowVersionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public restoreWorkflowVersion(
    requestParameters: WorkflowsApiRestoreWorkflowVersionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .restoreWorkflowVersion(requestParameters.workflowId, requestParameters.version, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates the configuration of an existing Workflow.
   * @summary Update Workflow
   * @param {WorkflowsApiUpdateWorkflowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkflowsApi
   */
  public updateWorkflow(
    requestParameters: WorkflowsApiUpdateWorkflowRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return WorkflowsApiFp(this.configuration)
      .updateWorkflow(requestParameters.workflowId, requestParameters.updateWorkflowConfig, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
